// Code generated by beak gen:caller-detection from clients/caller-detection.yaml. DO NOT EDIT.

export interface CallerRule {
  env: string;
  equals?: string;
  name?: string;
  passthrough?: boolean;
}

export const callerRules: CallerRule[] = [
  { env: "CLAUDECODE", name: "claude-code" },
  { env: "CODEX_CI", name: "codex" },
  { env: "GEMINI_CLI", name: "gemini" },
  { env: "QWEN_CODE", name: "qwen" },
  { env: "PI_CODING_AGENT", name: "pi" },
  { env: "OPENCODE", name: "opencode" },
  { env: "CLINE_ACTIVE", name: "cline" },
  { env: "ROO_ACTIVE", name: "roo" },
  { env: "SAND_AGENT", name: "grokbot" },
  { env: "__CFBundleIdentifier", equals: "com.anysphere.sand", name: "grokbot" },
  { env: "CURSOR_TRACE_ID", name: "cursor" },
  { env: "CURSOR_AGENT", name: "cursor" },
  { env: "ANTIGRAVITY_AGENT", name: "antigravity" },
  { env: "AUGMENT_AGENT", name: "augment" },
  { env: "AGENT", passthrough: true },
  { env: "AI_AGENT", passthrough: true },
  { env: "REPL_ID", name: "replit" },
  { env: "CI", name: "ci" },
  { env: "GITHUB_ACTIONS", name: "ci" },
  { env: "TERM_PROGRAM", equals: "zed", name: "zed" },
  { env: "ZED_TERM", name: "zed" },
  { env: "TERM_PROGRAM", equals: "kiro", name: "kiro" },
  { env: "TERM_PROGRAM", equals: "WarpTerminal", name: "warp" },
  { env: "TERMINAL_EMULATOR", equals: "JetBrains-JediTerm", name: "jetbrains" },
  { env: "__CFBundleIdentifier", equals: "com.exafunction.windsurf", name: "windsurf" },
  { env: "TERM_PROGRAM", equals: "vscode", name: "vscode" },
];

export const callerBooleanishSkip: ReadonlySet<string> = new Set(["1", "0", "true", "false", "yes", "no", "on", "off"]);

export const callerDefault = "shell";
