// Code generated by beak gen:caller-detection from clients/caller-detection.yaml. DO NOT EDIT.

export interface CallerRule {
  env: string;
  execution: string;
  verification: string;
  equals?: string;
  name?: string;
  passthrough?: boolean;
}

export const callerRules: CallerRule[] = [
  { env: "CLAUDE_CODE_CHILD_SESSION", execution: "declared", verification: "verified", name: "claude-code" },
  { env: "CLAUDECODE", execution: "unknown", verification: "verified", name: "claude-code" },
  { env: "CODEX_CI", execution: "declared", verification: "verified", name: "codex" },
  { env: "GEMINI_CLI", execution: "declared", verification: "verified", name: "gemini" },
  { env: "QWEN_CODE", execution: "declared", verification: "verified", name: "qwen" },
  { env: "PI_CODING_AGENT", execution: "declared", verification: "verified", name: "pi" },
  { env: "OPENCODE", execution: "declared", verification: "verified", name: "opencode" },
  { env: "CLINE_ACTIVE", execution: "unknown", verification: "verified", name: "cline" },
  { env: "ROO_ACTIVE", execution: "unknown", verification: "verified", name: "roo" },
  { env: "SAND_AGENT", execution: "unknown", verification: "unverified", name: "grokbot" },
  { env: "__CFBundleIdentifier", execution: "unknown", verification: "unverified", equals: "com.anysphere.sand", name: "grokbot" },
  { env: "CURSOR_AGENT", execution: "declared", verification: "verified", name: "cursor" },
  { env: "CURSOR_TRACE_ID", execution: "unknown", verification: "unverified", name: "cursor" },
  { env: "ANTIGRAVITY_AGENT", execution: "unknown", verification: "unverified", name: "antigravity" },
  { env: "AUGMENT_AGENT", execution: "unknown", verification: "unverified", name: "augment" },
  { env: "AGENT", execution: "declared", verification: "verified", passthrough: true },
  { env: "AI_AGENT", execution: "declared", verification: "verified", passthrough: true },
  { env: "REPL_ID", execution: "unknown", verification: "unverified", name: "replit" },
  { env: "CI", execution: "unknown", verification: "unverified", name: "ci" },
  { env: "GITHUB_ACTIONS", execution: "unknown", verification: "unverified", name: "ci" },
  { env: "TERM_PROGRAM", execution: "unknown", verification: "unverified", equals: "zed", name: "zed" },
  { env: "ZED_TERM", execution: "unknown", verification: "unverified", name: "zed" },
  { env: "TERM_PROGRAM", execution: "unknown", verification: "unverified", equals: "kiro", name: "kiro" },
  { env: "TERM_PROGRAM", execution: "unknown", verification: "unverified", equals: "WarpTerminal", name: "warp" },
  { env: "TERMINAL_EMULATOR", execution: "unknown", verification: "unverified", equals: "JetBrains-JediTerm", name: "jetbrains" },
  { env: "__CFBundleIdentifier", execution: "unknown", verification: "unverified", equals: "com.exafunction.windsurf", name: "windsurf" },
  { env: "TERM_PROGRAM", execution: "unknown", verification: "unverified", equals: "vscode", name: "vscode" },
];

export const callerModelEnv: Readonly<Record<string, string>> = {
  "claude-code": "ANTHROPIC_MODEL",
  "gemini": "GEMINI_MODEL",
};

export const callerPublicModels: ReadonlySet<string> = new Set(["best", "fable", "opus[1m]", "sonnet[1m]", "opusplan[1m]", "haiku", "opus", "opusplan", "sonnet", "claude-fable-5-1", "claude-opus-5-5", "claude-sonnet-5-5", "claude-haiku-4-5", "claude-haiku-4-5-20251001", "gemini-3.8-flash", "gemini-3.7-flash", "gemini-3.6-flash", "gemini-3.5-flash", "gemini-3.5-flash-lite", "gemini-3.1-flash-lite", "gemini-3.1-pro-preview", "gemini-3-flash-preview", "gemini-2.5-pro", "gemini-2.5-flash", "gemini-2.5-flash-lite"]);

export const callerFalseLike: ReadonlySet<string> = new Set(["0", "false", "no", "off"]);

export const callerBooleanishSkip: ReadonlySet<string> = new Set(["1", "0", "true", "false", "yes", "no", "on", "off"]);

export const callerDefault = "shell";
