// Code generated by beak gen:event-consts. DO NOT EDIT.

/**
 * Webhook event types known at this SDK version. The wire value is an open
 * string: a value added by a newer server is returned by `unwrap` unchanged,
 * so switch on these with a `default` branch.
 */
export const WebhookEventType = {
  DomainFailed: "domain.failed",
  DomainVerified: "domain.verified",
  EmailAccepted: "email.accepted",
  EmailBounced: "email.bounced",
  EmailCanceled: "email.canceled",
  EmailClicked: "email.clicked",
  EmailComplained: "email.complained",
  EmailDeferred: "email.deferred",
  EmailDelivered: "email.delivered",
  EmailListUnsubscribed: "email.list_unsubscribed",
  EmailMailboxMessageDelivered: "email_mailbox.message_delivered",
  EmailMailboxMessageFailed: "email_mailbox.message_failed",
  EmailMailboxMessageReceived: "email_mailbox.message_received",
  EmailMailboxMessageSent: "email_mailbox.message_sent",
  EmailMailboxSuspended: "email_mailbox.suspended",
  EmailMailboxThreadCreated: "email_mailbox.thread_created",
  EmailOpened: "email.opened",
  EmailOutOfBandBounce: "email.out_of_band_bounce",
  EmailProcessed: "email.processed",
  EmailReceived: "email.received",
  EmailRejected: "email.rejected",
  EmailScheduled: "email.scheduled",
  EmailSuppressionCreated: "email_suppression.created",
  EmailUnsubscribed: "email.unsubscribed",
  SmsAccepted: "sms.accepted",
  SmsDelivered: "sms.delivered",
  SmsExpired: "sms.expired",
  SmsFailed: "sms.failed",
  SmsReceived: "sms.received",
  SmsRejected: "sms.rejected",
  SmsSent: "sms.sent",
  SmsUndelivered: "sms.undelivered",
  VerifyAttemptDelivered: "verify.attempt.delivered",
  VerifyAttemptSent: "verify.attempt.sent",
  VerifyAttemptUndelivered: "verify.attempt.undelivered",
  VerifyVerificationCreated: "verify.verification.created",
  VerifyVerificationVerified: "verify.verification.verified",
  VoiceCallAnswered: "voice_call.answered",
  VoiceCallEnded: "voice_call.ended",
  VoiceCallInitiated: "voice_call.initiated",
  WhatsappAccepted: "whatsapp.accepted",
  WhatsappDelivered: "whatsapp.delivered",
  WhatsappFailed: "whatsapp.failed",
  WhatsappRead: "whatsapp.read",
  WhatsappReceived: "whatsapp.received",
  WhatsappRejected: "whatsapp.rejected",
  WhatsappSent: "whatsapp.sent",
} as const;

/** A known webhook event type value. */
export type WebhookEventTypeValue =
  (typeof WebhookEventType)[keyof typeof WebhookEventType];
