// Code generated by beak gen:event-consts. DO NOT EDIT.

/**
 * Values of EmailEventType known at this SDK version. The wire value is an open
 * string: a value added by a newer server deserializes unchanged, so switch on
 * these with a `default` branch rather than treating the set as closed.
 */
export const EmailEventType = {
  EmailAccepted: "email.accepted",
  EmailBounced: "email.bounced",
  EmailCanceled: "email.canceled",
  EmailClicked: "email.clicked",
  EmailComplained: "email.complained",
  EmailDeferred: "email.deferred",
  EmailDelivered: "email.delivered",
  EmailListUnsubscribed: "email.list_unsubscribed",
  EmailOpened: "email.opened",
  EmailOutOfBandBounce: "email.out_of_band_bounce",
  EmailProcessed: "email.processed",
  EmailRejected: "email.rejected",
  EmailScheduled: "email.scheduled",
  EmailUnsubscribed: "email.unsubscribed",
} as const;

/** A known EmailEventType value. */
export type EmailEventTypeValue = (typeof EmailEventType)[keyof typeof EmailEventType];

/**
 * Values of EmailLookupFlag known at this SDK version. The wire value is an open
 * string: a value added by a newer server deserializes unchanged, so switch on
 * these with a `default` branch rather than treating the set as closed.
 */
export const EmailLookupFlag = {
  Disposable: "disposable",
  FreeProvider: "free_provider",
  Role: "role",
} as const;

/** A known EmailLookupFlag value. */
export type EmailLookupFlagValue = (typeof EmailLookupFlag)[keyof typeof EmailLookupFlag];

/**
 * Values of EmailLookupReason known at this SDK version. The wire value is an open
 * string: a value added by a newer server deserializes unchanged, so switch on
 * these with a `default` branch rather than treating the set as closed.
 */
export const EmailLookupReason = {
  InvalidDomain: "invalid_domain",
  InvalidRecipient: "invalid_recipient",
  InvalidSyntax: "invalid_syntax",
} as const;

/** A known EmailLookupReason value. */
export type EmailLookupReasonValue = (typeof EmailLookupReason)[keyof typeof EmailLookupReason];

/**
 * Values of EmailLookupResult known at this SDK version. The wire value is an open
 * string: a value added by a newer server deserializes unchanged, so switch on
 * these with a `default` branch rather than treating the set as closed.
 */
export const EmailLookupResult = {
  Neutral: "neutral",
  Risky: "risky",
  Typo: "typo",
  Undeliverable: "undeliverable",
  Valid: "valid",
} as const;

/** A known EmailLookupResult value. */
export type EmailLookupResultValue = (typeof EmailLookupResult)[keyof typeof EmailLookupResult];

/**
 * Values of EmailTemplateSource known at this SDK version. The wire value is an open
 * string: a value added by a newer server deserializes unchanged, so switch on
 * these with a `default` branch rather than treating the set as closed.
 */
export const EmailTemplateSource = {
  Html: "html",
} as const;

/** A known EmailTemplateSource value. */
export type EmailTemplateSourceValue = (typeof EmailTemplateSource)[keyof typeof EmailTemplateSource];

/**
 * Values of LookupFlag known at this SDK version. The wire value is an open
 * string: a value added by a newer server deserializes unchanged, so switch on
 * these with a `default` branch rather than treating the set as closed.
 */
export const LookupFlag = {
  Ported: "ported",
} as const;

/** A known LookupFlag value. */
export type LookupFlagValue = (typeof LookupFlag)[keyof typeof LookupFlag];

/**
 * Values of LookupPropertyStatus known at this SDK version. The wire value is an open
 * string: a value added by a newer server deserializes unchanged, so switch on
 * these with a `default` branch rather than treating the set as closed.
 */
export const LookupPropertyStatus = {
  Inconclusive: "inconclusive",
  Ok: "ok",
  Unavailable: "unavailable",
} as const;

/** A known LookupPropertyStatus value. */
export type LookupPropertyStatusValue = (typeof LookupPropertyStatus)[keyof typeof LookupPropertyStatus];

/**
 * Values of NumberCapability known at this SDK version. The wire value is an open
 * string: a value added by a newer server deserializes unchanged, so switch on
 * these with a `default` branch rather than treating the set as closed.
 */
export const NumberCapability = {
  Mms: "mms",
  Sms: "sms",
  Voice: "voice",
} as const;

/** A known NumberCapability value. */
export type NumberCapabilityValue = (typeof NumberCapability)[keyof typeof NumberCapability];

/**
 * Values of NumberType known at this SDK version. The wire value is an open
 * string: a value added by a newer server deserializes unchanged, so switch on
 * these with a `default` branch rather than treating the set as closed.
 */
export const NumberType = {
  Local: "local",
  Mobile: "mobile",
  National: "national",
  ShortCode: "short_code",
  ShortCodeFteu: "short_code_fteu",
  TollFree: "toll_free",
} as const;

/** A known NumberType value. */
export type NumberTypeValue = (typeof NumberType)[keyof typeof NumberType];

/**
 * Values of NumbersOrderStatus known at this SDK version. The wire value is an open
 * string: a value added by a newer server deserializes unchanged, so switch on
 * these with a `default` branch rather than treating the set as closed.
 */
export const NumbersOrderStatus = {
  Charging: "charging",
  Completed: "completed",
  Failed: "failed",
  Ordering: "ordering",
  Pending: "pending",
} as const;

/** A known NumbersOrderStatus value. */
export type NumbersOrderStatusValue = (typeof NumbersOrderStatus)[keyof typeof NumbersOrderStatus];

/**
 * Values of PreferenceChannel known at this SDK version. The wire value is an open
 * string: a value added by a newer server deserializes unchanged, so switch on
 * these with a `default` branch rather than treating the set as closed.
 */
export const PreferenceChannel = {
  Email: "email",
  Sms: "sms",
  Whatsapp: "whatsapp",
} as const;

/** A known PreferenceChannel value. */
export type PreferenceChannelValue = (typeof PreferenceChannel)[keyof typeof PreferenceChannel];

/**
 * Values of PreferenceOrigin known at this SDK version. The wire value is an open
 * string: a value added by a newer server deserializes unchanged, so switch on
 * these with a `default` branch rather than treating the set as closed.
 */
export const PreferenceOrigin = {
  ApiKey: "api_key",
  Import: "import",
  Keyword: "keyword",
  PreferencePage: "preference_page",
  UnsubscribeEvent: "unsubscribe_event",
  UnsubscribeLink: "unsubscribe_link",
  User: "user",
} as const;

/** A known PreferenceOrigin value. */
export type PreferenceOriginValue = (typeof PreferenceOrigin)[keyof typeof PreferenceOrigin];

/**
 * Values of SMSErrorCode known at this SDK version. The wire value is an open
 * string: a value added by a newer server deserializes unchanged, so switch on
 * these with a `default` branch rather than treating the set as closed.
 */
export const SMSErrorCode = {
  BlockedByCarrier: "blocked_by_carrier",
  BlockedByRecipient: "blocked_by_recipient",
  ContentRejected: "content_rejected",
  InsufficientBalance: "insufficient_balance",
  InvalidDestination: "invalid_destination",
  LandlineUnreachable: "landline_unreachable",
  ProviderUnavailable: "provider_unavailable",
  RecipientOptedOut: "recipient_opted_out",
  SenderUnregistered: "sender_unregistered",
  Unknown: "unknown",
  Unreachable: "unreachable",
} as const;

/** A known SMSErrorCode value. */
export type SMSErrorCodeValue = (typeof SMSErrorCode)[keyof typeof SMSErrorCode];

/**
 * Values of SMSKeywordOperation known at this SDK version. The wire value is an open
 * string: a value added by a newer server deserializes unchanged, so switch on
 * these with a `default` branch rather than treating the set as closed.
 */
export const SMSKeywordOperation = {
  Confirm: "confirm",
  Custom: "custom",
  Help: "help",
  Info: "info",
  Start: "start",
  Stop: "stop",
} as const;

/** A known SMSKeywordOperation value. */
export type SMSKeywordOperationValue = (typeof SMSKeywordOperation)[keyof typeof SMSKeywordOperation];

/**
 * Values of SMSSuppressionCoverage known at this SDK version. The wire value is an open
 * string: a value added by a newer server deserializes unchanged, so switch on
 * these with a `default` branch rather than treating the set as closed.
 */
export const SMSSuppressionCoverage = {
  All: "all",
  NonTransactional: "non_transactional",
} as const;

/** A known SMSSuppressionCoverage value. */
export type SMSSuppressionCoverageValue = (typeof SMSSuppressionCoverage)[keyof typeof SMSSuppressionCoverage];

/**
 * Values of SMSSuppressionEndReason known at this SDK version. The wire value is an open
 * string: a value added by a newer server deserializes unchanged, so switch on
 * these with a `default` branch rather than treating the set as closed.
 */
export const SMSSuppressionEndReason = {
  ApiKey: "api_key",
  CarrierCleared: "carrier_cleared",
  KeywordStart: "keyword_start",
  User: "user",
} as const;

/** A known SMSSuppressionEndReason value. */
export type SMSSuppressionEndReasonValue = (typeof SMSSuppressionEndReason)[keyof typeof SMSSuppressionEndReason];

/**
 * Values of SMSSuppressionOrigin known at this SDK version. The wire value is an open
 * string: a value added by a newer server deserializes unchanged, so switch on
 * these with a `default` branch rather than treating the set as closed.
 */
export const SMSSuppressionOrigin = {
  ApiKey: "api_key",
  DlrEvent: "dlr_event",
  Keyword: "keyword",
  User: "user",
} as const;

/** A known SMSSuppressionOrigin value. */
export type SMSSuppressionOriginValue = (typeof SMSSuppressionOrigin)[keyof typeof SMSSuppressionOrigin];

/**
 * Values of SMSSuppressionReason known at this SDK version. The wire value is an open
 * string: a value added by a newer server deserializes unchanged, so switch on
 * these with a `default` branch rather than treating the set as closed.
 */
export const SMSSuppressionReason = {
  CarrierOptedOut: "carrier_opted_out",
  KeywordStop: "keyword_stop",
  Manual: "manual",
} as const;

/** A known SMSSuppressionReason value. */
export type SMSSuppressionReasonValue = (typeof SMSSuppressionReason)[keyof typeof SMSSuppressionReason];

/**
 * Values of TemplateLanguageStatus known at this SDK version. The wire value is an open
 * string: a value added by a newer server deserializes unchanged, so switch on
 * these with a `default` branch rather than treating the set as closed.
 */
export const TemplateLanguageStatus = {
  Draft: "draft",
  Live: "live",
  Superseded: "superseded",
} as const;

/** A known TemplateLanguageStatus value. */
export type TemplateLanguageStatusValue = (typeof TemplateLanguageStatus)[keyof typeof TemplateLanguageStatus];

/**
 * Values of VerificationAttemptFailureReason known at this SDK version. The wire value is an open
 * string: a value added by a newer server deserializes unchanged, so switch on
 * these with a `default` branch rather than treating the set as closed.
 */
export const VerificationAttemptFailureReason = {
  CarrierRejected: "carrier_rejected",
  ChannelDisabled: "channel_disabled",
  ChannelRestricted: "channel_restricted",
  ChannelUnavailable: "channel_unavailable",
  DeliveryTimeout: "delivery_timeout",
  HardBounce: "hard_bounce",
  NotBillable: "not_billable",
  SoftBounce: "soft_bounce",
  Undelivered: "undelivered",
} as const;

/** A known VerificationAttemptFailureReason value. */
export type VerificationAttemptFailureReasonValue = (typeof VerificationAttemptFailureReason)[keyof typeof VerificationAttemptFailureReason];

/**
 * Values of VerificationChannel known at this SDK version. The wire value is an open
 * string: a value added by a newer server deserializes unchanged, so switch on
 * these with a `default` branch rather than treating the set as closed.
 */
export const VerificationChannel = {
  Email: "email",
  Sms: "sms",
  Telegram: "telegram",
  Voice: "voice",
  Whatsapp: "whatsapp",
} as const;

/** A known VerificationChannel value. */
export type VerificationChannelValue = (typeof VerificationChannel)[keyof typeof VerificationChannel];

/**
 * Values of VerificationTerminalReason known at this SDK version. The wire value is an open
 * string: a value added by a newer server deserializes unchanged, so switch on
 * these with a `default` branch rather than treating the set as closed.
 */
export const VerificationTerminalReason = {
  AttemptsExhausted: "attempts_exhausted",
  TtlElapsed: "ttl_elapsed",
  Undeliverable: "undeliverable",
} as const;

/** A known VerificationTerminalReason value. */
export type VerificationTerminalReasonValue = (typeof VerificationTerminalReason)[keyof typeof VerificationTerminalReason];

/**
 * Values of WhatsAppBusinessAccountMarketingMessagesStatus known at this SDK version. The wire value is an open
 * string: a value added by a newer server deserializes unchanged, so switch on
 * these with a `default` branch rather than treating the set as closed.
 */
export const WhatsAppBusinessAccountMarketingMessagesStatus = {
  Eligible: "eligible",
  Onboarded: "onboarded",
} as const;

/** A known WhatsAppBusinessAccountMarketingMessagesStatus value. */
export type WhatsAppBusinessAccountMarketingMessagesStatusValue = (typeof WhatsAppBusinessAccountMarketingMessagesStatus)[keyof typeof WhatsAppBusinessAccountMarketingMessagesStatus];

/**
 * Values of WhatsAppBusinessAccountReviewStatus known at this SDK version. The wire value is an open
 * string: a value added by a newer server deserializes unchanged, so switch on
 * these with a `default` branch rather than treating the set as closed.
 */
export const WhatsAppBusinessAccountReviewStatus = {
  Approved: "approved",
  Deferred: "deferred",
  Pending: "pending",
  Rejected: "rejected",
} as const;

/** A known WhatsAppBusinessAccountReviewStatus value. */
export type WhatsAppBusinessAccountReviewStatusValue = (typeof WhatsAppBusinessAccountReviewStatus)[keyof typeof WhatsAppBusinessAccountReviewStatus];

/**
 * Values of WhatsAppBusinessAccountStatus known at this SDK version. The wire value is an open
 * string: a value added by a newer server deserializes unchanged, so switch on
 * these with a `default` branch rather than treating the set as closed.
 */
export const WhatsAppBusinessAccountStatus = {
  Active: "active",
} as const;

/** A known WhatsAppBusinessAccountStatus value. */
export type WhatsAppBusinessAccountStatusValue = (typeof WhatsAppBusinessAccountStatus)[keyof typeof WhatsAppBusinessAccountStatus];

/**
 * Values of WhatsAppBusinessPortfolioMarketingMessagesStatus known at this SDK version. The wire value is an open
 * string: a value added by a newer server deserializes unchanged, so switch on
 * these with a `default` branch rather than treating the set as closed.
 */
export const WhatsAppBusinessPortfolioMarketingMessagesStatus = {
  NotStarted: "not_started",
  RequestSent: "request_sent",
  TermOfServiceSigned: "term_of_service_signed",
} as const;

/** A known WhatsAppBusinessPortfolioMarketingMessagesStatus value. */
export type WhatsAppBusinessPortfolioMarketingMessagesStatusValue = (typeof WhatsAppBusinessPortfolioMarketingMessagesStatus)[keyof typeof WhatsAppBusinessPortfolioMarketingMessagesStatus];

/**
 * Values of WhatsAppBusinessVerificationStatus known at this SDK version. The wire value is an open
 * string: a value added by a newer server deserializes unchanged, so switch on
 * these with a `default` branch rather than treating the set as closed.
 */
export const WhatsAppBusinessVerificationStatus = {
  Expired: "expired",
  Failed: "failed",
  Ineligible: "ineligible",
  NotVerified: "not_verified",
  Pending: "pending",
  PendingNeedMoreInfo: "pending_need_more_info",
  PendingSubmission: "pending_submission",
  Rejected: "rejected",
  Revoked: "revoked",
  Verified: "verified",
} as const;

/** A known WhatsAppBusinessVerificationStatus value. */
export type WhatsAppBusinessVerificationStatusValue = (typeof WhatsAppBusinessVerificationStatus)[keyof typeof WhatsAppBusinessVerificationStatus];

/**
 * Values of WhatsAppBusinessVertical known at this SDK version. The wire value is an open
 * string: a value added by a newer server deserializes unchanged, so switch on
 * these with a `default` branch rather than treating the set as closed.
 */
export const WhatsAppBusinessVertical = {
  Alcohol: "alcohol",
  Apparel: "apparel",
  Auto: "auto",
  Beauty: "beauty",
  Edu: "edu",
  Entertain: "entertain",
  EventPlan: "event_plan",
  Finance: "finance",
  Govt: "govt",
  Grocery: "grocery",
  Health: "health",
  Hotel: "hotel",
  Nonprofit: "nonprofit",
  OnlineGambling: "online_gambling",
  OtcDrugs: "otc_drugs",
  Other: "other",
  PhysicalGambling: "physical_gambling",
  ProfServices: "prof_services",
  Restaurant: "restaurant",
  Retail: "retail",
  Travel: "travel",
} as const;

/** A known WhatsAppBusinessVertical value. */
export type WhatsAppBusinessVerticalValue = (typeof WhatsAppBusinessVertical)[keyof typeof WhatsAppBusinessVertical];

/**
 * Values of WhatsAppDisplayNameStatus known at this SDK version. The wire value is an open
 * string: a value added by a newer server deserializes unchanged, so switch on
 * these with a `default` branch rather than treating the set as closed.
 */
export const WhatsAppDisplayNameStatus = {
  Approved: "approved",
  AvailableWithoutReview: "available_without_review",
  Declined: "declined",
  Expired: "expired",
  NonExists: "non_exists",
  None: "none",
  PendingReview: "pending_review",
} as const;

/** A known WhatsAppDisplayNameStatus value. */
export type WhatsAppDisplayNameStatusValue = (typeof WhatsAppDisplayNameStatus)[keyof typeof WhatsAppDisplayNameStatus];

/**
 * Values of WhatsAppErrorCode known at this SDK version. The wire value is an open
 * string: a value added by a newer server deserializes unchanged, so switch on
 * these with a `default` branch rather than treating the set as closed.
 */
export const WhatsAppErrorCode = {
  InsufficientBalance: "insufficient_balance",
  InternalError: "internal_error",
  MediaRejected: "media_rejected",
  PriceNotFound: "price_not_found",
  RateLimited: "rate_limited",
  RecipientSuppressed: "recipient_suppressed",
  ServiceWindowExpired: "service_window_expired",
  Undeliverable: "undeliverable",
} as const;

/** A known WhatsAppErrorCode value. */
export type WhatsAppErrorCodeValue = (typeof WhatsAppErrorCode)[keyof typeof WhatsAppErrorCode];

/**
 * Values of WhatsAppEventType known at this SDK version. The wire value is an open
 * string: a value added by a newer server deserializes unchanged, so switch on
 * these with a `default` branch rather than treating the set as closed.
 */
export const WhatsAppEventType = {
  WhatsappAccepted: "whatsapp.accepted",
  WhatsappDelivered: "whatsapp.delivered",
  WhatsappFailed: "whatsapp.failed",
  WhatsappRead: "whatsapp.read",
  WhatsappReceived: "whatsapp.received",
  WhatsappRejected: "whatsapp.rejected",
  WhatsappSent: "whatsapp.sent",
} as const;

/** A known WhatsAppEventType value. */
export type WhatsAppEventTypeValue = (typeof WhatsAppEventType)[keyof typeof WhatsAppEventType];

/**
 * Values of WhatsAppInteractiveButtonType known at this SDK version. The wire value is an open
 * string: a value added by a newer server deserializes unchanged, so switch on
 * these with a `default` branch rather than treating the set as closed.
 */
export const WhatsAppInteractiveButtonType = {
  CtaUrl: "cta_url",
  QuickReply: "quick_reply",
} as const;

/** A known WhatsAppInteractiveButtonType value. */
export type WhatsAppInteractiveButtonTypeValue = (typeof WhatsAppInteractiveButtonType)[keyof typeof WhatsAppInteractiveButtonType];

/**
 * Values of WhatsAppInteractiveHeaderType known at this SDK version. The wire value is an open
 * string: a value added by a newer server deserializes unchanged, so switch on
 * these with a `default` branch rather than treating the set as closed.
 */
export const WhatsAppInteractiveHeaderType = {
  Document: "document",
  Image: "image",
  Text: "text",
  Video: "video",
} as const;

/** A known WhatsAppInteractiveHeaderType value. */
export type WhatsAppInteractiveHeaderTypeValue = (typeof WhatsAppInteractiveHeaderType)[keyof typeof WhatsAppInteractiveHeaderType];

/**
 * Values of WhatsAppInteractiveReplyType known at this SDK version. The wire value is an open
 * string: a value added by a newer server deserializes unchanged, so switch on
 * these with a `default` branch rather than treating the set as closed.
 */
export const WhatsAppInteractiveReplyType = {
  Button: "button",
  List: "list",
} as const;

/** A known WhatsAppInteractiveReplyType value. */
export type WhatsAppInteractiveReplyTypeValue = (typeof WhatsAppInteractiveReplyType)[keyof typeof WhatsAppInteractiveReplyType];

/**
 * Values of WhatsAppInteractiveType known at this SDK version. The wire value is an open
 * string: a value added by a newer server deserializes unchanged, so switch on
 * these with a `default` branch rather than treating the set as closed.
 */
export const WhatsAppInteractiveType = {
  Button: "button",
  Carousel: "carousel",
  CtaUrl: "cta_url",
  List: "list",
  LocationRequestMessage: "location_request_message",
  RequestContactInfo: "request_contact_info",
} as const;

/** A known WhatsAppInteractiveType value. */
export type WhatsAppInteractiveTypeValue = (typeof WhatsAppInteractiveType)[keyof typeof WhatsAppInteractiveType];

/**
 * Values of WhatsAppNumberErrorCode known at this SDK version. The wire value is an open
 * string: a value added by a newer server deserializes unchanged, so switch on
 * these with a `default` branch rather than treating the set as closed.
 */
export const WhatsAppNumberErrorCode = {
  BusinessAccountLocked: "business_account_locked",
  CreditCurrencyMismatch: "credit_currency_mismatch",
  InternalError: "internal_error",
  InvalidRequest: "invalid_request",
  NumberAlreadyInUse: "number_already_in_use",
  NumberAlreadyLinked: "number_already_linked",
  NumberNotRegistered: "number_not_registered",
  NumberVerificationRequired: "number_verification_required",
  PermissionDenied: "permission_denied",
  RegistrationAttemptsExhausted: "registration_attempts_exhausted",
  RegistrationPinRateLimited: "registration_pin_rate_limited",
  RegistrationPinRejected: "registration_pin_rejected",
  VerificationCodeNotReceived: "verification_code_not_received",
  VerificationRateLimited: "verification_rate_limited",
} as const;

/** A known WhatsAppNumberErrorCode value. */
export type WhatsAppNumberErrorCodeValue = (typeof WhatsAppNumberErrorCode)[keyof typeof WhatsAppNumberErrorCode];

/**
 * Values of WhatsAppNumberMessagingLimit known at this SDK version. The wire value is an open
 * string: a value added by a newer server deserializes unchanged, so switch on
 * these with a `default` branch rather than treating the set as closed.
 */
export const WhatsAppNumberMessagingLimit = {
  Tier100k: "tier_100k",
  Tier10k: "tier_10k",
  Tier1k: "tier_1k",
  Tier250: "tier_250",
  Tier50: "tier_50",
  TierUnlimited: "tier_unlimited",
} as const;

/** A known WhatsAppNumberMessagingLimit value. */
export type WhatsAppNumberMessagingLimitValue = (typeof WhatsAppNumberMessagingLimit)[keyof typeof WhatsAppNumberMessagingLimit];

/**
 * Values of WhatsAppNumberQualityRating known at this SDK version. The wire value is an open
 * string: a value added by a newer server deserializes unchanged, so switch on
 * these with a `default` branch rather than treating the set as closed.
 */
export const WhatsAppNumberQualityRating = {
  Green: "green",
  Red: "red",
  Unknown: "unknown",
  Yellow: "yellow",
} as const;

/** A known WhatsAppNumberQualityRating value. */
export type WhatsAppNumberQualityRatingValue = (typeof WhatsAppNumberQualityRating)[keyof typeof WhatsAppNumberQualityRating];

/**
 * Values of WhatsAppNumberStatus known at this SDK version. The wire value is an open
 * string: a value added by a newer server deserializes unchanged, so switch on
 * these with a `default` branch rather than treating the set as closed.
 */
export const WhatsAppNumberStatus = {
  AwaitingSignup: "awaiting_signup",
  Banned: "banned",
  Connected: "connected",
  Deleted: "deleted",
  Disconnected: "disconnected",
  Failed: "failed",
  Flagged: "flagged",
  Migrated: "migrated",
  Pending: "pending",
  Preparing: "preparing",
  RateLimited: "rate_limited",
  Restricted: "restricted",
} as const;

/** A known WhatsAppNumberStatus value. */
export type WhatsAppNumberStatusValue = (typeof WhatsAppNumberStatus)[keyof typeof WhatsAppNumberStatus];

/**
 * Values of WhatsAppNumberThroughputLevel known at this SDK version. The wire value is an open
 * string: a value added by a newer server deserializes unchanged, so switch on
 * these with a `default` branch rather than treating the set as closed.
 */
export const WhatsAppNumberThroughputLevel = {
  Standard: "standard",
} as const;

/** A known WhatsAppNumberThroughputLevel value. */
export type WhatsAppNumberThroughputLevelValue = (typeof WhatsAppNumberThroughputLevel)[keyof typeof WhatsAppNumberThroughputLevel];

/**
 * Values of WhatsAppTemplateCategory known at this SDK version. The wire value is an open
 * string: a value added by a newer server deserializes unchanged, so switch on
 * these with a `default` branch rather than treating the set as closed.
 */
export const WhatsAppTemplateCategory = {
  Authentication: "authentication",
  Marketing: "marketing",
  Utility: "utility",
} as const;

/** A known WhatsAppTemplateCategory value. */
export type WhatsAppTemplateCategoryValue = (typeof WhatsAppTemplateCategory)[keyof typeof WhatsAppTemplateCategory];

/**
 * Values of WhatsAppTemplateLanguageStatus known at this SDK version. The wire value is an open
 * string: a value added by a newer server deserializes unchanged, so switch on
 * these with a `default` branch rather than treating the set as closed.
 */
export const WhatsAppTemplateLanguageStatus = {
  Approved: "approved",
  Archived: "archived",
  Deleted: "deleted",
  Disabled: "disabled",
  InAppeal: "in_appeal",
  LimitExceeded: "limit_exceeded",
  OutcomeUnknown: "outcome_unknown",
  Paused: "paused",
  Pending: "pending",
  PendingDeletion: "pending_deletion",
  Rejected: "rejected",
  SubmitFailed: "submit_failed",
} as const;

/** A known WhatsAppTemplateLanguageStatus value. */
export type WhatsAppTemplateLanguageStatusValue = (typeof WhatsAppTemplateLanguageStatus)[keyof typeof WhatsAppTemplateLanguageStatus];

/**
 * Values of WhatsAppTemplateParameterType known at this SDK version. The wire value is an open
 * string: a value added by a newer server deserializes unchanged, so switch on
 * these with a `default` branch rather than treating the set as closed.
 */
export const WhatsAppTemplateParameterType = {
  Document: "document",
  Gif: "gif",
  Image: "image",
  Location: "location",
  Text: "text",
  Video: "video",
} as const;

/** A known WhatsAppTemplateParameterType value. */
export type WhatsAppTemplateParameterTypeValue = (typeof WhatsAppTemplateParameterType)[keyof typeof WhatsAppTemplateParameterType];

/**
 * Values of WhatsAppTemplateQualityScore known at this SDK version. The wire value is an open
 * string: a value added by a newer server deserializes unchanged, so switch on
 * these with a `default` branch rather than treating the set as closed.
 */
export const WhatsAppTemplateQualityScore = {
  Green: "green",
  Red: "red",
  Unknown: "unknown",
  Yellow: "yellow",
} as const;

/** A known WhatsAppTemplateQualityScore value. */
export type WhatsAppTemplateQualityScoreValue = (typeof WhatsAppTemplateQualityScore)[keyof typeof WhatsAppTemplateQualityScore];

/**
 * Values of WhatsAppTemplateRejectionCategory known at this SDK version. The wire value is an open
 * string: a value added by a newer server deserializes unchanged, so switch on
 * these with a `default` branch rather than treating the set as closed.
 */
export const WhatsAppTemplateRejectionCategory = {
  AbusiveContent: "abusive_content",
  IncorrectCategory: "incorrect_category",
  InvalidFormat: "invalid_format",
  Scam: "scam",
  TagContentMismatch: "tag_content_mismatch",
} as const;

/** A known WhatsAppTemplateRejectionCategory value. */
export type WhatsAppTemplateRejectionCategoryValue = (typeof WhatsAppTemplateRejectionCategory)[keyof typeof WhatsAppTemplateRejectionCategory];

/**
 * Values of WhatsAppUsernameStatus known at this SDK version. The wire value is an open
 * string: a value added by a newer server deserializes unchanged, so switch on
 * these with a `default` branch rather than treating the set as closed.
 */
export const WhatsAppUsernameStatus = {
  Approved: "approved",
  Deleted: "deleted",
  Reserved: "reserved",
} as const;

/** A known WhatsAppUsernameStatus value. */
export type WhatsAppUsernameStatusValue = (typeof WhatsAppUsernameStatus)[keyof typeof WhatsAppUsernameStatus];
