// Code generated by surface-gen; DO NOT EDIT.
// Every catalogued sdk method must exist on the client; a missing or renamed
// method makes a Pick reference a non-existent key and fails `tsc --noEmit`.
// Generated from backend/openapi/surfaces.ir.json.
import type { BirdClient } from "./client.js";

export type _Email = Pick<BirdClient["email"], "send" | "sendBatch" | "get" | "list" | "cancel">;
export type _EmailStats = Pick<BirdClient["email"]["stats"], "summary" | "daily" | "hourly" | "byTag" | "byCategory" | "bySendingIp" | "bySendingDomain" | "byRecipientDomain" | "byMailboxProvider" | "byMailboxProviderRegion" | "byTemplate" | "byLocation" | "byClient" | "byBounceCode" | "byComplaintType" | "byBroadcast">;
export type _Sms = Pick<BirdClient["sms"], "send" | "sendBatch" | "get" | "list" | "listEvents">;
export type _SmsTemplates = Pick<BirdClient["smsTemplates"], "list" | "get">;
export type _SmsStats = Pick<BirdClient["sms"]["stats"], "summary" | "daily" | "hourly" | "byCountry" | "byCarrier" | "byCategory" | "byOriginator" | "byStatus" | "byErrorCode" | "byTag">;
export type _SmsStatsInbound = Pick<BirdClient["sms"]["stats"]["inbound"], "summary" | "daily" | "hourly" | "byCountry" | "byOperator" | "byNumber">;
export type _SmsSuppressions = Pick<BirdClient["smsSuppressions"], "list" | "get" | "add" | "remove">;
export type _SmsKeywordRules = Pick<BirdClient["smsKeywordRules"], "list" | "get" | "create" | "update" | "delete">;
export type _Whatsapp = Pick<BirdClient["whatsapp"], "send" | "get" | "list" | "listEvents">;
export type _Voice = Pick<BirdClient["voice"], "list" | "get">;
export type _VerifyVerifications = Pick<BirdClient["verify"]["verifications"], "create" | "check" | "nextChannel">;
export type _Lookup = Pick<BirdClient["lookup"], "phoneNumber" | "email">;
export type _Numbers = Pick<BirdClient["numbers"], "list" | "get" | "release">;
export type _NumbersAvailable = Pick<BirdClient["numbers"]["available"], "list" | "get">;
export type _NumbersOrders = Pick<BirdClient["numbers"]["orders"], "create" | "list" | "get">;
export type _Domains = Pick<BirdClient["domains"], "list" | "get" | "create" | "verify" | "update" | "delete">;
export type _Webhooks = Pick<BirdClient["webhooks"], "list" | "get" | "create" | "test" | "delete" | "attempts" | "rotateSecret" | "update" | "unwrap">;
export type _Workspace = Pick<BirdClient["workspace"], "get">;
export type _Preferences = Pick<BirdClient["preferences"], "list" | "get" | "create" | "delete">;
export type _Contacts = Pick<BirdClient["contacts"], "list" | "get" | "create" | "update" | "delete" | "batch">;
export type _ContactsPreferences = Pick<BirdClient["contacts"]["preferences"], "list">;
export type _ContactProperties = Pick<BirdClient["contactProperties"], "list" | "get" | "create" | "update" | "archive" | "unarchive">;
export type _Audiences = Pick<BirdClient["audiences"], "list" | "get" | "create" | "update" | "delete" | "listContacts" | "addContacts" | "removeContacts" | "removeContact">;
export type _EmailMailboxes = Pick<BirdClient["email"]["mailboxes"], "list" | "create" | "get" | "update" | "delete" | "restore" | "resume" | "stats" | "labels">;
export type _EmailMailboxesMessages = Pick<BirdClient["email"]["mailboxes"]["messages"], "create">;
export type _EmailMailboxesReceiveRules = Pick<BirdClient["email"]["mailboxes"]["receiveRules"], "list" | "create" | "delete">;
export type _EmailThreads = Pick<BirdClient["email"]["threads"], "list" | "get" | "update" | "delete">;
export type _EmailThreadsMessages = Pick<BirdClient["email"]["threads"]["messages"], "list" | "get" | "body" | "reply" | "attachments">;
export type _Realtime = Pick<BirdClient["realtime"], "publish" | "publishBatch">;
export type _RealtimeChannels = Pick<BirdClient["realtime"]["channels"], "list" | "get" | "members">;
export type _RealtimeMembers = Pick<BirdClient["realtime"]["members"], "send" | "disconnect">;
