// Code generated by surface-gen; DO NOT EDIT.
import { createAmbMessage, getAmbMessage, listAmbMessageEvents, listAmbMessages } from "../generated/sdk.gen.js";
import type { AmbMessage, AmbMessageEventList, CreateAmbMessageData, GetAmbMessageData, ListAmbMessageEventsData, ListAmbMessagesData } from "../generated/types.gen.js";
import { Resource } from "./base.js";
import type { APIPromise, PaginatedPromise, RequestOptions } from "../core/result.js";

export type { AmbMessageEventList };
export type { AmbMessage };
export type AmbListEventsQuery = NonNullable<ListAmbMessageEventsData["query"]>;
export type AmbListQuery = NonNullable<ListAmbMessagesData["query"]>;
export type AmbSendParams = NonNullable<CreateAmbMessageData["body"]>;

export class AmbResourceBase extends Resource {
  /**
   * Reads the processing events for a message in your workspace. Use the events to inspect rejections and gateway failures before deciding whether to submit another message.
   *
   * @example 
   * const result = await bird.amb.listEvents("amb_01krdgeqcxet5s7t44vh8rt9mg");
   * console.log(result);
   */
  listEvents(messageId: string, query?: AmbListEventsQuery, options?: RequestOptions): APIPromise<AmbMessageEventList> {
    return this.call<AmbMessageEventList>("GET", options, ({ signal, headers }) =>
      listAmbMessageEvents({ client: this.client, path: { message_id: messageId }, query, headers, signal }));
  }

  /**
   * Reads a message in your workspace, including its native content and processing state. Sent records Apple gateway acceptance; a send failure does not rule out an earlier attempt reaching Apple.
   *
   * @example 
   * const result = await bird.amb.get("amb_01krdgeqcxet5s7t44vh8rt9mg");
   * console.log(result);
   */
  get(messageId: string, options?: RequestOptions): APIPromise<AmbMessage> {
    return this.call<AmbMessage>("GET", options, ({ signal, headers }) =>
      getAmbMessage({ client: this.client, path: { message_id: messageId }, headers, signal }));
  }

  /**
   * Lists your workspace's incoming and outgoing Apple messages with cursor pagination. Filter by business or conversation to inspect one exchange; sent records Apple gateway acceptance.
   *
   * @example 
   * const result = await bird.amb.list({
   *   business_account_id: "abz_01krdgeqcxet5s7t44vh8rt9mg",
   *   limit: 2,
   * });
   * console.log(result);
   */
  list(query?: AmbListQuery, options?: RequestOptions): PaginatedPromise<AmbMessage> {
    return this.paginated<AmbMessage>("GET", options, ({ signal, headers }, cursor) =>
      listAmbMessages({ client: this.client, query: { ...query, starting_after: cursor ?? query?.starting_after, ending_before: cursor === undefined ? query?.ending_before : undefined }, headers, signal }));
  }

  /**
   * Queues a billable reply to an open customer conversation. Requires a configured business, regardless of onboarding status. Apple decides whether to accept the message. Use the business's apple_business_id as from and the conversation's recipient.opaque_user_id as to. Sent records Apple gateway acceptance; device delivery and read receipts are unavailable.
   *
   * @example 
   * const result = await bird.amb.send({
   *   from: "b52d6267-2b62-4f8a-8842-0533d0f1dc07",
   *   to: "opaque-customer",
   *   content: { type: "text", body: "Your order is ready." },
   * });
   * console.log(result);
   */
  send(params: AmbSendParams, options?: RequestOptions): APIPromise<AmbMessage> {
    return this.call<AmbMessage>("POST", options, ({ signal, headers }) =>
      createAmbMessage({ client: this.client, body: params, headers, signal }));
  }
}
