// Code generated by surface-gen; DO NOT EDIT.
import { createAmbBusinessAccount, deleteAmbBusinessAccount, getAmbBusinessAccount, listAmbBusinessAccounts, restoreAmbBusinessAccount, updateAmbBusinessAccount } from "../generated/sdk.gen.js";
import type { AmbBusinessAccount, CreateAmbBusinessAccountData, DeleteAmbBusinessAccountData, GetAmbBusinessAccountData, ListAmbBusinessAccountsData, RestoreAmbBusinessAccountData, UpdateAmbBusinessAccountData } from "../generated/types.gen.js";
import { Resource } from "./base.js";
import type { APIPromise, PaginatedPromise, RequestOptions } from "../core/result.js";

export type { AmbBusinessAccount };
export type AmbBusinessAccountsUpdateParams = NonNullable<UpdateAmbBusinessAccountData["body"]>;
export type AmbBusinessAccountsListQuery = NonNullable<ListAmbBusinessAccountsData["query"]>;
export type AmbBusinessAccountsCreateParams = NonNullable<CreateAmbBusinessAccountData["body"]>;

export class AmbBusinessAccountsResourceBase extends Resource {
  /**
   * Stops new and queued sends while retaining the account, Apple UUID, approval, credentials and history. Repeated disconnects succeed without changing history. An already-started send attempt may finish; provider requests cannot be recalled. This is a local Bird connection change, not Apple deregistration.
   *
   * @example 
   * await bird.amb.businessAccounts.delete("abz_01krdgeqcxet5s7t44vh8rt9mg");
   */
  delete(businessAccountId: string, options?: RequestOptions): APIPromise<void> {
    return this.call<void>("DELETE", options, ({ signal, headers }) =>
      deleteAmbBusinessAccount({ client: this.client, path: { business_account_id: businessAccountId }, headers, signal }));
  }

  /**
   * Restores the local connection. The retained approval and suspension state still determines whether the account can send. Repeated reconnects return the current account.
   *
   * @example 
   * const result = await bird.amb.businessAccounts.reconnect(
   *   "abz_01krdgeqcxet5s7t44vh8rt9mg",
   * );
   * console.log(result);
   */
  reconnect(businessAccountId: string, options?: RequestOptions): APIPromise<AmbBusinessAccount> {
    return this.call<AmbBusinessAccount>("POST", options, ({ signal, headers }) =>
      restoreAmbBusinessAccount({ client: this.client, path: { business_account_id: businessAccountId }, headers, signal }));
  }

  /**
   * Reads a business record in your workspace. Its apple_business_id supplies the from field for sends; creating a draft does not establish Apple approval.
   *
   * @example 
   * const result = await bird.amb.businessAccounts.get(
   *   "abz_01krdgeqcxet5s7t44vh8rt9mg",
   * );
   * console.log(result);
   */
  get(businessAccountId: string, options?: RequestOptions): APIPromise<AmbBusinessAccount> {
    return this.call<AmbBusinessAccount>("GET", options, ({ signal, headers }) =>
      getAmbBusinessAccount({ client: this.client, path: { business_account_id: businessAccountId }, headers, signal }));
  }

  /**
   * Updates a business in your workspace, leaving omitted fields unchanged. Changing Apple's business UUID does not submit the record or change its approval state.
   *
   * @example 
   * const result = await bird.amb.businessAccounts.update(
   *   "abz_01krdgeqcxet5s7t44vh8rt9mg",
   *   { name: "Acme Support" },
   * );
   * console.log(result);
   */
  update(businessAccountId: string, params: AmbBusinessAccountsUpdateParams = {}, options?: RequestOptions): APIPromise<AmbBusinessAccount> {
    return this.call<AmbBusinessAccount>("PATCH", options, ({ signal, headers }) =>
      updateAmbBusinessAccount({ client: this.client, path: { business_account_id: businessAccountId }, body: params, headers, signal }));
  }

  /**
   * Lists the Apple businesses registered in your workspace, with cursor pagination. Requires business-management read permission. Use the configured apple_business_id when sending; onboarding status does not gate messaging.
   *
   * @example 
   * const result = await bird.amb.businessAccounts.list({ limit: 2 });
   * console.log(result);
   */
  list(query?: AmbBusinessAccountsListQuery, options?: RequestOptions): PaginatedPromise<AmbBusinessAccount> {
    return this.paginated<AmbBusinessAccount>("GET", options, ({ signal, headers }, cursor) =>
      listAmbBusinessAccounts({ client: this.client, query: { ...query, starting_after: cursor ?? query?.starting_after, ending_before: cursor === undefined ? query?.ending_before : undefined }, headers, signal }));
  }

  /**
   * Creates a draft business in your workspace. Supplying Apple's business UUID does not submit the record; upload evidence and create a submission when ready for review.
   *
   * @example 
   * const result = await bird.amb.businessAccounts.create({
   *   name: "Acme Retail",
   *   apple_business_id: "b52d6267-2b62-4f8a-8842-0533d0f1dc07",
   * });
   * console.log(result);
   */
  create(params: AmbBusinessAccountsCreateParams, options?: RequestOptions): APIPromise<AmbBusinessAccount> {
    return this.call<AmbBusinessAccount>("POST", options, ({ signal, headers }) =>
      createAmbBusinessAccount({ client: this.client, body: params, headers, signal }));
  }
}
