// Code generated by surface-gen; DO NOT EDIT.
import { createAmbBusinessAccountSubmission, listAmbBusinessAccountSubmissions } from "../generated/sdk.gen.js";
import type { AmbBusinessAccountSubmission, CreateAmbBusinessAccountSubmissionData, ListAmbBusinessAccountSubmissionsData } from "../generated/types.gen.js";
import { Resource } from "./base.js";
import type { APIPromise, PaginatedPromise, RequestOptions } from "../core/result.js";

export type { AmbBusinessAccountSubmission };
export type AmbBusinessAccountsSubmissionsListQuery = NonNullable<ListAmbBusinessAccountSubmissionsData["query"]>;
export type AmbBusinessAccountsSubmissionsCreateParams = NonNullable<CreateAmbBusinessAccountSubmissionData["body"]>;

export class AmbBusinessAccountsSubmissionsResource extends Resource {
  /**
   * Lists the review attempts for a business in your workspace. Each attempt retains the business identity and evidence selected at submission.
   *
   * @example 
   * const result = await bird.amb.businessAccounts.submissions.list(
   *   "abz_01krdgeqcxet5s7t44vh8rt9mg",
   *   { limit: 2 },
   * );
   * console.log(result);
   */
  list(businessAccountId: string, query?: AmbBusinessAccountsSubmissionsListQuery, options?: RequestOptions): PaginatedPromise<AmbBusinessAccountSubmission> {
    return this.paginated<AmbBusinessAccountSubmission>("GET", options, ({ signal, headers }, cursor) =>
      listAmbBusinessAccountSubmissions({ client: this.client, path: { business_account_id: businessAccountId }, query: { ...query, starting_after: cursor ?? query?.starting_after, ending_before: cursor === undefined ? query?.ending_before : undefined }, headers, signal }));
  }

  /**
   * Submits an account for review, making its name, Apple UUID and three uploaded evidence attachments available to Bird staff. This does not approve the account.
   *
   * @example 
   * const result = await bird.amb.businessAccounts.submissions.create(
   *   "abz_01krdgeqcxet5s7t44vh8rt9mg",
   *   {
   *     readiness_attachment_id: "tca_01krdgeqcxet5s7t44vh8rt9mg",
   *     use_cases_attachment_id: "tca_01krdgeqcxet5s7t44vh8rt9mh",
   *     video_attachment_id: "tca_01krdgeqcxet5s7t44vh8rt9mj",
   *   },
   * );
   * console.log(result);
   */
  create(businessAccountId: string, params: AmbBusinessAccountsSubmissionsCreateParams, options?: RequestOptions): APIPromise<AmbBusinessAccountSubmission> {
    return this.call<AmbBusinessAccountSubmission>("POST", options, ({ signal, headers }) =>
      createAmbBusinessAccountSubmission({ client: this.client, path: { business_account_id: businessAccountId }, body: params, headers, signal }));
  }
}
