// Code generated by surface-gen; DO NOT EDIT.
import { createAmbConversationTyping, getAmbConversation, listAmbConversationMessages, listAmbConversations, updateAmbConversation } from "../generated/sdk.gen.js";
import type { AmbConversation, AmbMessage, CreateAmbConversationTypingData, GetAmbConversationData, ListAmbConversationMessagesData, ListAmbConversationsData, UpdateAmbConversationData } from "../generated/types.gen.js";
import { Resource } from "./base.js";
import type { APIPromise, PaginatedPromise, RequestOptions } from "../core/result.js";

export type { AmbConversation };
export type { AmbMessage };
export type AmbConversationsUpdateParams = NonNullable<UpdateAmbConversationData["body"]>;
export type AmbConversationsListMessagesQuery = NonNullable<ListAmbConversationMessagesData["query"]>;
export type AmbConversationsTypingParams = NonNullable<CreateAmbConversationTypingData["body"]>;
export type AmbConversationsListQuery = NonNullable<ListAmbConversationsData["query"]>;

export class AmbConversationsResource extends Resource {
  /**
   * Reads a customer-initiated conversation in your workspace. Its opaque_user_id supplies the to field for replies; verify the business and open state before sending.
   *
   * @example 
   * const result = await bird.amb.conversations.get(
   *   "acv_01krdgeqcxet5s7t44vh8rt9mg",
   * );
   * console.log(result);
   */
  get(conversationId: string, options?: RequestOptions): APIPromise<AmbConversation> {
    return this.call<AmbConversation>("GET", options, ({ signal, headers }) =>
      getAmbConversation({ client: this.client, path: { conversation_id: conversationId }, headers, signal }));
  }

  /**
   * Updates assignment, labels and read state on a workspace conversation. Omitted fields stay unchanged; null assigned_to unassigns, empty labels clears labels, and read false has no effect. This operation does not close or reopen a conversation.
   *
   * @example 
   * const result = await bird.amb.conversations.update(
   *   "acv_01krdgeqcxet5s7t44vh8rt9mg",
   *   { assigned_to: null, labels: [], read: false },
   * );
   * console.log(result);
   */
  update(conversationId: string, params: AmbConversationsUpdateParams = {}, options?: RequestOptions): APIPromise<AmbConversation> {
    return this.call<AmbConversation>("PATCH", options, ({ signal, headers }) =>
      updateAmbConversation({ client: this.client, path: { conversation_id: conversationId }, body: params, headers, signal }));
  }

  /**
   * Returns the messages in a conversation, newest first, both received and sent. To page through older messages, use `starting_after`. The sort order is fixed, so to render the messages in conversation order, reverse the page yourself.
   *
   * @example 
   * const result = await bird.amb.conversations.listMessages(
   *   "acv_01krdgeqcxet5s7t44vh8rt9mg",
   *   { limit: 2 },
   * );
   * console.log(result);
   */
  listMessages(conversationId: string, query?: AmbConversationsListMessagesQuery, options?: RequestOptions): PaginatedPromise<AmbMessage> {
    return this.paginated<AmbMessage>("GET", options, ({ signal, headers }, cursor) =>
      listAmbConversationMessages({ client: this.client, path: { conversation_id: conversationId }, query: { ...query, starting_after: cursor ?? query?.starting_after, ending_before: cursor === undefined ? query?.ending_before : undefined }, headers, signal }));
  }

  /**
   * Sends a typing signal through Apple for an existing conversation. Typing is best effort; typing_end still needs native device verification. It does not enqueue a billable message.
   *
   * @example 
   * const result = await bird.amb.conversations.typing(
   *   "acv_01krdgeqcxet5s7t44vh8rt9mg",
   *   { event: "typing_start" },
   * );
   * console.log(result);
   */
  typing(conversationId: string, params: AmbConversationsTypingParams, options?: RequestOptions): APIPromise<void> {
    return this.call<void>("POST", options, ({ signal, headers }) =>
      createAmbConversationTyping({ client: this.client, path: { conversation_id: conversationId }, body: params, headers, signal }));
  }

  /**
   * Returns the conversations your business has with customers on Apple Messages for Business, newest first by last message. To page through older conversations, use `starting_after`. A closed conversation stays in this list; filter on `status` to separate them from open ones.
   *
   * @example 
   * const result = await bird.amb.conversations.list({
   *   business_account_id: "abz_01krdgeqcxet5s7t44vh8rt9mg",
   *   limit: 2,
   * });
   * console.log(result);
   */
  list(query?: AmbConversationsListQuery, options?: RequestOptions): PaginatedPromise<AmbConversation> {
    return this.paginated<AmbConversation>("GET", options, ({ signal, headers }, cursor) =>
      listAmbConversations({ client: this.client, query: { ...query, starting_after: cursor ?? query?.starting_after, ending_before: cursor === undefined ? query?.ending_before : undefined }, headers, signal }));
  }
}
