// Code generated by surface-gen; DO NOT EDIT.
import { createAmbRoutingRule, deleteAmbRoutingRule, getAmbRoutingRule, listAmbRoutingRules, updateAmbRoutingRule } from "../generated/sdk.gen.js";
import type { AmbRoutingRule, AmbRoutingRuleList, CreateAmbRoutingRuleData, DeleteAmbRoutingRuleData, GetAmbRoutingRuleData, ListAmbRoutingRulesData, UpdateAmbRoutingRuleData } from "../generated/types.gen.js";
import { Resource } from "./base.js";
import type { APIPromise, RequestOptions } from "../core/result.js";

export type { AmbRoutingRule };
export type { AmbRoutingRuleList };
export type AmbRoutingRulesUpdateParams = NonNullable<UpdateAmbRoutingRuleData["body"]>;
export type AmbRoutingRulesListQuery = NonNullable<ListAmbRoutingRulesData["query"]>;
export type AmbRoutingRulesCreateParams = NonNullable<CreateAmbRoutingRuleData["body"]>;

export class AmbRoutingRulesResource extends Resource {
  /**
   * Returns one routing rule by ID.
   *
   * @example 
   * const result = await bird.amb.routingRules.get(
   *   "arr_01krdgeqcxet5s7t44vh8rt9mg",
   * );
   * console.log(result);
   */
  get(routingRuleId: string, options?: RequestOptions): APIPromise<AmbRoutingRule> {
    return this.call<AmbRoutingRule>("GET", options, ({ signal, headers }) =>
      getAmbRoutingRule({ client: this.client, path: { routing_rule_id: routingRuleId }, headers, signal }));
  }

  /**
   * Changes a routing rule's business, match, queue, precedence, or default status. The match changes as a unit: send `match_kind` with the intent and group ids it requires, as on create. Returns a `409` when the update would leave this rule as the default of a business that already has a different default rule.
   *
   * @example 
   * const result = await bird.amb.routingRules.update(
   *   "arr_01krdgeqcxet5s7t44vh8rt9mg",
   *   { queue: "sales", precedence: 0, is_default: false },
   * );
   * console.log(result);
   */
  update(routingRuleId: string, params: AmbRoutingRulesUpdateParams = {}, options?: RequestOptions): APIPromise<AmbRoutingRule> {
    return this.call<AmbRoutingRule>("PATCH", options, ({ signal, headers }) =>
      updateAmbRoutingRule({ client: this.client, path: { routing_rule_id: routingRuleId }, body: params, headers, signal }));
  }

  /**
   * Deletes a routing rule. A conversation already routed by it keeps its queue; only newly created or reopened conversations stop matching it. Deleting a business's default rule leaves it with none, so unmatched conversations route to an empty queue until you create another.
   *
   * @example 
   * const result = await bird.amb.routingRules.delete(
   *   "arr_01krdgeqcxet5s7t44vh8rt9mg",
   * );
   * console.log(result);
   */
  delete(routingRuleId: string, options?: RequestOptions): APIPromise<void> {
    return this.call<void>("DELETE", options, ({ signal, headers }) =>
      deleteAmbRoutingRule({ client: this.client, path: { routing_rule_id: routingRuleId }, headers, signal }));
  }

  /**
   * Returns the workspace's Apple Messages for Business routing rules, highest precedence first. Rules run when a conversation is created, when a closed conversation reopens, and when a customer writes to a resolved conversation, matching its group and intent to a queue. A message without a group or intent routes on the conversation's stored values. Later messages while the conversation is open in the inbox retain its queue.
   *
   * @example 
   * const result = await bird.amb.routingRules.list({
   *   business_account_id: "abz_01krdgeqcxet5s7t44vh8rt9mg",
   * });
   * console.log(result);
   */
  list(query?: AmbRoutingRulesListQuery, options?: RequestOptions): APIPromise<AmbRoutingRuleList> {
    return this.call<AmbRoutingRuleList>("GET", options, ({ signal, headers }) =>
      listAmbRoutingRules({ client: this.client, query, headers, signal }));
  }

  /**
   * Creates a routing rule for one of your Apple Messages for Business brands. Set `is_default` to make it the rule that catches a conversation matching nothing else. A business can have only one default rule, and creating a second while one exists returns a `409`.
   *
   * @example 
   * const result = await bird.amb.routingRules.create({
   *   business_account_id: "abz_01krdgeqcxet5s7t44vh8rt9mg",
   *   match_kind: "intent",
   *   match_intent_id: "support",
   *   queue: "support",
   *   precedence: 0,
   *   is_default: false,
   *   match_group_id: null,
   * });
   * console.log(result);
   */
  create(params: AmbRoutingRulesCreateParams, options?: RequestOptions): APIPromise<AmbRoutingRule> {
    return this.call<AmbRoutingRule>("POST", options, ({ signal, headers }) =>
      createAmbRoutingRule({ client: this.client, body: params, headers, signal }));
  }
}
