// Code generated by surface-gen; DO NOT EDIT.
import { getAmbStatsByBusiness, getAmbStatsByCategory, getAmbStatsByErrorCode, getAmbStatsByGroup, getAmbStatsByIntent, getAmbStatsByMessageKind, getAmbStatsByTag, getAmbStatsDaily, getAmbStatsHourly, getAmbStatsSummary } from "../generated/sdk.gen.js";
import type { AmbStatsByBusinessResponse, AmbStatsByCategoryResponse, AmbStatsByErrorCodeResponse, AmbStatsByGroupResponse, AmbStatsByIntentResponse, AmbStatsByMessageKindResponse, AmbStatsByTagResponse, AmbStatsResponse, AmbStatsSummary, GetAmbStatsByBusinessData, GetAmbStatsByCategoryData, GetAmbStatsByErrorCodeData, GetAmbStatsByGroupData, GetAmbStatsByIntentData, GetAmbStatsByMessageKindData, GetAmbStatsByTagData, GetAmbStatsDailyData, GetAmbStatsHourlyData, GetAmbStatsSummaryData } from "../generated/types.gen.js";
import { Resource } from "./base.js";
import type { APIPromise, RequestOptions } from "../core/result.js";

export type { AmbStatsByBusinessResponse };
export type { AmbStatsByCategoryResponse };
export type { AmbStatsResponse };
export type { AmbStatsByErrorCodeResponse };
export type { AmbStatsByGroupResponse };
export type { AmbStatsByIntentResponse };
export type { AmbStatsByMessageKindResponse };
export type { AmbStatsSummary };
export type { AmbStatsByTagResponse };
export type AmbStatsByBusinessQuery = NonNullable<GetAmbStatsByBusinessData["query"]>;
export type AmbStatsByCategoryQuery = NonNullable<GetAmbStatsByCategoryData["query"]>;
export type AmbStatsDailyQuery = NonNullable<GetAmbStatsDailyData["query"]>;
export type AmbStatsByErrorCodeQuery = NonNullable<GetAmbStatsByErrorCodeData["query"]>;
export type AmbStatsByGroupQuery = NonNullable<GetAmbStatsByGroupData["query"]>;
export type AmbStatsHourlyQuery = NonNullable<GetAmbStatsHourlyData["query"]>;
export type AmbStatsByIntentQuery = NonNullable<GetAmbStatsByIntentData["query"]>;
export type AmbStatsByMessageKindQuery = NonNullable<GetAmbStatsByMessageKindData["query"]>;
export type AmbStatsSummaryQuery = NonNullable<GetAmbStatsSummaryData["query"]>;
export type AmbStatsByTagQuery = NonNullable<GetAmbStatsByTagData["query"]>;

export class AmbStatsResourceBase extends Resource {
  /**
   * Returns outbound counts and latency percentiles grouped by business, for the requested period. Rows are ranked by accepted volume descending and capped at the requested `limit` (default 50, max 200). Rows use accepted-time attribution: a send failure recorded during the period for a message accepted earlier counts against the earlier period. Each row also carries `first_response` latency percentiles, omitted when no qualifying message contributes a measurement.
   *
   * @example 
   * const result = await bird.amb.stats.byBusiness({ limit: 2 });
   * console.log(result);
   */
  byBusiness(query?: AmbStatsByBusinessQuery, options?: RequestOptions): APIPromise<AmbStatsByBusinessResponse> {
    return this.call<AmbStatsByBusinessResponse>("GET", options, ({ signal, headers }) =>
      getAmbStatsByBusiness({ client: this.client, query, headers, signal }));
  }

  /**
   * Returns outbound counts and latency percentiles grouped by message category, for the requested period. Rows are ranked by accepted volume descending and capped at the requested `limit` (default 50, max 200). A send that names no category is grouped under an empty-string category. Rows use accepted-time attribution: a send failure recorded during the period for a message accepted earlier counts against the earlier period. Each row also carries `first_response` latency percentiles, omitted when no qualifying message contributes a measurement.
   *
   * @example 
   * const result = await bird.amb.stats.byCategory({ limit: 2 });
   * console.log(result);
   */
  byCategory(query?: AmbStatsByCategoryQuery, options?: RequestOptions): APIPromise<AmbStatsByCategoryResponse> {
    return this.call<AmbStatsByCategoryResponse>("GET", options, ({ signal, headers }) =>
      getAmbStatsByCategory({ client: this.client, query, headers, signal }));
  }

  /**
   * Returns one row of outbound Apple Messages for Business counts and processing-latency percentiles per calendar day for the workspace, gap-filled so a silent day is a zero row rather than a missing one. Every count in a row is attributed to the day its message was accepted, regardless of when a later event, such as a send failure, arrived.
   *
   * @example 
   * const result = await bird.amb.stats.daily({
   *   business_account_id: "abz_01krdgeqcxet5s7t44vh8rt9mg",
   * });
   * console.log(result);
   */
  daily(query?: AmbStatsDailyQuery, options?: RequestOptions): APIPromise<AmbStatsResponse> {
    return this.call<AmbStatsResponse>("GET", options, ({ signal, headers }) =>
      getAmbStatsDaily({ client: this.client, query, headers, signal }));
  }

  /**
   * Returns outbound counts and latency percentiles grouped by failure reason, for the requested period. Rows are ranked by `send_failed + rejected` descending and capped at the requested `limit` (default 50, max 200). Only messages carrying a failure reason appear: a `bird:` code is usually a rejection (never charged, never attempted), an `apple:` code a send failure; use the summary for the period's full accepted total.
   *
   * @example 
   * const result = await bird.amb.stats.byErrorCode({ limit: 2 });
   * console.log(result);
   */
  byErrorCode(query?: AmbStatsByErrorCodeQuery, options?: RequestOptions): APIPromise<AmbStatsByErrorCodeResponse> {
    return this.call<AmbStatsByErrorCodeResponse>("GET", options, ({ signal, headers }) =>
      getAmbStatsByErrorCode({ client: this.client, query, headers, signal }));
  }

  /**
   * Returns outbound counts and latency percentiles grouped by entry-point group, for the requested period. Rows are ranked by accepted volume descending and capped at the requested `limit` (default 50, max 200). Groups are workspace-defined strings configured on the business's entry points and have no fixed vocabulary. Rows use accepted-time attribution: a send failure recorded during the period for a message accepted earlier counts against the earlier period.
   *
   * @example 
   * const result = await bird.amb.stats.byGroup({ limit: 2 });
   * console.log(result);
   */
  byGroup(query?: AmbStatsByGroupQuery, options?: RequestOptions): APIPromise<AmbStatsByGroupResponse> {
    return this.call<AmbStatsByGroupResponse>("GET", options, ({ signal, headers }) =>
      getAmbStatsByGroup({ client: this.client, query, headers, signal }));
  }

  /**
   * Returns one row of outbound Apple Messages for Business counts and processing-latency percentiles per hour, gap-filled so a silent hour is a zero row rather than a missing one. Every count in a row is attributed to the hour its message was accepted, regardless of when a later event, such as a send failure, arrived. Use it where the daily grain hides the shape; a window spans at most 720 hours (30 days), and for anything longer use `amb.stats.daily`.
   *
   * @example 
   * const result = await bird.amb.stats.hourly({
   *   business_account_id: "abz_01krdgeqcxet5s7t44vh8rt9mg",
   * });
   * console.log(result);
   */
  hourly(query?: AmbStatsHourlyQuery, options?: RequestOptions): APIPromise<AmbStatsResponse> {
    return this.call<AmbStatsResponse>("GET", options, ({ signal, headers }) =>
      getAmbStatsHourly({ client: this.client, query, headers, signal }));
  }

  /**
   * Returns outbound counts and latency percentiles grouped by entry-point intent, for the requested period. Rows are ranked by accepted volume descending and capped at the requested `limit` (default 50, max 200). Intents are workspace-defined strings configured on the business's entry points and have no fixed vocabulary. Rows use accepted-time attribution: a send failure recorded during the period for a message accepted earlier counts against the earlier period.
   *
   * @example 
   * const result = await bird.amb.stats.byIntent({ limit: 2 });
   * console.log(result);
   */
  byIntent(query?: AmbStatsByIntentQuery, options?: RequestOptions): APIPromise<AmbStatsByIntentResponse> {
    return this.call<AmbStatsByIntentResponse>("GET", options, ({ signal, headers }) =>
      getAmbStatsByIntent({ client: this.client, query, headers, signal }));
  }

  /**
   * Returns outbound counts and latency percentiles grouped by message content kind, for the requested period. Rows are ranked by accepted volume descending and capped at the requested `limit` (default 50, max 200). Rows use accepted-time attribution: a send failure recorded during the period for a message accepted earlier counts against the earlier period. Each row also carries `first_response` latency percentiles, omitted when no qualifying message contributes a measurement.
   *
   * @example 
   * const result = await bird.amb.stats.byMessageKind({ limit: 2 });
   * console.log(result);
   */
  byMessageKind(query?: AmbStatsByMessageKindQuery, options?: RequestOptions): APIPromise<AmbStatsByMessageKindResponse> {
    return this.call<AmbStatsByMessageKindResponse>("GET", options, ({ signal, headers }) =>
      getAmbStatsByMessageKind({ client: this.client, query, headers, signal }));
  }

  /**
   * Returns one aggregate row of outbound Apple Messages for Business counts and latency percentiles (`p50`, `p95`, and `p99`) for the requested period. Counts are attributed to the time each message was accepted, so a send failure recorded today counts against the day its message was accepted; `period.data_as_of` is the freshness boundary the rollups have reached.
   *
   * @example 
   * const result = await bird.amb.stats.summary({
   *   business_account_id: "abz_01krdgeqcxet5s7t44vh8rt9mg",
   * });
   * console.log(result);
   */
  summary(query?: AmbStatsSummaryQuery, options?: RequestOptions): APIPromise<AmbStatsSummary> {
    return this.call<AmbStatsSummary>("GET", options, ({ signal, headers }) =>
      getAmbStatsSummary({ client: this.client, query, headers, signal }));
  }

  /**
   * Returns outbound counts and latency percentiles grouped by tag (`name` or `name:value`), for the requested period. Rows are ranked by accepted volume descending and capped at the requested `limit` (default 50, max 200). Only tagged messages appear, and one carrying several tags counts once under each, so rows do not sum to the period total. Rows use accepted-time attribution: a send failure recorded during the period for a message accepted earlier counts against the earlier period.
   *
   * @example 
   * const result = await bird.amb.stats.byTag({ limit: 2 });
   * console.log(result);
   */
  byTag(query?: AmbStatsByTagQuery, options?: RequestOptions): APIPromise<AmbStatsByTagResponse> {
    return this.call<AmbStatsByTagResponse>("GET", options, ({ signal, headers }) =>
      getAmbStatsByTag({ client: this.client, query, headers, signal }));
  }
}
