// Code generated by surface-gen; DO NOT EDIT.
import { getAmbInboundStatsByBusiness, getAmbInboundStatsByIntent, getAmbInboundStatsDaily, getAmbInboundStatsHourly, getAmbInboundStatsSummary } from "../generated/sdk.gen.js";
import type { AmbInboundStatsByBusinessResponse, AmbInboundStatsByIntentResponse, AmbInboundStatsResponse, AmbInboundStatsSummary, GetAmbInboundStatsByBusinessData, GetAmbInboundStatsByIntentData, GetAmbInboundStatsDailyData, GetAmbInboundStatsHourlyData, GetAmbInboundStatsSummaryData } from "../generated/types.gen.js";
import { Resource } from "./base.js";
import type { APIPromise, RequestOptions } from "../core/result.js";

export type { AmbInboundStatsByBusinessResponse };
export type { AmbInboundStatsResponse };
export type { AmbInboundStatsByIntentResponse };
export type { AmbInboundStatsSummary };
export type AmbStatsInboundByBusinessQuery = NonNullable<GetAmbInboundStatsByBusinessData["query"]>;
export type AmbStatsInboundDailyQuery = NonNullable<GetAmbInboundStatsDailyData["query"]>;
export type AmbStatsInboundHourlyQuery = NonNullable<GetAmbInboundStatsHourlyData["query"]>;
export type AmbStatsInboundByIntentQuery = NonNullable<GetAmbInboundStatsByIntentData["query"]>;
export type AmbStatsInboundSummaryQuery = NonNullable<GetAmbInboundStatsSummaryData["query"]>;

export class AmbStatsInboundResource extends Resource {
  /**
   * Returns inbound received counts grouped by business, for the requested period. Rows are ranked by received volume descending and capped at the requested `limit` (default 50, max 200). Rows are attributed to when the inbound event occurred, not to any earlier outbound message. This channel has no delivery receipt and no derived rate, so each row carries only the raw `received` count. The maximum window is 365 days; a longer range returns `422`. Historical dates are supported within the maximum window length; the requested dates are not shifted forward.
   *
   * @example 
   * const result = await bird.amb.stats.inbound.byBusiness({ limit: 2 });
   * console.log(result);
   */
  byBusiness(query?: AmbStatsInboundByBusinessQuery, options?: RequestOptions): APIPromise<AmbInboundStatsByBusinessResponse> {
    return this.call<AmbInboundStatsByBusinessResponse>("GET", options, ({ signal, headers }) =>
      getAmbInboundStatsByBusiness({ client: this.client, query, headers, signal }));
  }

  /**
   * Returns one row of inbound Apple Messages for Business counts per calendar day for the workspace, gap-filled so a silent day is a zero row rather than a missing one. Every row is attributed to the day the inbound event occurred, not to any earlier outbound message.
   *
   * @example 
   * const result = await bird.amb.stats.inbound.daily();
   * console.log(result);
   */
  daily(query?: AmbStatsInboundDailyQuery, options?: RequestOptions): APIPromise<AmbInboundStatsResponse> {
    return this.call<AmbInboundStatsResponse>("GET", options, ({ signal, headers }) =>
      getAmbInboundStatsDaily({ client: this.client, query, headers, signal }));
  }

  /**
   * Returns one row of inbound Apple Messages for Business counts per hour, gap-filled so a silent hour is a zero row rather than a missing one. Every row is attributed to the hour the inbound event occurred, not to any earlier outbound message. Use it where the daily grain hides the shape; a window spans at most 720 hours (30 days), and for anything longer use `amb.stats.inbound.daily`.
   *
   * @example 
   * const result = await bird.amb.stats.inbound.hourly();
   * console.log(result);
   */
  hourly(query?: AmbStatsInboundHourlyQuery, options?: RequestOptions): APIPromise<AmbInboundStatsResponse> {
    return this.call<AmbInboundStatsResponse>("GET", options, ({ signal, headers }) =>
      getAmbInboundStatsHourly({ client: this.client, query, headers, signal }));
  }

  /**
   * Returns inbound received counts grouped by entry-point intent, for the requested period. Rows are ranked by received volume descending and capped at the requested `limit` (default 50, max 200). Intents are workspace-defined strings configured on the business's entry points and have no fixed vocabulary. Rows are attributed to when the inbound event occurred, not to any earlier outbound message. This channel has no delivery receipt and no derived rate, so each row carries only the raw `received` count.
   *
   * @example 
   * const result = await bird.amb.stats.inbound.byIntent({ limit: 2 });
   * console.log(result);
   */
  byIntent(query?: AmbStatsInboundByIntentQuery, options?: RequestOptions): APIPromise<AmbInboundStatsByIntentResponse> {
    return this.call<AmbInboundStatsByIntentResponse>("GET", options, ({ signal, headers }) =>
      getAmbInboundStatsByIntent({ client: this.client, query, headers, signal }));
  }

  /**
   * Returns one aggregate row of inbound Apple Messages for Business counts for the requested period. Inbound statistics are attributed to when the event occurred, not to any earlier outbound message, so a reply received today counts against today regardless of when the conversation started. `period.data_as_of` is the freshness boundary the rollups have reached.
   *
   * @example 
   * const result = await bird.amb.stats.inbound.summary();
   * console.log(result);
   */
  summary(query?: AmbStatsInboundSummaryQuery, options?: RequestOptions): APIPromise<AmbInboundStatsSummary> {
    return this.call<AmbInboundStatsSummary>("GET", options, ({ signal, headers }) =>
      getAmbInboundStatsSummary({ client: this.client, query, headers, signal }));
  }
}
