// Code generated by surface-gen; DO NOT EDIT.
import { assignAudienceContacts, createAudience, deleteAudience, getAudience, listAudienceContacts, listAudiences, unassignAudienceContact, unassignAudienceContacts, updateAudience } from "../generated/sdk.gen.js";
import type { AssignAudienceContactsData, Audience, AudienceMember, CreateAudienceData, DeleteAudienceData, GetAudienceData, ListAudienceContactsData, ListAudiencesData, UnassignAudienceContactData, UnassignAudienceContactsData, UpdateAudienceData } from "../generated/types.gen.js";
import { Resource } from "./base.js";
import type { APIPromise, PaginatedPromise, RequestOptions } from "../core/result.js";

export type { Audience };
export type { AudienceMember };
export type AudienceListQuery = NonNullable<ListAudiencesData["query"]>;
export type AudienceCreateParams = NonNullable<CreateAudienceData["body"]>;
export type AudienceUpdateParams = NonNullable<UpdateAudienceData["body"]>;
export type AudienceListContactsQuery = NonNullable<ListAudienceContactsData["query"]>;
export type AudienceAddContactsParams = NonNullable<AssignAudienceContactsData["body"]>;
export type AudienceRemoveContactsParams = NonNullable<UnassignAudienceContactsData["body"]>;

export class AudiencesResource extends Resource {
  /**
   * List the workspace's audiences as a cursor page, newest first. Filter by name substring with `q`.
   *
   * @example Iterate every audience, or take one page
   * for await (const audience of bird.audiences.list()) {
   *   console.log(audience.id, audience.name);
   * }
   */
  list(query?: AudienceListQuery, options?: RequestOptions): PaginatedPromise<Audience> {
    return this.paginated<Audience>("GET", options, ({ signal, headers }, cursor) =>
      listAudiences({ client: this.client, query: { ...query, starting_after: cursor ?? query?.starting_after }, headers, signal }));
  }

  /**
   * Get a single audience by ID: name, description, and type. Members are listed separately with `audiences.list_contacts`.
   *
   * @example Fetch an audience by id
   * const audience = await bird.audiences.get("adn_01krdgeqcxet5s7t44vh8rt9mg");
   * console.log(audience.name);
   */
  get(audienceId: string, options?: RequestOptions): APIPromise<Audience> {
    return this.call<Audience>("GET", options, ({ signal, headers }) =>
      getAudience({ client: this.client, path: { audience_id: audienceId }, headers, signal }));
  }

  /**
   * Create an audience in the workspace. New audiences start empty; add contacts with `audiences.add_contacts` or `contacts.batch`. Only static audiences can be created today.
   *
   * @example Create an audience
   * const audience = await bird.audiences.create({ name: "Newsletter subscribers" });
   * console.log(audience.id); // "adn_…"
   */
  create(params: AudienceCreateParams, options?: RequestOptions): APIPromise<Audience> {
    return this.call<Audience>("POST", options, ({ signal, headers }) =>
      createAudience({ client: this.client, body: params, headers, signal }));
  }

  /**
   * Update an audience's name or description. Omitted fields are unchanged; a `null` description clears it.
   *
   * @example Rename an audience
   * await bird.audiences.update("adn_01krdgeqcxet5s7t44vh8rt9mg", { name: "Renamed" });
   */
  update(audienceId: string, params: AudienceUpdateParams = {}, options?: RequestOptions): APIPromise<Audience> {
    return this.call<Audience>("PATCH", options, ({ signal, headers }) =>
      updateAudience({ client: this.client, path: { audience_id: audienceId }, body: params, headers, signal }));
  }

  /**
   * Delete an audience and its memberships; contacts themselves are not deleted. Fails while a broadcast targeting the audience is scheduled, accepted, sending, or canceling.
   *
   * @example Delete an audience by id
   * await bird.audiences.delete("adn_01krdgeqcxet5s7t44vh8rt9mg");
   */
  delete(audienceId: string, options?: RequestOptions): APIPromise<void> {
    return this.call<void>("DELETE", options, ({ signal, headers }) =>
      deleteAudience({ client: this.client, path: { audience_id: audienceId }, headers, signal }));
  }

  /**
   * List the contacts in a static audience by ID, as a cursor page ordered by when each contact joined (most recent first). Each entry pairs the contact with its join time.
   *
   * @example Iterate an audience's members
   * for await (const member of bird.audiences.listContacts("adn_01krdgeqcxet5s7t44vh8rt9mg")) {
   *   console.log(member.contact.id, member.joined_at);
   * }
   */
  listContacts(audienceId: string, query?: AudienceListContactsQuery, options?: RequestOptions): PaginatedPromise<AudienceMember> {
    return this.paginated<AudienceMember>("GET", options, ({ signal, headers }, cursor) =>
      listAudienceContacts({ client: this.client, path: { audience_id: audienceId }, query: { ...query, starting_after: cursor ?? query?.starting_after }, headers, signal }));
  }

  /**
   * Add up to 1,000 existing contacts to a static audience by ID. Fails entirely if any contact ID does not exist. To add contacts you have not created yet, use `contacts.batch` with `audience_ids` instead: it matches or creates each contact by email address and assigns it to the audience in one call.
   *
   * @example Add contacts to an audience
   * await bird.audiences.addContacts("adn_01krdgeqcxet5s7t44vh8rt9mg", {
   *   contact_ids: ["con_01krdgeqcxet5s7t44vh8rt9mg"],
   * });
   */
  addContacts(audienceId: string, params: AudienceAddContactsParams, options?: RequestOptions): APIPromise<void> {
    return this.call<void>("POST", options, ({ signal, headers }) =>
      assignAudienceContacts({ client: this.client, path: { audience_id: audienceId }, body: params, headers, signal }));
  }

  /**
   * Remove up to 1,000 contacts from a static audience by ID. Fails entirely if any contact ID does not exist; contacts are not deleted.
   *
   * @example Remove contacts from an audience
   * await bird.audiences.removeContacts("adn_01krdgeqcxet5s7t44vh8rt9mg", {
   *   contact_ids: ["con_01krdgeqcxet5s7t44vh8rt9mg"],
   * });
   */
  removeContacts(audienceId: string, params: AudienceRemoveContactsParams, options?: RequestOptions): APIPromise<void> {
    return this.call<void>("POST", options, ({ signal, headers }) =>
      unassignAudienceContacts({ client: this.client, path: { audience_id: audienceId }, body: params, headers, signal }));
  }

  /**
   * Remove one contact's membership from an audience. The contact itself is not deleted and stays a member of any other audiences.
   *
   * @example Remove one contact's membership
   * await bird.audiences.removeContact(
   *   "adn_01krdgeqcxet5s7t44vh8rt9mg",
   *   "con_01krdgeqcxet5s7t44vh8rt9mg",
   * );
   */
  removeContact(audienceId: string, contactId: string, options?: RequestOptions): APIPromise<void> {
    return this.call<void>("DELETE", options, ({ signal, headers }) =>
      unassignAudienceContact({ client: this.client, path: { audience_id: audienceId, contact_id: contactId }, headers, signal }));
  }
}
