// Code generated by surface-gen; DO NOT EDIT.
import { archiveContactProperty, createContactProperty, getContactProperty, listContactProperties, unarchiveContactProperty, updateContactProperty } from "../generated/sdk.gen.js";
import type { ArchiveContactPropertyData, ContactProperty, CreateContactPropertyData, GetContactPropertyData, ListContactPropertiesData, UnarchiveContactPropertyData, UpdateContactPropertyData } from "../generated/types.gen.js";
import { Resource } from "./base.js";
import type { APIPromise, PaginatedPromise, RequestOptions } from "../core/result.js";

export type { ContactProperty };
export type ContactPropertyListQuery = NonNullable<ListContactPropertiesData["query"]>;
export type ContactPropertyCreateParams = NonNullable<CreateContactPropertyData["body"]>;
export type ContactPropertyUpdateParams = NonNullable<UpdateContactPropertyData["body"]>;

export class ContactPropertiesResource extends Resource {
  /**
   * List the workspace's contact properties as a cursor page, newest first. Archived properties are included, marked by their archived flag.
   *
   * @example Iterate every contact property, or take one page
   * for await (const prop of bird.contactProperties.list()) {
   *   console.log(prop.key, prop.type);
   * }
   * const page = await bird.contactProperties.list({ limit: 50 }); // page.data, page.next_cursor
   */
  list(query?: ContactPropertyListQuery, options?: RequestOptions): PaginatedPromise<ContactProperty> {
    return this.paginated<ContactProperty>("GET", options, ({ signal, headers }, cursor) =>
      listContactProperties({ client: this.client, query: { ...query, starting_after: cursor ?? query?.starting_after, ending_before: cursor === undefined ? query?.ending_before : undefined }, headers, signal }));
  }

  /**
   * Get a single contact property by ID: key, type, fallback value, and archived state.
   *
   * @example Fetch a contact property by id
   * const prop = await bird.contactProperties.get("cp_01krdgeqcxet5s7t44vh8rt9mg");
   * console.log(prop.key, prop.type);
   */
  get(propertyId: string, options?: RequestOptions): APIPromise<ContactProperty> {
    return this.call<ContactProperty>("GET", options, ({ signal, headers }) =>
      getContactProperty({ client: this.client, path: { property_id: propertyId }, headers, signal }));
  }

  /**
   * Define a custom contact property (key + value type) that becomes available in contact data and as a broadcast template variable. The key and type cannot change after creation; a workspace holds at most 200 properties, archived included.
   *
   * @example Define a custom property
   * const prop = await bird.contactProperties.create({ key: "plan", type: "string" });
   * console.log(prop.id); // "cp_…"
   */
  create(params: ContactPropertyCreateParams, options?: RequestOptions): APIPromise<ContactProperty> {
    return this.call<ContactProperty>("POST", options, ({ signal, headers }) =>
      createContactProperty({ client: this.client, body: params, headers, signal }));
  }

  /**
   * Update a contact property's fallback value. Only the fallback value can change; the key and type are fixed at creation, so a different key or type needs a new property.
   *
   * @example Change a property's fallback value
   * await bird.contactProperties.update("cp_01krdgeqcxet5s7t44vh8rt9mg", { fallback_value: "free" });
   */
  update(propertyId: string, params: ContactPropertyUpdateParams = {}, options?: RequestOptions): APIPromise<ContactProperty> {
    return this.call<ContactProperty>("PATCH", options, ({ signal, headers }) =>
      updateContactProperty({ client: this.client, path: { property_id: propertyId }, body: params, headers, signal }));
  }

  /**
   * Archive a contact property: the key is rejected in new contact writes and can no longer be used in a template version you publish, while stored values remain readable and versions published before the archive keep sending. Succeeds whatever else reads the key; only an already-archived property is refused. The key stays reserved and counts toward the 200-property limit; reverse with `contact_properties.unarchive`.
   *
   * @example Archive a property, retiring the field without deleting its data
   * const prop = await bird.contactProperties.archive("cp_01krdgeqcxet5s7t44vh8rt9mg");
   * console.log(prop.key, prop.archived);
   */
  archive(propertyId: string, options?: RequestOptions): APIPromise<ContactProperty> {
    return this.call<ContactProperty>("POST", options, ({ signal, headers }) =>
      archiveContactProperty({ client: this.client, path: { property_id: propertyId }, headers, signal }));
  }

  /**
   * Reactivate an archived contact property so its key is accepted in contact writes and new template versions. Stored values are unchanged. Fails with a conflict if the property is not archived.
   *
   * @example Restore an archived property
   * await bird.contactProperties.unarchive("cp_01krdgeqcxet5s7t44vh8rt9mg");
   */
  unarchive(propertyId: string, options?: RequestOptions): APIPromise<ContactProperty> {
    return this.call<ContactProperty>("POST", options, ({ signal, headers }) =>
      unarchiveContactProperty({ client: this.client, path: { property_id: propertyId }, headers, signal }));
  }
}
