// Code generated by surface-gen; DO NOT EDIT.
import { createContact, createContactBatch, deleteContact, getContact, listContacts, updateContact } from "../generated/sdk.gen.js";
import type { Contact, ContactUpsertResult, CreateContactBatchData, CreateContactData, DeleteContactData, GetContactData, ListContactsData, UpdateContactData } from "../generated/types.gen.js";
import { Resource } from "./base.js";
import type { APIPromise, PaginatedPromise, RequestOptions } from "../core/result.js";

export type { Contact };
export type { ContactUpsertResult };
export type ContactListQuery = NonNullable<ListContactsData["query"]>;
export type ContactCreateParams = NonNullable<CreateContactData["body"]>;
export type ContactUpdateParams = NonNullable<UpdateContactData["body"]>;
export type ContactBatchParams = NonNullable<CreateContactBatchData["body"]>;

export class ContactsResourceBase extends Resource {
  /**
   * List the workspace's contacts as a cursor page, newest first. Look one up by exact email, phone_number, or external_id, repeating phone_number to resolve up to 50 numbers in one call (raise limit to match), or search by email, name, or phone substring. Pass include_total for a total count.
   *
   * @example Iterate every contact, or take one page
   * for await (const contact of bird.contacts.list({ q: "acme.com" })) {
   *   console.log(contact.id, contact.email);
   * }
   * const page = await bird.contacts.list({ limit: 50 }); // page.data, page.next_cursor
   */
  list(query?: ContactListQuery, options?: RequestOptions): PaginatedPromise<Contact> {
    return this.paginated<Contact>("GET", options, ({ signal, headers }, cursor) =>
      listContacts({ client: this.client, query: { ...query, starting_after: cursor ?? query?.starting_after }, headers, signal }));
  }

  /**
   * Get a single contact by ID. Look up an ID by exact email, phone_number, or external_id with `contacts.list`.
   *
   * @example Fetch a contact by id
   * const contact = await bird.contacts.get("con_01krdgeqcxet5s7t44vh8rt9mg");
   * console.log(contact.email, contact.first_name);
   */
  get(contactId: string, options?: RequestOptions): APIPromise<Contact> {
    return this.call<Contact>("GET", options, ({ signal, headers }) =>
      getContact({ client: this.client, path: { contact_id: contactId }, headers, signal }));
  }

  /**
   * Create a contact identified by an email address, an E.164 phone number, or both. Fails with a conflict if the email, phone_number, or external_id is already used by another contact. For bulk import or create-or-update semantics use `contacts.batch`.
   *
   * @example Create a contact
   * const contact = await bird.contacts.create({
   *   email: "jane@acme.com",
   *   first_name: "Jane",
   * });
   * console.log(contact.id); // "con_…"
   */
  create(params: ContactCreateParams = {}, options?: RequestOptions): APIPromise<Contact> {
    return this.call<Contact>("POST", options, ({ signal, headers }) =>
      createContact({ client: this.client, body: params, headers, signal }));
  }

  /**
   * Update a contact's name, `external_id`, email, `phone_number`, or custom data. Only supplied fields change; custom data keys are merged, with `null` removing a key. A contact keeps at least one identifier: clearing both email and `phone_number` is rejected.
   *
   * @example Change a contact's fields
   * const contact = await bird.contacts.update("con_01krdgeqcxet5s7t44vh8rt9mg", {
   *   first_name: "Jane",
   * });
   * console.log(contact.first_name);
   */
  update(contactId: string, params: ContactUpdateParams = {}, options?: RequestOptions): APIPromise<Contact> {
    return this.call<Contact>("PATCH", options, ({ signal, headers }) =>
      updateContact({ client: this.client, path: { contact_id: contactId }, body: params, headers, signal }));
  }

  /**
   * Delete a contact and remove it from every audience it belongs to. Suppression records for the address are unaffected.
   *
   * @example Delete a contact by id
   * await bird.contacts.delete("con_01krdgeqcxet5s7t44vh8rt9mg");
   */
  delete(contactId: string, options?: RequestOptions): APIPromise<void> {
    return this.call<void>("DELETE", options, ({ signal, headers }) =>
      deleteContact({ client: this.client, path: { contact_id: contactId }, headers, signal }));
  }

  /**
   * Create or update up to 1,000 contacts in one request. Match each entry against every supplied identifier (`email`, `phone_number`, and `external_id`), or set `match_on` to use one identifier. Optionally add all successful contacts to up to 10 audiences. Results follow submission order.
   *
   * @example Create or update many contacts at once, matched by the identifiers each entry carries
   * const result = await bird.contacts.batch({
   *   contacts: [{ email: "jane@acme.com", first_name: "Jane" }],
   * });
   * for (const item of result.data) {
   *   console.log(item.entry.email, item.status);
   * }
   */
  batch(params: ContactBatchParams, options?: RequestOptions): APIPromise<ContactUpsertResult> {
    return this.call<ContactUpsertResult>("POST", options, ({ signal, headers }) =>
      createContactBatch({ client: this.client, body: params, headers, signal }));
  }
}
