// Code generated by surface-gen; DO NOT EDIT.
import { listContactPreferences } from "../generated/sdk.gen.js";
import type { ListContactPreferencesData, Preference } from "../generated/types.gen.js";
import { Resource } from "./base.js";
import type { APIPromise, PaginatedPromise, RequestOptions } from "../core/result.js";

export type { Preference };
export type ContactsPreferencesListQuery = NonNullable<ListContactPreferencesData["query"]>;

export class ContactsPreferencesResource extends Resource {
  /**
   * List the recorded messaging preferences for a contact's own handles (their email address and phone number) across every channel, as a cursor page.
   *
   * @example List a contact's own preferences
   * for await (const preference of bird.contacts.preferences.list(
   *   "con_01krdgeqcxet5s7t44vh8rt9mg",
   * )) {
   *   console.log(preference.channel, preference.status);
   * }
   */
  list(contactId: string, query?: ContactsPreferencesListQuery, options?: RequestOptions): PaginatedPromise<Preference> {
    return this.paginated<Preference>("GET", options, ({ signal, headers }, cursor) =>
      listContactPreferences({ client: this.client, path: { contact_id: contactId }, query: { ...query, starting_after: cursor ?? query?.starting_after }, headers, signal }));
  }
}
