// Code generated by surface-gen; DO NOT EDIT.
import { createDomain, deleteDomain, getDomain, listDomains, updateDomain, verifyDomain } from "../generated/sdk.gen.js";
import type { CreateDomainData, DeleteDomainData, Domain, GetDomainData, ListDomainsData, UpdateDomainData, VerifyDomainData } from "../generated/types.gen.js";
import { Resource } from "./base.js";
import type { APIPromise, PaginatedPromise, RequestOptions } from "../core/result.js";

export type { Domain };
export type DomainListQuery = NonNullable<ListDomainsData["query"]>;
export type DomainCreateParams = NonNullable<CreateDomainData["body"]>;
export type DomainUpdateParams = NonNullable<UpdateDomainData["body"]>;

export class DomainsResource extends Resource {
  /**
   * List the workspace's sending domains with their verification status, as a cursor page.
   *
   * @example Iterate every sending domain
   * for await (const domain of bird.domains.list()) {
   *   console.log(domain.id, domain.status);
   * }
   */
  list(query?: DomainListQuery, options?: RequestOptions): PaginatedPromise<Domain> {
    return this.paginated<Domain>("GET", options, ({ signal, headers }, cursor) =>
      listDomains({ client: this.client, query: { ...query, starting_after: cursor ?? query?.starting_after }, headers, signal }));
  }

  /**
   * Fetch one sending domain: verification status and the DNS records with their individual verification states.
   *
   * @example Fetch a sending domain by id
   * const domain = await bird.domains.get("dom_01krdgeqcxet5s7t44vh8rt9mg");
   * console.log(domain.domain);
   */
  get(domainId: string, options?: RequestOptions): APIPromise<Domain> {
    return this.call<Domain>("GET", options, ({ signal, headers }) =>
      getDomain({ client: this.client, path: { domain_id: domainId }, headers, signal }));
  }

  /**
   * Register a new sending domain and get the DNS records to publish. Verification is a second step: the records go live at the DNS provider, then email_domains_verify confirms them. Propagation takes minutes to hours, so the first verify often still reports unverified and a later one succeeds.
   *
   * @example Register a sending domain
   * const domain = await bird.domains.create({ domain: "mail.acme.com" });
   * console.log(domain.id, domain.status); // "dom_…", "pending"
   */
  create(params: DomainCreateParams, options?: RequestOptions): APIPromise<Domain> {
    return this.call<Domain>("POST", options, ({ signal, headers }) =>
      createDomain({ client: this.client, body: params, headers, signal }));
  }

  /**
   * Trigger a DNS verification check for a sending domain and return the refreshed domain with per-record results. Safe to repeat while waiting for DNS propagation.
   *
   * @example Re-run the DNS verification check
   * const domain = await bird.domains.verify("dom_01krdgeqcxet5s7t44vh8rt9mg");
   * console.log(domain.status); // "verified" once DNS is in place
   */
  verify(domainId: string, options?: RequestOptions): APIPromise<Domain> {
    return this.call<Domain>("POST", options, ({ signal, headers }) =>
      verifyDomain({ client: this.client, path: { domain_id: domainId }, headers, signal }));
  }

  /**
   * Update a sending domain's tracking and inbound configuration. Tracking: click_tracking and open_tracking apply immediately to new sends, and the tracking domain can be set, changed, or removed (the name part only, and the sending domain is appended for you). Enabling either toggle with no tracking domain configured returns 409, and removing the tracking domain while either toggle is still on also returns 409. Tracking-domain changes on a verified domain are staged behind DNS verification, so the current config keeps serving until the new records verify. Inbound receiving: inbound.enabled starts or stops receiving mail for the domain. Enabling requires the domain's DKIM to be verified first (a fresh enable on an unverified domain returns 422), and a domain already receiving inbound for another organization returns 422. The MX records to publish are always listed in dns_records regardless, so receiving starts only once inbound.enabled is set, even when those records are already published.
   *
   * @example Enable tracking on a domain
   * await bird.domains.update("dom_01krdgeqcxet5s7t44vh8rt9mg", {
   *   settings: { click_tracking: true, open_tracking: true },
   *   tracking: { name: "links" },
   * });
   */
  update(domainId: string, params: DomainUpdateParams = {}, options?: RequestOptions): APIPromise<Domain> {
    return this.call<Domain>("PATCH", options, ({ signal, headers }) =>
      updateDomain({ client: this.client, path: { domain_id: domainId }, body: params, headers, signal }));
  }

  /**
   * Delete a sending domain by id. Revokes its sender authorization: new sends from the domain are rejected afterward, while historical statistics and events for past sends are preserved. Destructive.
   *
   * @example Delete a sending domain by id
   * await bird.domains.delete("dom_01krdgeqcxet5s7t44vh8rt9mg");
   */
  delete(domainId: string, options?: RequestOptions): APIPromise<void> {
    return this.call<void>("DELETE", options, ({ signal, headers }) =>
      deleteDomain({ client: this.client, path: { domain_id: domainId }, headers, signal }));
  }
}
