// Code generated by surface-gen; DO NOT EDIT.
import { getEmailInboxInsightsSeedTestConfiguration } from "../generated/sdk.gen.js";
import type { EmailInboxInsightsSeedTestConfiguration, GetEmailInboxInsightsSeedTestConfigurationData } from "../generated/types.gen.js";
import { Resource } from "./base.js";
import type { APIPromise, RequestOptions } from "../core/result.js";

export type { EmailInboxInsightsSeedTestConfiguration };
export type EmailInboxInsightsSeedTestsConfigurationGetQuery = NonNullable<GetEmailInboxInsightsSeedTestConfigurationData["query"]>;

export class EmailInboxInsightsSeedTestsConfigurationResource extends Resource {
  /**
   * Read available seed pools, regions and engagement profiles for an owned sending
domain before `email.inbox_insights.seed_tests.create`. Use only available pools
and preserve region strings exactly. Scoped API keys, OAuth and service accounts
require organization preview access.
   *
   * @example Read available seed-test options
   * // Requires Insights preview access for the organization.
   * let sendingDomain: string | undefined;
   * for await (const domain of bird.email.inboxInsights.domains.list({ search: "mail.example.com" })) {
   *   if (domain.domain === "mail.example.com") { sendingDomain = domain.domain; break; }
   * }
   * if (!sendingDomain) throw new Error("Verify mail.example.com in this workspace first");
   * const report = await bird.email.inboxInsights.seedTests.configuration.get({ sending_domain: sendingDomain });
   * console.log(report);
   */
  get(query: EmailInboxInsightsSeedTestsConfigurationGetQuery, options?: RequestOptions): APIPromise<EmailInboxInsightsSeedTestConfiguration> {
    return this.call<EmailInboxInsightsSeedTestConfiguration>("GET", options, ({ signal, headers }) =>
      getEmailInboxInsightsSeedTestConfiguration({ client: this.client, query, headers, signal }));
  }
}
