// Code generated by surface-gen; DO NOT EDIT.
import { getEmailCompetitiveVolumeSeries } from "../generated/sdk.gen.js";
import type { EmailCompetitiveVolumeSeries, GetEmailCompetitiveVolumeSeriesData } from "../generated/types.gen.js";
import { Resource } from "./base.js";
import type { APIPromise, RequestOptions } from "../core/result.js";

export type { EmailCompetitiveVolumeSeries };
export type EmailCompetitiveVolumeSeriesQuery = NonNullable<GetEmailCompetitiveVolumeSeriesData["query"]>;

export class EmailCompetitiveResourceBase extends Resource {
  /**
   * Accepts up to 20 distinct watchlist entry IDs from
`email.competitive.watchlist.get`. Omitting brand_ids requests the workspace's
own line. Competitor lines retain the requested order after the workspace
line, when present. Each line's source distinguishes estimated panel volume
from the workspace's accepted sends. Returns daily series without pagination.

API-key calls require Insights preview access for your organization.
   *
   * @example Compare daily volume with a watched brand
   * // Requires Insights preview access for the organization.
   * const watchlist = await bird.email.competitive.watchlist.get({ range: 30 });
   * const entry = watchlist.data.find((row) => row.name === "Everlane" && row.watchlist_brand_id);
   * if (!entry?.watchlist_brand_id) throw new Error("Add Everlane to the watchlist first");
   * const watchlistBrandId = entry.watchlist_brand_id;
   * const report = await bird.email.competitive.volumeSeries({ range: 30, brand_ids: [watchlistBrandId] });
   * console.log(report);
   */
  volumeSeries(query?: EmailCompetitiveVolumeSeriesQuery, options?: RequestOptions): APIPromise<EmailCompetitiveVolumeSeries> {
    return this.call<EmailCompetitiveVolumeSeries>("GET", options, ({ signal, headers }) =>
      getEmailCompetitiveVolumeSeries({ client: this.client, query, headers, signal }));
  }
}
