// Code generated by surface-gen; DO NOT EDIT.
import { getEmailThreadMessage, getEmailThreadMessageBody, listEmailThreadMessageAttachments, listEmailThreadMessages, replyEmailThreadMessage } from "../generated/sdk.gen.js";
import type { EmailThreadMessage, EmailThreadMessageAttachmentList, EmailThreadMessageBody, GetEmailThreadMessageBodyData, GetEmailThreadMessageData, ListEmailThreadMessageAttachmentsData, ListEmailThreadMessagesData, ReplyEmailThreadMessageData } from "../generated/types.gen.js";
import { Resource } from "./base.js";
import type { APIPromise, PaginatedPromise, RequestOptions } from "../core/result.js";

export type { EmailThreadMessage };
export type { EmailThreadMessageBody };
export type { EmailThreadMessageAttachmentList };
export type EmailThreadsMessagesListQuery = NonNullable<ListEmailThreadMessagesData["query"]>;
export type EmailThreadsMessagesReplyParams = NonNullable<ReplyEmailThreadMessageData["body"]>;

export class EmailThreadsMessagesResource extends Resource {
  /**
   * List the messages in a conversation newest first, both directions. Page older messages with `starting_after`, and pass `include=extracted_text` to inline each message's extracted plain text.
   *
   * @example List a thread's messages
   * for await (const msg of bird.email.threads.messages.list("thr_01abc")) {
   *   console.log(msg.id, msg.direction);
   * }
   */
  list(threadId: string, query?: EmailThreadsMessagesListQuery, options?: RequestOptions): PaginatedPromise<EmailThreadMessage> {
    return this.paginated<EmailThreadMessage>("GET", options, ({ signal, headers }, cursor) =>
      listEmailThreadMessages({ client: this.client, path: { thread_id: threadId }, query: { ...query, starting_after: cursor ?? query?.starting_after }, headers, signal }));
  }

  /**
   * Get one conversation message with its extracted plain text, readable for the mailbox's full retention tier without MIME parsing.
   *
   * @example Get a message
   * const msg = await bird.email.threads.messages.get("thr_01abc", "rem_01xyz");
   * console.log(msg.direction); // "inbound"
   */
  get(threadId: string, messageId: string, options?: RequestOptions): APIPromise<EmailThreadMessage> {
    return this.call<EmailThreadMessage>("GET", options, ({ signal, headers }) =>
      getEmailThreadMessage({ client: this.client, path: { thread_id: threadId, message_id: messageId }, headers, signal }));
  }

  /**
   * Get the original rendered HTML and plain-text body of a conversation message. Available for 30 days. After that, use the message's extracted_text.
   *
   * @example Get a message body
   * const body = await bird.email.threads.messages.body("thr_01abc", "rem_01xyz");
   * console.log(body.text);
   */
  body(threadId: string, messageId: string, options?: RequestOptions): APIPromise<EmailThreadMessageBody> {
    return this.call<EmailThreadMessageBody>("GET", options, ({ signal, headers }) =>
      getEmailThreadMessageBody({ client: this.client, path: { thread_id: threadId, message_id: messageId }, headers, signal }));
  }

  /**
   * Reply to a specific conversation message from the mailbox's own address. To reply to a conversation, target its newest received message. Recipients, subject, and threading headers are derived automatically.
   *
   * @example Reply to a message
   * const reply = await bird.email.threads.messages.reply("thr_01abc", "rem_01xyz", {
   *   text: "Thanks for reaching out!",
   * });
   * console.log(reply.id);
   */
  reply(threadId: string, messageId: string, params: EmailThreadsMessagesReplyParams = {}, options?: RequestOptions): APIPromise<EmailThreadMessage> {
    return this.call<EmailThreadMessage>("POST", options, ({ signal, headers }) =>
      replyEmailThreadMessage({ client: this.client, path: { thread_id: threadId, message_id: messageId }, body: params, headers, signal }));
  }

  /**
   * List the attachments on a conversation message. Bytes are downloadable for the mailbox's retention tier, and the metadata stays readable afterward on the message's attachment_manifest.
   *
   * @example List a message's attachments
   * const atts = await bird.email.threads.messages.attachments("thr_01abc", "rem_01xyz");
   * console.log(atts.data.map((a) => a.filename));
   */
  attachments(threadId: string, messageId: string, options?: RequestOptions): APIPromise<EmailThreadMessageAttachmentList> {
    return this.call<EmailThreadMessageAttachmentList>("GET", options, ({ signal, headers }) =>
      listEmailThreadMessageAttachments({ client: this.client, path: { thread_id: threadId, message_id: messageId }, headers, signal }));
  }
}
