// Code generated by surface-gen; DO NOT EDIT.
import { deleteEmailTemplateLanguage, getEmailTemplateLanguage, listEmailTemplateVersionLanguages, updateEmailTemplateLanguage, upsertEmailTemplateLanguage } from "../generated/sdk.gen.js";
import type { DeleteEmailTemplateLanguageData, EmailTemplateLanguage, EmailTemplateLanguageList, EmailTemplateLanguageSaved, GetEmailTemplateLanguageData, ListEmailTemplateVersionLanguagesData, UpdateEmailTemplateLanguageData, UpsertEmailTemplateLanguageData } from "../generated/types.gen.js";
import { Resource } from "./base.js";
import type { APIPromise, RequestOptions } from "../core/result.js";

export type { EmailTemplateLanguageList };
export type { EmailTemplateLanguage };
export type { EmailTemplateLanguageSaved };
export type EmailTemplatesVersionsLanguagesSetParams = NonNullable<UpsertEmailTemplateLanguageData["body"]>;
export type EmailTemplatesVersionsLanguagesUpdateParams = NonNullable<UpdateEmailTemplateLanguageData["body"]>;

export class EmailTemplatesVersionsLanguagesResource extends Resource {
  /**
   * List the languages a template version holds, with each language's revision and fingerprint but not its content.
   */
  list(templateRef: string, versionId: string, options?: RequestOptions): APIPromise<EmailTemplateLanguageList> {
    return this.call<EmailTemplateLanguageList>("GET", options, ({ signal, headers }) =>
      listEmailTemplateVersionLanguages({ client: this.client, path: { template_ref: templateRef, version_id: versionId }, headers, signal }));
  }

  /**
   * Read one language's subject and bodies from a template version. The response carries `compatibility`: what the stored HTML uses that mail clients remove, ignore, or render inconsistently, and `compatibility_severity` reducing it to `problem`, `warning`, or `none`.
   */
  get(templateRef: string, versionId: string, language: string, options?: RequestOptions): APIPromise<EmailTemplateLanguage> {
    return this.call<EmailTemplateLanguage>("GET", options, ({ signal, headers }) =>
      getEmailTemplateLanguage({ client: this.client, path: { template_ref: templateRef, version_id: versionId, language: language }, headers, signal }));
  }

  /**
   * Save one language's full content on a template's draft, creating the language if the draft does not have it yet. The response carries `compatibility`: what the saved HTML uses that mail clients remove, ignore, or render inconsistently, each finding naming the pattern, its line and column, and what to use instead. Advisory: the language is saved either way, and `compatibility_severity` of `problem` means part of the content does nothing at all in the clients the finding names.
   */
  set(templateRef: string, versionId: string, language: string, params: EmailTemplatesVersionsLanguagesSetParams, options?: RequestOptions): APIPromise<EmailTemplateLanguageSaved> {
    return this.call<EmailTemplateLanguageSaved>("PUT", options, ({ signal, headers }) =>
      upsertEmailTemplateLanguage({ client: this.client, path: { template_ref: templateRef, version_id: versionId, language: language }, body: params, headers, signal }));
  }

  /**
   * Change some fields of one language on a template's draft, leaving the rest as they are. The response carries `compatibility` for the language as saved, the same advisory report the full save returns.
   */
  update(templateRef: string, versionId: string, language: string, params: EmailTemplatesVersionsLanguagesUpdateParams = {}, options?: RequestOptions): APIPromise<EmailTemplateLanguageSaved> {
    return this.call<EmailTemplateLanguageSaved>("PATCH", options, ({ signal, headers }) =>
      updateEmailTemplateLanguage({ client: this.client, path: { template_ref: templateRef, version_id: versionId, language: language }, body: params, headers, signal }));
  }

  /**
   * Remove one language from a template's draft. The current default cannot be removed on its own; update the template to point the default at a different language first, then remove the old one.
   */
  delete(templateRef: string, versionId: string, language: string, options?: RequestOptions): APIPromise<void> {
    return this.call<void>("DELETE", options, ({ signal, headers }) =>
      deleteEmailTemplateLanguage({ client: this.client, path: { template_ref: templateRef, version_id: versionId, language: language }, headers, signal }));
  }
}
