// Code generated by surface-gen; DO NOT EDIT.
import { searchEmailCompetitiveBrands } from "../generated/sdk.gen.js";
import type { EmailCompetitiveBrandSearchResults, SearchEmailCompetitiveBrandsData } from "../generated/types.gen.js";
import { Resource } from "./base.js";
import type { APIPromise, RequestOptions } from "../core/result.js";

export type { EmailCompetitiveBrandSearchResults };
export type EmailCompetitiveBrandsSearchQuery = NonNullable<SearchEmailCompetitiveBrandsData["query"]>;

export class EmailCompetitiveBrandsResource extends Resource {
  /**
   * Find a competitor by brand name or sending domain without adding it. For
existing competitors, `email.competitive.watchlist.get` already returns names,
tracked domains and watchlist IDs. Search returns at most eight matches, each
with its highest-volume sending domain, not every domain a brand uses. Resolve
ambiguous names against the intended domain before any authorized addition.
An empty or limited result describes this search, not exhaustive panel coverage.
The returned panel `brand_id` differs from a saved `watchlist_brand_id`.

API-key calls require Insights preview access for your organization.
   *
   * @example Find a competitor brand
   * // Requires Insights preview access for the organization.
   * const report = await bird.email.competitive.brands.search({ q: "Everlane" });
   * console.log(report.data);
   */
  search(query: EmailCompetitiveBrandsSearchQuery, options?: RequestOptions): APIPromise<EmailCompetitiveBrandSearchResults> {
    return this.call<EmailCompetitiveBrandSearchResults>("GET", options, ({ signal, headers }) =>
      searchEmailCompetitiveBrands({ client: this.client, query, headers, signal }));
  }
}
