// Code generated by surface-gen; DO NOT EDIT.
import { listEmailTemplates } from "../generated/sdk.gen.js";
import type { EmailTemplateSummary, ListEmailTemplatesData } from "../generated/types.gen.js";
import { Resource } from "./base.js";
import type { APIPromise, PaginatedPromise, RequestOptions } from "../core/result.js";

export type { EmailTemplateSummary };
export type EmailTemplatesListQuery = NonNullable<ListEmailTemplatesData["query"]>;

export class EmailTemplatesResource extends Resource {
  /**
   * List email templates as a cursor page. The list covers both the workspace's own templates and our built-in `system` templates. Filter to one tier with `scope`, and filter further by category, source, theme, or a search across slug, name, and description. A theme narrows the built-in catalog to one of its five visual themes, so naming one returns built-ins alone.
   *
   * @example Find the templates a send can name
   * for await (const tpl of bird.email.templates.list({ scope: "workspace" })) {
   *   console.log(tpl.slug, tpl.name);
   * }
   */
  list(query?: EmailTemplatesListQuery, options?: RequestOptions): PaginatedPromise<EmailTemplateSummary> {
    return this.paginated<EmailTemplateSummary>("GET", options, ({ signal, headers }, cursor) =>
      listEmailTemplates({ client: this.client, query: { ...query, starting_after: cursor ?? query?.starting_after }, headers, signal }));
  }
}
