// Code generated by surface-gen; DO NOT EDIT.
import { listEmailTemplateBroadcasts } from "../generated/sdk.gen.js";
import type { EmailTemplateBroadcastSummary, ListEmailTemplateBroadcastsData } from "../generated/types.gen.js";
import { Resource } from "./base.js";
import type { APIPromise, PaginatedPromise, RequestOptions } from "../core/result.js";

export type { EmailTemplateBroadcastSummary };
export type EmailTemplatesBroadcastsListQuery = NonNullable<ListEmailTemplateBroadcastsData["query"]>;

export class EmailTemplatesBroadcastsResource extends Resource {
  /**
   * List the broadcasts that block deleting a template, newest first.
   */
  list(templateRef: string, query?: EmailTemplatesBroadcastsListQuery, options?: RequestOptions): PaginatedPromise<EmailTemplateBroadcastSummary> {
    return this.paginated<EmailTemplateBroadcastSummary>("GET", options, ({ signal, headers }, cursor) =>
      listEmailTemplateBroadcasts({ client: this.client, path: { template_ref: templateRef }, query: { ...query, starting_after: cursor ?? query?.starting_after }, headers, signal }));
  }
}
