// Code generated by surface-gen; DO NOT EDIT.
import { getEmailInboxInsightsAuthentication, getEmailInboxInsightsBlocklists, getEmailInboxInsightsComplaints, getEmailInboxInsightsPlacement, getEmailInboxInsightsSpamTraps } from "../generated/sdk.gen.js";
import type { EmailInboxInsightsAuthentication, EmailInboxInsightsBlocklists, EmailInboxInsightsComplaints, EmailInboxInsightsPlacement, EmailInboxInsightsSpamTraps, GetEmailInboxInsightsAuthenticationData, GetEmailInboxInsightsBlocklistsData, GetEmailInboxInsightsComplaintsData, GetEmailInboxInsightsPlacementData, GetEmailInboxInsightsSpamTrapsData } from "../generated/types.gen.js";
import { Resource } from "./base.js";
import type { APIPromise, RequestOptions } from "../core/result.js";

export type { EmailInboxInsightsPlacement };
export type { EmailInboxInsightsAuthentication };
export type { EmailInboxInsightsComplaints };
export type { EmailInboxInsightsSpamTraps };
export type { EmailInboxInsightsBlocklists };
export type EmailInboxInsightsPlacementQuery = NonNullable<GetEmailInboxInsightsPlacementData["query"]>;
export type EmailInboxInsightsAuthenticationQuery = NonNullable<GetEmailInboxInsightsAuthenticationData["query"]>;
export type EmailInboxInsightsComplaintsQuery = NonNullable<GetEmailInboxInsightsComplaintsData["query"]>;
export type EmailInboxInsightsSpamTrapsQuery = NonNullable<GetEmailInboxInsightsSpamTrapsData["query"]>;
export type EmailInboxInsightsBlocklistsQuery = NonNullable<GetEmailInboxInsightsBlocklistsData["query"]>;

export class EmailInboxInsightsResourceBase extends Resource {
  /**
   * Read placement for a verified domain owned by the workspace. Dates are inclusive
UTC days, with at most 30 days between from and to. Rates are percentages, and
section statuses distinguish missing measurements. Deltas require a requested
comparison and comparable prior data; absence does not mean stable placement.
Provider filters add series
lines without filtering the provider table. The response reports domain-wide
panel/seed estimates with audience weighting, not delivery counts or a
marketing/transactional split; a domain name alone does not identify a stream.
Read rate measures reading, not opens. Label freshness from freshness.as_of;
missing days and nulls are not zeros. Associations do not establish a cause.
This read does not enable monitoring. Individual seed-test results and Google
Postmaster connection status are dashboard-only; these aggregates cannot
substitute for a particular test or prove placement for every customer.

API-key calls require Insights preview access for your organization.
   *
   * @example Read placement with per-section statuses
   * // Requires Insights preview access for the organization.
   * let sendingDomain: string | undefined;
   * for await (const domain of bird.email.inboxInsights.domains.list({ search: "mail.example.com" })) {
   *   if (domain.domain === "mail.example.com") { sendingDomain = domain.domain; break; }
   * }
   * if (!sendingDomain) throw new Error("Verify mail.example.com in this workspace first");
   * const report = await bird.email.inboxInsights.placement({ sending_domain: sendingDomain });
   * console.log(report);
   */
  placement(query: EmailInboxInsightsPlacementQuery, options?: RequestOptions): APIPromise<EmailInboxInsightsPlacement> {
    return this.call<EmailInboxInsightsPlacement>("GET", options, ({ signal, headers }) =>
      getEmailInboxInsightsPlacement({ client: this.client, query, headers, signal }));
  }

  /**
   * Read SPF, DKIM and DMARC results for a verified domain owned by the workspace.
Dates are inclusive UTC days, with at most 30 days between from and to.
Pass rates are percentages. A not_configured section does not establish that
DNS records are absent or that authentication failed; the source's coverage
must be checked. Read section statuses, sources.latest_data_date and freshness
before drawing conclusions. Authentication and placement changes can coincide
without establishing cause. This read does not configure authentication or
enable monitoring.

API-key calls require Insights preview access for your organization.
   *
   * @example Read authentication readiness
   * // Requires Insights preview access for the organization.
   * let sendingDomain: string | undefined;
   * for await (const domain of bird.email.inboxInsights.domains.list({ search: "mail.example.com" })) {
   *   if (domain.domain === "mail.example.com") { sendingDomain = domain.domain; break; }
   * }
   * if (!sendingDomain) throw new Error("Verify mail.example.com in this workspace first");
   * const report = await bird.email.inboxInsights.authentication({ sending_domain: sendingDomain });
   * console.log(report);
   */
  authentication(query: EmailInboxInsightsAuthenticationQuery, options?: RequestOptions): APIPromise<EmailInboxInsightsAuthentication> {
    return this.call<EmailInboxInsightsAuthentication>("GET", options, ({ signal, headers }) =>
      getEmailInboxInsightsAuthentication({ client: this.client, query, headers, signal }));
  }

  /**
   * Read the Google Postmaster user-reported spam rate for a verified owned domain.
This percentage differs from spam-folder placement and Bird feedback-loop
complaints across providers. Dates are inclusive UTC days, at most 30 days
apart; compare=previous_period adds the preceding period. The period rate is
an unweighted mean of reported days; sparse days are missing observations,
not zero complaints. Freshness identifies the last reported day, not a promised
update schedule. Correlation with placement cannot identify causative sends.
Sections can report not_configured when setup is incomplete; connection
status and setup are available in the dashboard, not through this read.

API-key calls require Insights preview access for your organization.
   *
   * @example Read Gmail complaint measurements and setup status
   * // Requires Insights preview access for the organization.
   * let sendingDomain: string | undefined;
   * for await (const domain of bird.email.inboxInsights.domains.list({ search: "mail.example.com" })) {
   *   if (domain.domain === "mail.example.com") { sendingDomain = domain.domain; break; }
   * }
   * if (!sendingDomain) throw new Error("Verify mail.example.com in this workspace first");
   * const report = await bird.email.inboxInsights.complaints({ sending_domain: sendingDomain });
   * console.log(report);
   */
  complaints(query: EmailInboxInsightsComplaintsQuery, options?: RequestOptions): APIPromise<EmailInboxInsightsComplaints> {
    return this.call<EmailInboxInsightsComplaints>("GET", options, ({ signal, headers }) =>
      getEmailInboxInsightsComplaints({ client: this.client, query, headers, signal }));
  }

  /**
   * Read spam-trap totals, kinds, networks and sampled hits for a verified owned
domain. Dates are inclusive UTC days, at most 30 days apart;
compare=previous_period includes the preceding period. hit_rows has its own
status and truncated_types; empty rows do not negate a positive total, and row
counts cannot reconstruct total hits. A measured zero is valid. Hits alone
do not identify the sending campaign or establish why placement changed.

API-key calls require Insights preview access for your organization.
   *
   * @example Read spam-trap hits including measured zero
   * // Requires Insights preview access for the organization.
   * let sendingDomain: string | undefined;
   * for await (const domain of bird.email.inboxInsights.domains.list({ search: "mail.example.com" })) {
   *   if (domain.domain === "mail.example.com") { sendingDomain = domain.domain; break; }
   * }
   * if (!sendingDomain) throw new Error("Verify mail.example.com in this workspace first");
   * const report = await bird.email.inboxInsights.spamTraps({ sending_domain: sendingDomain });
   * console.log(report);
   */
  spamTraps(query: EmailInboxInsightsSpamTrapsQuery, options?: RequestOptions): APIPromise<EmailInboxInsightsSpamTraps> {
    return this.call<EmailInboxInsightsSpamTraps>("GET", options, ({ signal, headers }) =>
      getEmailInboxInsightsSpamTraps({ client: this.client, query, headers, signal }));
  }

  /**
   * Check blocklist standing for the sending infrastructure of a verified domain owned by the workspace. This is a current lookup and accepts no date window. Inspect each target status and checked_at; a null active_count means the lookup service supplied no count. Zero and an empty target list do not establish complete coverage.

API-key calls require Insights preview access for your organization.
   *
   * @example Read the current blocklist result
   * // Requires Insights preview access for the organization.
   * let sendingDomain: string | undefined;
   * for await (const domain of bird.email.inboxInsights.domains.list({ search: "mail.example.com" })) {
   *   if (domain.domain === "mail.example.com") { sendingDomain = domain.domain; break; }
   * }
   * if (!sendingDomain) throw new Error("Verify mail.example.com in this workspace first");
   * const report = await bird.email.inboxInsights.blocklists({ sending_domain: sendingDomain });
   * console.log(report);
   */
  blocklists(query: EmailInboxInsightsBlocklistsQuery, options?: RequestOptions): APIPromise<EmailInboxInsightsBlocklists> {
    return this.call<EmailInboxInsightsBlocklists>("GET", options, ({ signal, headers }) =>
      getEmailInboxInsightsBlocklists({ client: this.client, query, headers, signal }));
  }
}
