// Code generated by surface-gen; DO NOT EDIT.
import { createEmailCompetitiveWatchlistBrand, deleteEmailCompetitiveWatchlistBrand, getEmailCompetitiveBrand, getEmailCompetitiveBrandSendTime } from "../generated/sdk.gen.js";
import type { CreateEmailCompetitiveWatchlistBrandData, DeleteEmailCompetitiveWatchlistBrandData, EmailCompetitiveBrandProfile, EmailCompetitiveSendTimeGrid, EmailCompetitiveWatchlistBrand, GetEmailCompetitiveBrandData, GetEmailCompetitiveBrandSendTimeData } from "../generated/types.gen.js";
import { Resource } from "./base.js";
import type { APIPromise, RequestOptions } from "../core/result.js";

export type { EmailCompetitiveWatchlistBrand };
export type { EmailCompetitiveBrandProfile };
export type { EmailCompetitiveSendTimeGrid };
export type EmailCompetitiveWatchlistBrandsCreateParams = NonNullable<CreateEmailCompetitiveWatchlistBrandData["body"]>;
export type EmailCompetitiveWatchlistBrandsGetQuery = NonNullable<GetEmailCompetitiveBrandData["query"]>;
export type EmailCompetitiveWatchlistBrandsSendTimeQuery = NonNullable<GetEmailCompetitiveBrandSendTimeData["query"]>;

export class EmailCompetitiveWatchlistBrandsResourceBase extends Resource {
  /**
   * Add a brand using the panel brand_id returned by brand search. The response id
identifies the new workspace watchlist entry for reads and removal. Each entry
uses one place in the organization-wide allowance and tracks the brand's
highest-volume sending domain. Reuse an idempotency key when retrying the same addition.

API-key, OAuth, and service-account calls require Insights preview access for your organization.
   *
   * @example Add the brand returned by search
   * // Requires Insights preview access for the organization.
   * const matches = await bird.email.competitive.brands.search({ q: "Everlane" });
   * const match = matches.data.find((brand) => brand.name === "Everlane");
   * if (!match) throw new Error("No exact Everlane match");
   * const entry = await bird.email.competitive.watchlist.brands.create({ brand_id: match.brand_id });
   * console.log(entry.id);
   */
  create(params: EmailCompetitiveWatchlistBrandsCreateParams, options?: RequestOptions): APIPromise<EmailCompetitiveWatchlistBrand> {
    return this.call<EmailCompetitiveWatchlistBrand>("POST", options, ({ signal, headers }) =>
      createEmailCompetitiveWatchlistBrand({ client: this.client, body: params, headers, signal }));
  }

  /**
   * Remove the workspace watchlist entry using its cwb_ ID. This frees one place
in the organization-wide allowance. Adding the brand again creates a new
entry; removal does not delete campaign data from eDataSource.

API-key calls require Insights preview access for your organization.
   *
   * @example Remove the selected competitor
   * // Requires Insights preview access for the organization.
   * const watchlist = await bird.email.competitive.watchlist.get({ range: 30 });
   * const entry = watchlist.data.find((row) => row.name === "Everlane" && row.watchlist_brand_id);
   * if (!entry?.watchlist_brand_id) throw new Error("Add Everlane to the watchlist first");
   * const watchlistBrandId = entry.watchlist_brand_id;
   * await bird.email.competitive.watchlist.brands.delete(watchlistBrandId);
   */
  delete(watchlistBrandId: string, options?: RequestOptions): APIPromise<void> {
    return this.call<void>("DELETE", options, ({ signal, headers }) =>
      deleteEmailCompetitiveWatchlistBrand({ client: this.client, path: { watchlist_brand_id: watchlistBrandId }, headers, signal }));
  }

  /**
   * Read one watched brand using the `watchlist_brand_id` from
`email.competitive.watchlist.get`; the panel `brand_id` returned by
`email.competitive.brands.search` is not accepted. The response includes headline figures
and a mailbox-provider breakdown.

API-key calls require Insights preview access for your organization.
   *
   * @example Read one watched brand
   * // Requires Insights preview access for the organization.
   * const watchlist = await bird.email.competitive.watchlist.get({ range: 30 });
   * const entry = watchlist.data.find((row) => row.name === "Everlane" && row.watchlist_brand_id);
   * if (!entry?.watchlist_brand_id) throw new Error("Add Everlane to the watchlist first");
   * const watchlistBrandId = entry.watchlist_brand_id;
   * const report = await bird.email.competitive.watchlist.brands.get(watchlistBrandId, { range: 30 });
   * console.log(report);
   */
  get(watchlistBrandId: string, query?: EmailCompetitiveWatchlistBrandsGetQuery, options?: RequestOptions): APIPromise<EmailCompetitiveBrandProfile> {
    return this.call<EmailCompetitiveBrandProfile>("GET", options, ({ signal, headers }) =>
      getEmailCompetitiveBrand({ client: this.client, path: { watchlist_brand_id: watchlistBrandId }, query, headers, signal }));
  }

  /**
   * Takes a watchlist_brand_id from `email.competitive.watchlist.get` and an
optional IANA timezone. Covers the last 90 days, with no range parameter.
Cells describe sending activity by weekday and hour. The returned timezone
labels the grid; peak_send_window can be null when no sending was observed.

API-key calls require Insights preview access for your organization.
   *
   * @example Read its send-time distribution
   * // Requires Insights preview access for the organization.
   * const watchlist = await bird.email.competitive.watchlist.get({ range: 30 });
   * const entry = watchlist.data.find((row) => row.name === "Everlane" && row.watchlist_brand_id);
   * if (!entry?.watchlist_brand_id) throw new Error("Add Everlane to the watchlist first");
   * const watchlistBrandId = entry.watchlist_brand_id;
   * const report = await bird.email.competitive.watchlist.brands.sendTime(watchlistBrandId, { timezone: "UTC" });
   * console.log(report);
   */
  sendTime(watchlistBrandId: string, query?: EmailCompetitiveWatchlistBrandsSendTimeQuery, options?: RequestOptions): APIPromise<EmailCompetitiveSendTimeGrid> {
    return this.call<EmailCompetitiveSendTimeGrid>("GET", options, ({ signal, headers }) =>
      getEmailCompetitiveBrandSendTime({ client: this.client, path: { watchlist_brand_id: watchlistBrandId }, query, headers, signal }));
  }
}
