// Code generated by surface-gen; DO NOT EDIT.
import { createEmailInboxInsightsSeedTest, getEmailInboxInsightsSeedTests } from "../generated/sdk.gen.js";
import type { CreateEmailInboxInsightsSeedTestData, EmailInboxInsightsSeedTestRegistration, EmailInboxInsightsSeedTests, GetEmailInboxInsightsSeedTestsData } from "../generated/types.gen.js";
import { Resource } from "./base.js";
import type { APIPromise, RequestOptions } from "../core/result.js";

export type { EmailInboxInsightsSeedTestRegistration };
export type { EmailInboxInsightsSeedTests };
export type EmailInboxInsightsSeedTestsCreateParams = NonNullable<CreateEmailInboxInsightsSeedTestData["body"]>;
export type EmailInboxInsightsSeedTestsListQuery = NonNullable<GetEmailInboxInsightsSeedTestsData["query"]>;

export class EmailInboxInsightsSeedTestsResourceBase extends Resource {
  /**
   * Register only when the intended send is ready. Read
`email.inbox_insights.seed_tests.configuration.get` for supported options.
CLI and MCP registration require OAuth login and browser confirmation: a signed-in
person registers the test from the review page. Direct API and SDK calls register
immediately. Registration spends organization-wide allowance and returns addresses;
it sends no email.
Use a separately authorized send to deliver the intended message to those addresses.
Keep the same explicit Idempotency-Key and body after a lost response. On 409 E27008,
contact support with the request ID and domain before starting another test.
A new CLI or MCP invocation can create another proposal; executing it can register
another batch. registration_id is for support, not a history lookup. The person
reviewing a CLI or MCP proposal needs write access to the workspace.
   *
   * @example Register addresses for a ready send
   * // Requires Insights preview access for the organization.
   * const idempotencyKey = process.env.IDEMPOTENCY_KEY;
   * if (!idempotencyKey) throw new Error("Set IDEMPOTENCY_KEY to a unique key for this registration and retain it for retries");
   * let sendingDomain: string | undefined;
   * for await (const domain of bird.email.inboxInsights.domains.list({ search: "mail.example.com" })) {
   *   if (domain.domain === "mail.example.com") { sendingDomain = domain.domain; break; }
   * }
   * if (!sendingDomain) throw new Error("Verify mail.example.com in this workspace first");
   * const configuration = await bird.email.inboxInsights.seedTests.configuration.get({ sending_domain: sendingDomain });
   * const pool = configuration.list_types.find(choice => choice.available);
   * const profile = configuration.engagement_profiles.find(choice => choice.available);
   * const region = configuration.regions[0];
   * if (!pool || !profile || !region) throw new Error("No seed-test options available");
   *
   * const report = await bird.email.inboxInsights.seedTests.create({ sending_domain: sendingDomain, list_type: pool.value, engagement_profile: profile.value, regions: [region.value] }, { idempotencyKey });
   * console.log(report);
   */
  create(params: EmailInboxInsightsSeedTestsCreateParams, options?: RequestOptions): APIPromise<EmailInboxInsightsSeedTestRegistration> {
    return this.call<EmailInboxInsightsSeedTestRegistration>("POST", options, ({ signal, headers }) =>
      createEmailInboxInsightsSeedTest({ client: this.client, body: params, headers, signal }));
  }

  /**
   * Read seed-test history for an owned sending domain and the organization-wide
allowance. Results are capped at 100; narrow the date window if tests.truncated
is true. Only the newest test has full detail. registration_id cannot locate a
history row, and absent history does not prove a registration failed.
Scoped API keys, OAuth and service accounts require organization preview access.
   *
   * @example Read seed-test history and allowance
   * // Requires Insights preview access for the organization.
   * let sendingDomain: string | undefined;
   * for await (const domain of bird.email.inboxInsights.domains.list({ search: "mail.example.com" })) {
   *   if (domain.domain === "mail.example.com") { sendingDomain = domain.domain; break; }
   * }
   * if (!sendingDomain) throw new Error("Verify mail.example.com in this workspace first");
   * const report = await bird.email.inboxInsights.seedTests.list({ sending_domain: sendingDomain });
   * console.log(report);
   */
  list(query: EmailInboxInsightsSeedTestsListQuery, options?: RequestOptions): APIPromise<EmailInboxInsightsSeedTests> {
    return this.call<EmailInboxInsightsSeedTests>("GET", options, ({ signal, headers }) =>
      getEmailInboxInsightsSeedTests({ client: this.client, query, headers, signal }));
  }
}
