// Code generated by surface-gen; DO NOT EDIT.
import { getEmailStatsByBounceCode, getEmailStatsByBroadcast, getEmailStatsByCategory, getEmailStatsByClient, getEmailStatsByComplaintType, getEmailStatsByLocation, getEmailStatsByMailboxProvider, getEmailStatsByMailboxProviderRegion, getEmailStatsByRecipientDomain, getEmailStatsBySendingDomain, getEmailStatsBySendingIp, getEmailStatsByTag, getEmailStatsByTemplate, getEmailStatsDaily, getEmailStatsHourly, getEmailStatsQuery, getEmailStatsSummary } from "../generated/sdk.gen.js";
import type { EmailBounceCodeStatsPoint, EmailBroadcastStatsPoint, EmailCategoryStatsPoint, EmailClientStatsPoint, EmailComplaintTypeStatsPoint, EmailLocationStatsPoint, EmailMailboxProviderRegionStatsPoint, EmailMailboxProviderStatsPoint, EmailRecipientDomainStatsPoint, EmailSendingDomainStatsPoint, EmailSendingIpStatsPoint, EmailStatsByBounceCodeResponse, EmailStatsByBroadcastResponse, EmailStatsByCategoryResponse, EmailStatsByClientResponse, EmailStatsByComplaintTypeResponse, EmailStatsByLocationResponse, EmailStatsByMailboxProviderRegionResponse, EmailStatsByMailboxProviderResponse, EmailStatsByRecipientDomainResponse, EmailStatsBySendingDomainResponse, EmailStatsBySendingIpResponse, EmailStatsByTemplateResponse, EmailStatsQueryGroup, EmailStatsQueryResponse, EmailStatsResponse, EmailStatsSummary, EmailStatsTagsResponse, EmailTagStatsPoint, EmailTemplateStatsPoint, GetEmailStatsByBounceCodeData, GetEmailStatsByBroadcastData, GetEmailStatsByCategoryData, GetEmailStatsByClientData, GetEmailStatsByComplaintTypeData, GetEmailStatsByLocationData, GetEmailStatsByMailboxProviderData, GetEmailStatsByMailboxProviderRegionData, GetEmailStatsByRecipientDomainData, GetEmailStatsBySendingDomainData, GetEmailStatsBySendingIpData, GetEmailStatsByTagData, GetEmailStatsByTemplateData, GetEmailStatsDailyData, GetEmailStatsHourlyData, GetEmailStatsQueryData, GetEmailStatsSummaryData } from "../generated/types.gen.js";
import { Resource } from "./base.js";
import type { APIPromise, PaginatedPromise, RequestOptions } from "../core/result.js";

export type { EmailStatsQueryGroup };
export type { EmailStatsSummary };
export type { EmailStatsResponse };
export type { EmailTagStatsPoint };
export type { EmailCategoryStatsPoint };
export type { EmailSendingIpStatsPoint };
export type { EmailSendingDomainStatsPoint };
export type { EmailRecipientDomainStatsPoint };
export type { EmailMailboxProviderStatsPoint };
export type { EmailMailboxProviderRegionStatsPoint };
export type { EmailTemplateStatsPoint };
export type { EmailLocationStatsPoint };
export type { EmailClientStatsPoint };
export type { EmailBounceCodeStatsPoint };
export type { EmailComplaintTypeStatsPoint };
export type { EmailBroadcastStatsPoint };
export type { EmailStatsQueryResponse };
export type { EmailStatsTagsResponse };
export type { EmailStatsByCategoryResponse };
export type { EmailStatsBySendingIpResponse };
export type { EmailStatsBySendingDomainResponse };
export type { EmailStatsByRecipientDomainResponse };
export type { EmailStatsByMailboxProviderResponse };
export type { EmailStatsByMailboxProviderRegionResponse };
export type { EmailStatsByTemplateResponse };
export type { EmailStatsByLocationResponse };
export type { EmailStatsByClientResponse };
export type { EmailStatsByBounceCodeResponse };
export type { EmailStatsByComplaintTypeResponse };
export type { EmailStatsByBroadcastResponse };
export type EmailStatsQueryParams = NonNullable<GetEmailStatsQueryData["body"]>;
export type EmailStatsSummaryQuery = NonNullable<GetEmailStatsSummaryData["query"]>;
export type EmailStatsDailyQuery = NonNullable<GetEmailStatsDailyData["query"]>;
export type EmailStatsHourlyQuery = NonNullable<GetEmailStatsHourlyData["query"]>;
export type EmailStatsByTagQuery = NonNullable<GetEmailStatsByTagData["query"]>;
export type EmailStatsByCategoryQuery = NonNullable<GetEmailStatsByCategoryData["query"]>;
export type EmailStatsBySendingIpQuery = NonNullable<GetEmailStatsBySendingIpData["query"]>;
export type EmailStatsBySendingDomainQuery = NonNullable<GetEmailStatsBySendingDomainData["query"]>;
export type EmailStatsByRecipientDomainQuery = NonNullable<GetEmailStatsByRecipientDomainData["query"]>;
export type EmailStatsByMailboxProviderQuery = NonNullable<GetEmailStatsByMailboxProviderData["query"]>;
export type EmailStatsByMailboxProviderRegionQuery = NonNullable<GetEmailStatsByMailboxProviderRegionData["query"]>;
export type EmailStatsByTemplateQuery = NonNullable<GetEmailStatsByTemplateData["query"]>;
export type EmailStatsByLocationQuery = NonNullable<GetEmailStatsByLocationData["query"]>;
export type EmailStatsByClientQuery = NonNullable<GetEmailStatsByClientData["query"]>;
export type EmailStatsByBounceCodeQuery = NonNullable<GetEmailStatsByBounceCodeData["query"]>;
export type EmailStatsByComplaintTypeQuery = NonNullable<GetEmailStatsByComplaintTypeData["query"]>;
export type EmailStatsByBroadcastQuery = NonNullable<GetEmailStatsByBroadcastData["query"]>;

export class EmailStatsResource extends Resource {
  /**
   * Select email metrics over a date or instant window, optionally grouped by one dimension with complete time series per group. Events are selected and bucketed by when they occurred, including activity on messages sent earlier. Filters match recorded event context. Unsupported combinations and unavailable history return 422. Follow cursors by replaying the original body and changing its cursor fields; the response period has an exclusive end and must not replace the request end. Use a new idempotency key for each continuation page; reuse a key only to retry the same page.
   *
   * @example Weekly deliveries by recipient domain
   * for await (const group of bird.email.stats.query({
   *   from: "2026-08-03",
   *   to: "2026-08-16",
   *   metrics: ["delivered", "bounce_rate"],
   *   group_by: "recipient_domain",
   *   grain: "week",
   *   limit: 25,
   * })) {
   *   console.log(group.dimensions, group.metrics, group.series);
   * }
   */
  query(params: EmailStatsQueryParams, options?: RequestOptions): PaginatedPromise<EmailStatsQueryGroup, EmailStatsQueryResponse> {
    return this.paginated<EmailStatsQueryGroup, EmailStatsQueryResponse>("POST", options, ({ signal, headers }, cursor) =>
      getEmailStatsQuery({ client: this.client, body: { ...params, starting_after: cursor ?? params.starting_after, ending_before: cursor === undefined ? params.ending_before : undefined }, headers, signal }));
  }

  /**
   * Aggregate email KPIs for one period: sends, delivered, bounces, complaints, opens, clicks, their rates, and latency percentiles. The `from` and `to` values are both `YYYY-MM-DD` days or both RFC 3339 instants (hour grain). Add `compare=previous_period` for deltas versus the prior window. For a per-day or per-hour series use `email.stats.daily` or `email.stats.hourly`.
   *
   * @example Summary for a month
   * const s = await bird.email.stats.summary({ from: "2026-05-01", to: "2026-05-31" });
   * console.log(s.sends_accepted, s.delivery.delivered);
   */
  summary(query?: EmailStatsSummaryQuery, options?: RequestOptions): APIPromise<EmailStatsSummary> {
    return this.call<EmailStatsSummary>("GET", options, ({ signal, headers }) =>
      getEmailStatsSummary({ client: this.client, query, headers, signal }));
  }

  /**
   * Per-day email stats series (counts, rates, latency percentiles), gap-filled with zero rows, max 365 days. At most one filter of `category`, `sending_domain`, `tag`, `sending_ip`, `recipient_domain`, `template`. For hour resolution use `email.stats.hourly`; for one aggregate row use `email.stats.summary`.
   *
   * @example 
   * const series = await bird.email.stats.daily({ from: "2026-05-01", to: "2026-05-31" });
   * for (const row of series.data) console.log(row.bucket, row.delivery.delivered);
   */
  daily(query?: EmailStatsDailyQuery, options?: RequestOptions): APIPromise<EmailStatsResponse> {
    return this.call<EmailStatsResponse>("GET", options, ({ signal, headers }) =>
      getEmailStatsDaily({ client: this.client, query, headers, signal }));
  }

  /**
   * Per-hour email stats series, gap-filled with zero rows, max 720 hours (30 days). Takes the same single-dimension filters as `email.stats.daily`; for longer ranges use `email.stats.daily`, for one aggregate row use `email.stats.summary`.
   *
   * @example 
   * const series = await bird.email.stats.hourly({ from: "2026-05-01", to: "2026-05-02" });
   * for (const row of series.data) console.log(row.bucket, row.delivery.delivered);
   */
  hourly(query?: EmailStatsHourlyQuery, options?: RequestOptions): APIPromise<EmailStatsResponse> {
    return this.call<EmailStatsResponse>("GET", options, ({ signal, headers }) =>
      getEmailStatsHourly({ client: this.client, query, headers, signal }));
  }

  /**
   * Email delivery and engagement stats grouped by tag, one row per `name:value` pair set at send time. Rows are ranked by `sort`, `processed` by default. Set `include_trend=true` to add a per-bucket rate series to each row.
   *
   * @example Top 10 tags by delivered
   * const { data } = await bird.email.stats.byTag({
   *   from: "2026-05-01",
   *   to: "2026-05-31",
   *   sort: "delivered",
   *   limit: 10,
   * });
   * for (const row of data) console.log(row.tag, row.delivery.delivered);
   */
  byTag(query?: EmailStatsByTagQuery, options?: RequestOptions): PaginatedPromise<EmailTagStatsPoint, EmailStatsTagsResponse> {
    return this.paginated<EmailTagStatsPoint, EmailStatsTagsResponse>("GET", options, ({ signal, headers }, cursor) =>
      getEmailStatsByTag({ client: this.client, query: { ...query, starting_after: cursor ?? query?.starting_after, ending_before: cursor === undefined ? query?.ending_before : undefined }, headers, signal }));
  }

  /**
   * Email delivery and engagement stats grouped by category, meaning `transactional` compared with `marketing`. Rows are ranked by `sort`, `processed` by default. Set `include_trend=true` to add a per-bucket rate series to each row.
   *
   * @example 
   * const { data } = await bird.email.stats.byCategory({ from: "2026-05-01", to: "2026-05-31" });
   * for (const row of data) console.log(row.category, row.delivery.delivered);
   */
  byCategory(query?: EmailStatsByCategoryQuery, options?: RequestOptions): PaginatedPromise<EmailCategoryStatsPoint, EmailStatsByCategoryResponse> {
    return this.paginated<EmailCategoryStatsPoint, EmailStatsByCategoryResponse>("GET", options, ({ signal, headers }, cursor) =>
      getEmailStatsByCategory({ client: this.client, query: { ...query, starting_after: cursor ?? query?.starting_after, ending_before: cursor === undefined ? query?.ending_before : undefined }, headers, signal }));
  }

  /**
   * Delivery and bounce stats grouped by sending IP, with deferral counts alongside them. `sort=bounces.block` surfaces reputation-damaged IPs first. Engagement, accepted, and processed counts aren't available per IP, and complaint and out-of-band bounce counts always read `0` here. For workspace-wide figures, use `email.stats.daily`.
   *
   * @example 
   * const { data } = await bird.email.stats.bySendingIp({
   *   from: "2026-05-01",
   *   to: "2026-05-31",
   *   sort: "bounces.block",
   *   limit: 20,
   * });
   * for (const row of data) console.log(row.sending_ip, row.delivery.delivered);
   */
  bySendingIp(query?: EmailStatsBySendingIpQuery, options?: RequestOptions): PaginatedPromise<EmailSendingIpStatsPoint, EmailStatsBySendingIpResponse> {
    return this.paginated<EmailSendingIpStatsPoint, EmailStatsBySendingIpResponse>("GET", options, ({ signal, headers }, cursor) =>
      getEmailStatsBySendingIp({ client: this.client, query: { ...query, starting_after: cursor ?? query?.starting_after, ending_before: cursor === undefined ? query?.ending_before : undefined }, headers, signal }));
  }

  /**
   * Email delivery and engagement stats grouped by sending (`From`) domain, so you can compare deliverability across your workspace's verified domains. For per-IP reputation instead, use `email.stats.by_sending_ip`.
   *
   * @example 
   * const { data } = await bird.email.stats.bySendingDomain({
   *   from: "2026-05-01",
   *   to: "2026-05-31",
   *   sort: "delivery_rate",
   *   limit: 25,
   * });
   * for (const row of data) console.log(row.sending_domain, row.delivery.delivery_rate);
   */
  bySendingDomain(query?: EmailStatsBySendingDomainQuery, options?: RequestOptions): PaginatedPromise<EmailSendingDomainStatsPoint, EmailStatsBySendingDomainResponse> {
    return this.paginated<EmailSendingDomainStatsPoint, EmailStatsBySendingDomainResponse>("GET", options, ({ signal, headers }, cursor) =>
      getEmailStatsBySendingDomain({ client: this.client, query: { ...query, starting_after: cursor ?? query?.starting_after, ending_before: cursor === undefined ? query?.ending_before : undefined }, headers, signal }));
  }

  /**
   * Email delivery and engagement stats grouped by exact recipient mailbox domain, for example `gmail.com`. Finer-grained than `email.stats.by_mailbox_provider`, which buckets domains into providers.
   *
   * @example 
   * const { data } = await bird.email.stats.byRecipientDomain({
   *   from: "2026-05-01",
   *   to: "2026-05-31",
   *   sort: "bounce_rate",
   *   limit: 25,
   * });
   * for (const row of data) console.log(row.recipient_domain, row.delivery.bounce_rate);
   */
  byRecipientDomain(query?: EmailStatsByRecipientDomainQuery, options?: RequestOptions): PaginatedPromise<EmailRecipientDomainStatsPoint, EmailStatsByRecipientDomainResponse> {
    return this.paginated<EmailRecipientDomainStatsPoint, EmailStatsByRecipientDomainResponse>("GET", options, ({ signal, headers }, cursor) =>
      getEmailStatsByRecipientDomain({ client: this.client, query: { ...query, starting_after: cursor ?? query?.starting_after, ending_before: cursor === undefined ? query?.ending_before : undefined }, headers, signal }));
  }

  /**
   * Email delivery and engagement stats grouped by recipient mailbox provider, for example `gmail`, `microsoft`, or `yahoo`. It covers the delivery stage onward and omits accepted or processed counts. For a per-region split within a provider, use `email.stats.by_mailbox_provider_region`; for exact destination domains instead, use `email.stats.by_recipient_domain`.
   *
   * @example 
   * const { data } = await bird.email.stats.byMailboxProvider({
   *   from: "2026-05-01",
   *   to: "2026-05-31",
   *   limit: 25,
   * });
   * for (const row of data) console.log(row.mailbox_provider, row.delivery.delivered);
   */
  byMailboxProvider(query?: EmailStatsByMailboxProviderQuery, options?: RequestOptions): PaginatedPromise<EmailMailboxProviderStatsPoint, EmailStatsByMailboxProviderResponse> {
    return this.paginated<EmailMailboxProviderStatsPoint, EmailStatsByMailboxProviderResponse>("GET", options, ({ signal, headers }, cursor) =>
      getEmailStatsByMailboxProvider({ client: this.client, query: { ...query, starting_after: cursor ?? query?.starting_after, ending_before: cursor === undefined ? query?.ending_before : undefined }, headers, signal }));
  }

  /**
   * Email delivery and engagement stats grouped by a mailbox provider and provider region pair, for example `gmail` in `NA`. It covers the delivery stage onward and omits accepted or processed counts. For the provider-level view without the region split, use `email.stats.by_mailbox_provider`.
   *
   * @example 
   * const { data } = await bird.email.stats.byMailboxProviderRegion({
   *   from: "2026-05-01",
   *   to: "2026-05-31",
   *   limit: 25,
   * });
   * for (const row of data) console.log(row.mailbox_provider, row.mailbox_provider_region, row.delivery.delivered);
   */
  byMailboxProviderRegion(query?: EmailStatsByMailboxProviderRegionQuery, options?: RequestOptions): PaginatedPromise<EmailMailboxProviderRegionStatsPoint, EmailStatsByMailboxProviderRegionResponse> {
    return this.paginated<EmailMailboxProviderRegionStatsPoint, EmailStatsByMailboxProviderRegionResponse>("GET", options, ({ signal, headers }, cursor) =>
      getEmailStatsByMailboxProviderRegion({ client: this.client, query: { ...query, starting_after: cursor ?? query?.starting_after, ending_before: cursor === undefined ? query?.ending_before : undefined }, headers, signal }));
  }

  /**
   * Email delivery and engagement stats grouped by the template used at send time, keyed by template id (`emt_…`); only templated sends appear. A single template's trend over time comes from `email.stats.daily` with its `template` filter.
   *
   * @example 
   * const { data } = await bird.email.stats.byTemplate({
   *   from: "2026-05-01",
   *   to: "2026-05-31",
   *   sort: "open_rate",
   *   limit: 25,
   * });
   * for (const row of data) console.log(row.template_id, row.engagement.open_rate);
   */
  byTemplate(query?: EmailStatsByTemplateQuery, options?: RequestOptions): PaginatedPromise<EmailTemplateStatsPoint, EmailStatsByTemplateResponse> {
    return this.paginated<EmailTemplateStatsPoint, EmailStatsByTemplateResponse>("GET", options, ({ signal, headers }, cursor) =>
      getEmailStatsByTemplate({ client: this.client, query: { ...query, starting_after: cursor ?? query?.starting_after, ending_before: cursor === undefined ? query?.ending_before : undefined }, headers, signal }));
  }

  /**
   * Opens and clicks grouped by country, region, or city, whichever you choose with `group_by`. It only has engagement counts, no delivery counts or rates. For engagement grouped by mail client or device instead, use `email.stats.by_client`.
   *
   * @example 
   * const { data } = await bird.email.stats.byLocation({
   *   from: "2026-05-01",
   *   to: "2026-05-31",
   *   limit: 25,
   * });
   * for (const row of data) console.log(row.country, row.engagement.unique_opens);
   */
  byLocation(query?: EmailStatsByLocationQuery, options?: RequestOptions): PaginatedPromise<EmailLocationStatsPoint, EmailStatsByLocationResponse> {
    return this.paginated<EmailLocationStatsPoint, EmailStatsByLocationResponse>("GET", options, ({ signal, headers }, cursor) =>
      getEmailStatsByLocation({ client: this.client, query: { ...query, starting_after: cursor ?? query?.starting_after, ending_before: cursor === undefined ? query?.ending_before : undefined }, headers, signal }));
  }

  /**
   * Opens and clicks grouped by mail client, operating system, or device type, whichever you choose with `group_by`. It only has engagement counts, no delivery counts or rates. For engagement grouped by geography instead, use `email.stats.by_location`.
   *
   * @example 
   * const { data } = await bird.email.stats.byClient({
   *   from: "2026-05-01",
   *   to: "2026-05-31",
   *   limit: 25,
   * });
   * for (const row of data) console.log(row.email_client, row.engagement.unique_opens);
   */
  byClient(query?: EmailStatsByClientQuery, options?: RequestOptions): PaginatedPromise<EmailClientStatsPoint, EmailStatsByClientResponse> {
    return this.paginated<EmailClientStatsPoint, EmailStatsByClientResponse>("GET", options, ({ signal, headers }, cursor) =>
      getEmailStatsByClient({ client: this.client, query: { ...query, starting_after: cursor ?? query?.starting_after, ending_before: cursor === undefined ? query?.ending_before : undefined }, headers, signal }));
  }

  /**
   * Bounce counts grouped by the SMTP error code the receiving mail server returned. Each row also breaks the bounce down into its hard, soft, admin, block, and undetermined split. It omits delivered, open, and click counts because a bounce code only appears on a bounce event. For bounces broken down by destination instead, use `email.stats.by_recipient_domain` or `email.stats.by_mailbox_provider`.
   *
   * @example 
   * const { data } = await bird.email.stats.byBounceCode({
   *   from: "2026-05-01",
   *   to: "2026-05-31",
   *   sort: "bounced",
   *   limit: 25,
   * });
   * for (const row of data) console.log(row.smtp_error_code, row.bounced);
   */
  byBounceCode(query?: EmailStatsByBounceCodeQuery, options?: RequestOptions): PaginatedPromise<EmailBounceCodeStatsPoint, EmailStatsByBounceCodeResponse> {
    return this.paginated<EmailBounceCodeStatsPoint, EmailStatsByBounceCodeResponse>("GET", options, ({ signal, headers }, cursor) =>
      getEmailStatsByBounceCode({ client: this.client, query: { ...query, starting_after: cursor ?? query?.starting_after, ending_before: cursor === undefined ? query?.ending_before : undefined }, headers, signal }));
  }

  /**
   * Spam-complaint counts grouped by the feedback-loop complaint type, for example `abuse`, `fraud`, or `virus`. This complaint-only breakdown omits delivery and engagement counts. For complaints broken down by destination instead, use `email.stats.by_mailbox_provider` or `email.stats.by_recipient_domain`.
   *
   * @example 
   * const { data } = await bird.email.stats.byComplaintType({ from: "2026-05-01", to: "2026-05-31" });
   * for (const row of data) console.log(row.feedback_type, row.complained);
   */
  byComplaintType(query?: EmailStatsByComplaintTypeQuery, options?: RequestOptions): PaginatedPromise<EmailComplaintTypeStatsPoint, EmailStatsByComplaintTypeResponse> {
    return this.paginated<EmailComplaintTypeStatsPoint, EmailStatsByComplaintTypeResponse>("GET", options, ({ signal, headers }, cursor) =>
      getEmailStatsByComplaintType({ client: this.client, query: { ...query, starting_after: cursor ?? query?.starting_after, ending_before: cursor === undefined ? query?.ending_before : undefined }, headers, signal }));
  }

  /**
   * Email delivery and engagement stats grouped by broadcast. Only broadcast sends appear. Reflects roughly the last 30 days of activity.
   *
   * @example 
   * const { data } = await bird.email.stats.byBroadcast({
   *   from: "2026-05-01",
   *   to: "2026-05-31",
   *   sort: "click_rate",
   *   limit: 25,
   * });
   * for (const row of data) console.log(row.broadcast_id, row.engagement.click_rate);
   */
  byBroadcast(query?: EmailStatsByBroadcastQuery, options?: RequestOptions): PaginatedPromise<EmailBroadcastStatsPoint, EmailStatsByBroadcastResponse> {
    return this.paginated<EmailBroadcastStatsPoint, EmailStatsByBroadcastResponse>("GET", options, ({ signal, headers }, cursor) =>
      getEmailStatsByBroadcast({ client: this.client, query: { ...query, starting_after: cursor ?? query?.starting_after, ending_before: cursor === undefined ? query?.ending_before : undefined }, headers, signal }));
  }
}
