// Code generated by surface-gen; DO NOT EDIT.
import { cancelEmailMessage, getEmailHealth, getEmailMessage, listEmailMessages } from "../generated/sdk.gen.js";
import type { CancelEmailMessageData, EmailHealth, EmailMessage, GetEmailHealthData, GetEmailMessageData, ListEmailMessagesData } from "../generated/types.gen.js";
import { Resource } from "./base.js";
import type { APIPromise, PaginatedPromise, RequestOptions } from "../core/result.js";

export type { EmailMessage };
export type { EmailHealth };
export type EmailListQuery = NonNullable<ListEmailMessagesData["query"]>;
export type EmailHealthQuery = NonNullable<GetEmailHealthData["query"]>;

export class EmailResourceBase extends Resource {
  /**
   * Fetch one email message by `id`, with aggregate delivery status and per-state recipient counts. The message body (`html`, `text`) is not returned. Per-recipient delivery statuses and the event log are separate sub-resources: `GET /v1/email/messages/{message_id}/recipients` and `GET /v1/email/messages/{message_id}/events`. `broadcast_id` identifies the broadcast that sent the message and is absent for other sends. A broadcast records one message per recipient; these copies share the same `broadcast_id`.
   *
   * @example 
   * const msg = await bird.email.get("em_abc123");
   * msg.status; // "accepted" | "processed" | "delivered" | "bounced" | …
   * msg.delivered_count;
   * msg.bounced_count;
   */
  get(messageId: string, options?: RequestOptions): APIPromise<EmailMessage> {
    return this.call<EmailMessage>("GET", options, ({ signal, headers }) =>
      getEmailMessage({ client: this.client, path: { message_id: messageId }, headers, signal }));
  }

  /**
   * List sent email messages, newest first, as a cursor page (`{data, next_cursor, …}`). Pass `next_cursor` back as `starting_after` to fetch the next page. Filter by creation time with the half-open range `created_after` (inclusive) and `created_before` (exclusive). For a single UTC day, `created_after` is that day at 00:00:00Z and `created_before` is the next day at 00:00:00Z. `broadcast_id` identifies the broadcast that sent the message and is absent for other sends. A broadcast records one message per recipient; these copies share the same `broadcast_id`.
   *
   * @example 
   * for await (const message of bird.email.list({ status: "bounced" })) {
   *   console.log(message.id);
   * }
   */
  list(query?: EmailListQuery, options?: RequestOptions): PaginatedPromise<EmailMessage> {
    return this.paginated<EmailMessage>("GET", options, ({ signal, headers }, cursor) =>
      listEmailMessages({ client: this.client, query: { ...query, starting_after: cursor ?? query?.starting_after, ending_before: cursor === undefined ? query?.ending_before : undefined }, headers, signal }));
  }

  /**
   * Cancel a scheduled email before it sends. Only works while the message's `status` is still `scheduled`. Once it starts sending, or was already canceled, the call returns a conflict error. Canceling does not return consumed scheduled-send quota.
   *
   * @example 
   * await bird.email.cancel("em_abc123");
   */
  cancel(messageId: string, options?: RequestOptions): APIPromise<void> {
    return this.call<void>("POST", options, ({ signal, headers }) =>
      cancelEmailMessage({ client: this.client, path: { message_id: messageId }, headers, signal }));
  }

  /**
   * Deliverability verdict for one window: an overall `healthy`, `watching`, or `throttled` status, plus signals for delivery, opens, bounces, and complaints. Each signal carries its rate and verdict. Delivery, bounce, and complaint signals include the thresholds that set their verdicts; open rate has no risk thresholds. Reports risk only and never pauses sending. Window defaults to the 7 days before today (UTC), maximum 365 days. For the counts and rates behind the verdict use `email.stats.summary`.
   *
   * @example Sending-health verdict for a month
   * const health = await bird.email.health({ from: "2026-05-01", to: "2026-05-31" });
   * console.log(health.status);
   * for (const signal of health.signals) {
   *   console.log(signal.metric, signal.value, signal.status);
   * }
   */
  health(query?: EmailHealthQuery, options?: RequestOptions): APIPromise<EmailHealth> {
    return this.call<EmailHealth>("GET", options, ({ signal, headers }) =>
      getEmailHealth({ client: this.client, query, headers, signal }));
  }
}
