// Code generated by surface-gen; DO NOT EDIT.
import { getEmailCompetitiveNotableCampaigns, getEmailCompetitiveWatchlist } from "../generated/sdk.gen.js";
import type { EmailCompetitiveNotableFeed, EmailCompetitiveWatchlist, GetEmailCompetitiveNotableCampaignsData, GetEmailCompetitiveWatchlistData } from "../generated/types.gen.js";
import { Resource } from "./base.js";
import type { APIPromise, RequestOptions } from "../core/result.js";

export type { EmailCompetitiveWatchlist };
export type { EmailCompetitiveNotableFeed };
export type EmailCompetitiveWatchlistGetQuery = NonNullable<GetEmailCompetitiveWatchlistData["query"]>;
export type EmailCompetitiveWatchlistNotableQuery = NonNullable<GetEmailCompetitiveNotableCampaignsData["query"]>;

export class EmailCompetitiveWatchlistResourceBase extends Resource {
  /**
   * Compare volume, campaigns per week, placement, reading and audience overlap
across the existing watchlist in one read; no setup or per-brand reads are
needed for these headline metrics. Each brand covers its tracked sending
domains, not necessarily its whole program. `watchlist_brand_id` identifies
a saved entry; `email.competitive.watchlist.brands.get` adds provider detail.

Rate fields are fractions (0.2 means 20%); fields ending in percent already
use percentages. Your measured sends and cadence cover the workspace; your
panel rates and overlap describe its highest-volume sending domain. Overlap
uses that domain's panel-observed audience as denominator. `provenance`
identifies each metric's source. Panel read rate is not your open rate;
placement rates cannot establish counts of your delivered messages in spam.
Campaign cadence is not per-subscriber frequency. Interpret nulls by field:
rates can be unavailable, while last_campaign can mean none was observed and
overlap can mean no overlap was returned. Do not replace nulls with zeros.

API-key calls require Insights preview access for your organization.
   *
   * @example Read watchlist figures without replacing missing values
   * // Requires Insights preview access for the organization.
   * const report = await bird.email.competitive.watchlist.get({ range: 30 });
   * console.log(report.data);
   */
  get(query?: EmailCompetitiveWatchlistGetQuery, options?: RequestOptions): APIPromise<EmailCompetitiveWatchlist> {
    return this.call<EmailCompetitiveWatchlist>("GET", options, ({ signal, headers }) =>
      getEmailCompetitiveWatchlist({ client: this.client, query, headers, signal }));
  }

  /**
   * Returns up to 100 findings across watched brands for the requested range.
A campaign can appear for multiple signals, each with its own evidence.
truncated reports omitted eligible findings; this report has no cursor pages.
Each finding carries the watched-brand and campaign IDs for
`email.competitive.watchlist.brands.campaigns.get`.

API-key calls require Insights preview access for your organization.
   *
   * @example Read notable campaigns
   * // Requires Insights preview access for the organization.
   * const report = await bird.email.competitive.watchlist.notable({ range: 30 });
   * console.log(report);
   */
  notable(query?: EmailCompetitiveWatchlistNotableQuery, options?: RequestOptions): APIPromise<EmailCompetitiveNotableFeed> {
    return this.call<EmailCompetitiveNotableFeed>("GET", options, ({ signal, headers }) =>
      getEmailCompetitiveNotableCampaigns({ client: this.client, query, headers, signal }));
  }
}
