// Code generated by surface-gen; DO NOT EDIT.
import { deleteEmailTemplateVersion, getEmailTemplateVersion, listEmailTemplateVersions, rollbackEmailTemplate, submitEmailTemplateVersion } from "../generated/sdk.gen.js";
import type { DeleteEmailTemplateVersionData, EmailTemplate, EmailTemplateSubmitResult, EmailTemplateVersion, EmailTemplateVersionSummary, GetEmailTemplateVersionData, ListEmailTemplateVersionsData, RollbackEmailTemplateData, SubmitEmailTemplateVersionData } from "../generated/types.gen.js";
import { Resource } from "./base.js";
import type { APIPromise, PaginatedPromise, RequestOptions } from "../core/result.js";

export type { EmailTemplateVersionSummary };
export type { EmailTemplateVersion };
export type { EmailTemplateSubmitResult };
export type { EmailTemplate };
export type EmailTemplatesVersionsListQuery = NonNullable<ListEmailTemplateVersionsData["query"]>;
export type EmailTemplatesVersionsSubmitParams = NonNullable<SubmitEmailTemplateVersionData["body"]>;
export type EmailTemplatesVersionsRollbackParams = NonNullable<RollbackEmailTemplateData["body"]>;

export class EmailTemplatesVersionsResourceBase extends Resource {
  /**
   * List every version of a template (the draft plus all published versions), newest first.
   */
  list(templateRef: string, query?: EmailTemplatesVersionsListQuery, options?: RequestOptions): PaginatedPromise<EmailTemplateVersionSummary> {
    return this.paginated<EmailTemplateVersionSummary>("GET", options, ({ signal, headers }, cursor) =>
      listEmailTemplateVersions({ client: this.client, path: { template_ref: templateRef }, query: { ...query, starting_after: cursor ?? query?.starting_after }, headers, signal }));
  }

  /**
   * Read one version of a template: its lifecycle metadata (`status`, `version_number`, `published_at`), the content it froze in every language, and the `variables` that content expects at send time.
   */
  get(templateRef: string, versionId: string, options?: RequestOptions): APIPromise<EmailTemplateVersion> {
    return this.call<EmailTemplateVersion>("GET", options, ({ signal, headers }) =>
      getEmailTemplateVersion({ client: this.client, path: { template_ref: templateRef, version_id: versionId }, headers, signal }));
  }

  /**
   * Throw away the draft's unsaved changes, resetting its content to what is currently published.
   */
  delete(templateRef: string, versionId: string, options?: RequestOptions): APIPromise<void> {
    return this.call<void>("DELETE", options, ({ signal, headers }) =>
      deleteEmailTemplateVersion({ client: this.client, path: { template_ref: templateRef, version_id: versionId }, headers, signal }));
  }

  /**
   * Freeze a complete draft as the new immutable live version. Every language needs a subject and body, and the default language must be present. Submission is all or nothing and reports every language error. Set `validate_only: true` to check without publishing, or pass `expected_revision` to reject a concurrent edit. An unchanged draft is rejected. The response also carries `compatibility` across every language, each finding naming the language it is in: what the HTML uses that mail clients remove, ignore, or render inconsistently. Advisory and separate from `errors`, so a finding never fails a submit.
   */
  submit(templateRef: string, versionId: string, params: EmailTemplatesVersionsSubmitParams = {}, options?: RequestOptions): APIPromise<EmailTemplateSubmitResult> {
    return this.call<EmailTemplateSubmitResult>("POST", options, ({ signal, headers }) =>
      submitEmailTemplateVersion({ client: this.client, path: { template_ref: templateRef, version_id: versionId }, body: params, headers, signal }));
  }

  /**
   * Make an earlier published version live again and reset the draft to its content, so editing continues from it. The change is immediate, creates no new version, and leaves version history unchanged. The request must include the draft `revision` last read. The draft's current content is replaced. Only published versions can be rolled back to.
   */
  rollback(templateRef: string, versionId: string, params: EmailTemplatesVersionsRollbackParams, options?: RequestOptions): APIPromise<EmailTemplate> {
    return this.call<EmailTemplate>("POST", options, ({ signal, headers }) =>
      rollbackEmailTemplate({ client: this.client, path: { template_ref: templateRef, version_id: versionId }, body: params, headers, signal }));
  }
}
