// Code generated by surface-gen; DO NOT EDIT.
import { cancelEmailMessage, getEmailMessage, listEmailMessages } from "../generated/sdk.gen.js";
import type { CancelEmailMessageData, EmailMessage, GetEmailMessageData, ListEmailMessagesData } from "../generated/types.gen.js";
import { Resource } from "./base.js";
import type { APIPromise, PaginatedPromise, RequestOptions } from "../core/result.js";

export type { EmailMessage };
export type EmailListQuery = NonNullable<ListEmailMessagesData["query"]>;

export class EmailResourceBase extends Resource {
  /**
   * Fetch one email message by `id`, with aggregate delivery status and per-state recipient counts. The message body (`html`, `text`) is not returned. Per-recipient delivery statuses and the event log are separate sub-resources: `GET /v1/email/messages/{message_id}/recipients` and `GET /v1/email/messages/{message_id}/events`.
   *
   * @example 
   * const msg = await bird.email.get("em_abc123");
   * msg.status; // "accepted" | "processed" | "delivered" | "bounced" | …
   * msg.delivered_count;
   * msg.bounced_count;
   */
  get(messageId: string, options?: RequestOptions): APIPromise<EmailMessage> {
    return this.call<EmailMessage>("GET", options, ({ signal, headers }) =>
      getEmailMessage({ client: this.client, path: { message_id: messageId }, headers, signal }));
  }

  /**
   * List sent email messages, newest first, as a cursor page (`{data, next_cursor, …}`). Pass `next_cursor` back as `starting_after` to fetch the next page. Filter by creation time with the half-open range `created_after` (inclusive) and `created_before` (exclusive). For a single UTC day, `created_after` is that day at 00:00:00Z and `created_before` is the next day at 00:00:00Z.
   *
   * @example 
   * for await (const message of bird.email.list({ status: "bounced" })) {
   *   console.log(message.id);
   * }
   */
  list(query?: EmailListQuery, options?: RequestOptions): PaginatedPromise<EmailMessage> {
    return this.paginated<EmailMessage>("GET", options, ({ signal, headers }, cursor) =>
      listEmailMessages({ client: this.client, query: { ...query, starting_after: cursor ?? query?.starting_after }, headers, signal }));
  }

  /**
   * Cancel a scheduled email before it sends. Only works while the message's `status` is still `scheduled`. Once it starts sending, or was already canceled, the call returns a conflict error. Canceling does not return consumed scheduled-send quota.
   *
   * @example 
   * await bird.email.cancel("em_abc123");
   */
  cancel(messageId: string, options?: RequestOptions): APIPromise<void> {
    return this.call<void>("POST", options, ({ signal, headers }) =>
      cancelEmailMessage({ client: this.client, path: { message_id: messageId }, headers, signal }));
  }
}
