// Code generated by surface-gen; DO NOT EDIT.
import { deleteEmailTemplate, duplicateEmailTemplate, getEmailTemplate, getEmailTemplatePreview, listEmailTemplates, updateEmailTemplate } from "../generated/sdk.gen.js";
import type { DeleteEmailTemplateData, DuplicateEmailTemplateData, EmailTemplate, EmailTemplatePreview, EmailTemplateSummary, GetEmailTemplateData, GetEmailTemplatePreviewData, ListEmailTemplatesData, UpdateEmailTemplateData } from "../generated/types.gen.js";
import { Resource } from "./base.js";
import type { APIPromise, PaginatedPromise, RequestOptions } from "../core/result.js";

export type { EmailTemplateSummary };
export type { EmailTemplate };
export type { EmailTemplatePreview };
export type EmailTemplatesListQuery = NonNullable<ListEmailTemplatesData["query"]>;
export type EmailTemplatesUpdateParams = NonNullable<UpdateEmailTemplateData["body"]>;
export type EmailTemplatesDuplicateParams = NonNullable<DuplicateEmailTemplateData["body"]>;
export type EmailTemplatesPreviewParams = NonNullable<GetEmailTemplatePreviewData["body"]>;

export class EmailTemplatesResourceBase extends Resource {
  /**
   * List email templates as a cursor page. The list covers both the workspace's own templates and our built-in `system` templates. Filter to one tier with `scope`, and filter further by category, source, theme, or a search across slug, name, and description. A theme narrows the built-in catalog to one of its five visual themes, so naming one returns built-ins alone.
   *
   * @example Find the templates a send can name
   * for await (const tpl of bird.email.templates.list({ scope: "workspace" })) {
   *   console.log(tpl.slug, tpl.name);
   * }
   */
  list(query?: EmailTemplatesListQuery, options?: RequestOptions): PaginatedPromise<EmailTemplateSummary> {
    return this.paginated<EmailTemplateSummary>("GET", options, ({ signal, headers }, cursor) =>
      listEmailTemplates({ client: this.client, query: { ...query, starting_after: cursor ?? query?.starting_after, ending_before: cursor === undefined ? query?.ending_before : undefined }, headers, signal }));
  }

  /**
   * Read one template's metadata: the state of every language it has, the languages it can send today, the draft revision, and its draft and published version IDs. The response omits content; read a version's language to retrieve it. Accepts a workspace template ID (`emt_…`) or a built-in `system` template's `bird_` slug.
   */
  get(templateRef: string, options?: RequestOptions): APIPromise<EmailTemplate> {
    return this.call<EmailTemplate>("GET", options, ({ signal, headers }) =>
      getEmailTemplate({ client: this.client, path: { template_ref: templateRef }, headers, signal }));
  }

  /**
   * Change a template's metadata and draft settings without editing its content. Save content on the draft version. Pass the last-read draft `revision`; a concurrent edit returns a conflict.
   */
  update(templateRef: string, params: EmailTemplatesUpdateParams, options?: RequestOptions): APIPromise<EmailTemplate> {
    return this.call<EmailTemplate>("PATCH", options, ({ signal, headers }) =>
      updateEmailTemplate({ client: this.client, path: { template_ref: templateRef }, body: params, headers, signal }));
  }

  /**
   * Delete a template and every version it holds, freeing its slug for reuse in the workspace. The deletion cannot be undone, and a later send naming the template is rejected. A template a `scheduled` or `accepted` broadcast still references cannot be deleted, and returns a conflict. A scheduled message send using the template does not block the delete, and is rejected with `generation_failure` when it falls due.
   */
  delete(templateRef: string, options?: RequestOptions): APIPromise<void> {
    return this.call<void>("DELETE", options, ({ signal, headers }) =>
      deleteEmailTemplate({ client: this.client, path: { template_ref: templateRef }, headers, signal }));
  }

  /**
   * Copy a workspace or built-in `system` template into a new unpublished template. Its editable draft inherits the source's current content, category, authoring format, and description. Supply `slug` or use the derived `-copy` slug. A slug already in use returns a conflict.
   */
  duplicate(templateRef: string, params: EmailTemplatesDuplicateParams = {}, options?: RequestOptions): APIPromise<EmailTemplate> {
    return this.call<EmailTemplate>("POST", options, ({ signal, headers }) =>
      duplicateEmailTemplate({ client: this.client, path: { template_ref: templateRef }, body: params, headers, signal }));
  }

  /**
   * Render a template with sample values and return the resulting subject, HTML, and plain-text bodies: the personalized email as it will send. Renders the draft by default. Pass `version` to select a published version instead; built-in `system` templates have no versions, so `version` on one returns a validation error. Pass `contact` to fill the personalization from a real contact's record. Sample `parameters` cap at 16 KB serialized. Personalization that is invalid or unsupported returns a validation error naming what to fix. The response also carries `compatibility`: what the HTML uses that mail clients remove, ignore, or render inconsistently, each finding naming the pattern, the line and column it sits on, and what to use instead. Advisory, and the preview renders either way.
   */
  preview(templateRef: string, params: EmailTemplatesPreviewParams = {}, options?: RequestOptions): APIPromise<EmailTemplatePreview> {
    return this.call<EmailTemplatePreview>("POST", options, ({ signal, headers }) =>
      getEmailTemplatePreview({ client: this.client, path: { template_ref: templateRef }, body: params, headers, signal }));
  }
}
