// Code generated by surface-gen; DO NOT EDIT.
import { searchEmailCompetitiveBrands } from "../generated/sdk.gen.js";
import type { EmailCompetitiveBrandSearchResults, SearchEmailCompetitiveBrandsData } from "../generated/types.gen.js";
import { Resource } from "./base.js";
import type { APIPromise, RequestOptions } from "../core/result.js";

export type { EmailCompetitiveBrandSearchResults };
export type EmailCompetitiveBrandsSearchQuery = NonNullable<SearchEmailCompetitiveBrandsData["query"]>;

export class EmailCompetitiveBrandsResource extends Resource {
  /**
   * Search by brand name or sending domain. Each match returns the panel's `brand_id`, which is
different from the `watchlist_brand_id` returned by `email.competitive.watchlist.get`.

API-key calls require Insights preview access for your organization.
   *
   * @example Find a competitor brand
   * // Requires Insights preview access for the organization.
   * const report = await bird.email.competitive.brands.search({ q: "Everlane" });
   * console.log(report.data);
   */
  search(query: EmailCompetitiveBrandsSearchQuery, options?: RequestOptions): APIPromise<EmailCompetitiveBrandSearchResults> {
    return this.call<EmailCompetitiveBrandSearchResults>("GET", options, ({ signal, headers }) =>
      searchEmailCompetitiveBrands({ client: this.client, query, headers, signal }));
  }
}
