// Code generated by surface-gen; DO NOT EDIT.
import { getEmailCompetitiveNotableCampaigns, getEmailCompetitiveWatchlist } from "../generated/sdk.gen.js";
import type { EmailCompetitiveNotableFeed, EmailCompetitiveWatchlist, GetEmailCompetitiveNotableCampaignsData, GetEmailCompetitiveWatchlistData } from "../generated/types.gen.js";
import { Resource } from "./base.js";
import type { APIPromise, RequestOptions } from "../core/result.js";

export type { EmailCompetitiveWatchlist };
export type { EmailCompetitiveNotableFeed };
export type EmailCompetitiveWatchlistGetQuery = NonNullable<GetEmailCompetitiveWatchlistData["query"]>;
export type EmailCompetitiveWatchlistNotableQuery = NonNullable<GetEmailCompetitiveNotableCampaignsData["query"]>;

export class EmailCompetitiveWatchlistResourceBase extends Resource {
  /**
   * Read the complete watchlist report for the requested range. Competitor rows carry
`watchlist_brand_id` values for `email.competitive.watchlist.brands.get` and sampled panel
figures; an unavailable figure is null rather than zero.

API-key calls require Insights preview access for your organization.
   *
   * @example Read watchlist figures without replacing missing values
   * // Requires Insights preview access for the organization.
   * const report = await bird.email.competitive.watchlist.get({ range: 30 });
   * console.log(report.data);
   */
  get(query?: EmailCompetitiveWatchlistGetQuery, options?: RequestOptions): APIPromise<EmailCompetitiveWatchlist> {
    return this.call<EmailCompetitiveWatchlist>("GET", options, ({ signal, headers }) =>
      getEmailCompetitiveWatchlist({ client: this.client, query, headers, signal }));
  }

  /**
   * Returns up to 100 findings across watched brands for the requested range.
A campaign can appear for multiple signals, each with its own evidence.
truncated reports omitted eligible findings; this report has no cursor pages.
Each finding carries the watched-brand and campaign IDs for
`email.competitive.watchlist.brands.campaigns.get`.

API-key calls require Insights preview access for your organization.
   *
   * @example Read notable campaigns
   * // Requires Insights preview access for the organization.
   * const report = await bird.email.competitive.watchlist.notable({ range: 30 });
   * console.log(report);
   */
  notable(query?: EmailCompetitiveWatchlistNotableQuery, options?: RequestOptions): APIPromise<EmailCompetitiveNotableFeed> {
    return this.call<EmailCompetitiveNotableFeed>("GET", options, ({ signal, headers }) =>
      getEmailCompetitiveNotableCampaigns({ client: this.client, query, headers, signal }));
  }
}
