// Code generated by surface-gen; DO NOT EDIT.
import { getEmailCompetitiveBrandCampaign, getEmailCompetitiveBrandCampaigns } from "../generated/sdk.gen.js";
import type { EmailCompetitiveCampaign, GetEmailCompetitiveBrandCampaignData, GetEmailCompetitiveBrandCampaignsData } from "../generated/types.gen.js";
import { Resource } from "./base.js";
import type { APIPromise, PaginatedPromise, RequestOptions } from "../core/result.js";

export type { EmailCompetitiveCampaign };
export type EmailCompetitiveWatchlistBrandsCampaignsListQuery = NonNullable<GetEmailCompetitiveBrandCampaignsData["query"]>;

export class EmailCompetitiveWatchlistBrandsCampaignsResource extends Resource {
  /**
   * Takes a watchlist_brand_id from `email.competitive.watchlist.get`. Returns a
cursor page, default 25 rows and maximum 100. Cursors retain the brand, range
and ordering: next_cursor advances with starting_after; prev_cursor or
refresh_cursor reads preceding rows with ending_before. captured and
promo_rate describe a sample independently of this page. next_cursor controls
continuation; truncated can also describe the sample.

API-key calls require Insights preview access for your organization.
   *
   * @example Iterate campaigns across cursor pages
   * // Requires Insights preview access for the organization.
   * const watchlist = await bird.email.competitive.watchlist.get({ range: 30 });
   * const entry = watchlist.data.find((row) => row.name === "Everlane" && row.watchlist_brand_id);
   * if (!entry?.watchlist_brand_id) throw new Error("Add Everlane to the watchlist first");
   * const watchlistBrandId = entry.watchlist_brand_id;
   * for await (const campaign of bird.email.competitive.watchlist.brands.campaigns.list(watchlistBrandId, { range: 30, limit: 25 })) {
   *   console.log(campaign.id);
   * }
   */
  list(watchlistBrandId: string, query?: EmailCompetitiveWatchlistBrandsCampaignsListQuery, options?: RequestOptions): PaginatedPromise<EmailCompetitiveCampaign> {
    return this.paginated<EmailCompetitiveCampaign>("GET", options, ({ signal, headers }, cursor) =>
      getEmailCompetitiveBrandCampaigns({ client: this.client, path: { watchlist_brand_id: watchlistBrandId }, query: { ...query, starting_after: cursor ?? query?.starting_after, ending_before: cursor === undefined ? query?.ending_before : undefined }, headers, signal }));
  }

  /**
   * Takes a watchlist_brand_id and a campaign_id from
`email.competitive.watchlist.brands.campaigns.list`. campaign_id is text to
preserve its digits. Returns the campaign's figures and nullable creative URL;
a campaign outside that watched brand returns not found.

API-key calls require Insights preview access for your organization.
   *
   * @example Use a campaign ID without converting it to a number
   * // Requires Insights preview access for the organization.
   * const watchlist = await bird.email.competitive.watchlist.get({ range: 30 });
   * const entry = watchlist.data.find((row) => row.name === "Everlane" && row.watchlist_brand_id);
   * if (!entry?.watchlist_brand_id) throw new Error("Add Everlane to the watchlist first");
   * const watchlistBrandId = entry.watchlist_brand_id;
   * const page = await bird.email.competitive.watchlist.brands.campaigns.list(watchlistBrandId, { range: 30, limit: 1 });
   * const campaign = page.data[0];
   * if (!campaign) throw new Error("No captured campaigns");
   * const report = await bird.email.competitive.watchlist.brands.campaigns.get(watchlistBrandId, campaign.id);
   * console.log(report);
   */
  get(watchlistBrandId: string, campaignId: string, options?: RequestOptions): APIPromise<EmailCompetitiveCampaign> {
    return this.call<EmailCompetitiveCampaign>("GET", options, ({ signal, headers }) =>
      getEmailCompetitiveBrandCampaign({ client: this.client, path: { watchlist_brand_id: watchlistBrandId, campaign_id: campaignId }, headers, signal }));
  }
}
