// Code generated by surface-gen; DO NOT EDIT.
import { upsertEmailInboxInsightsDomainMonitoring } from "../generated/sdk.gen.js";
import type { EmailInboxInsightsDomainMonitoringResult, UpsertEmailInboxInsightsDomainMonitoringData } from "../generated/types.gen.js";
import { Resource } from "./base.js";
import type { APIPromise, RequestOptions } from "../core/result.js";

export type { EmailInboxInsightsDomainMonitoringResult };

export class EmailInboxInsightsDomainMonitoringResource extends Resource {
  /**
   * Set up monitoring for the workspace's main verified sending domain. Takes no body.
Existing monitoring returns already_on without changes. Otherwise, the sole verified
domain or the domain that sent the most mail in the last 30 days is enabled; an uncertain choice returns
choice_required, and no verified domains returns no_verified_domains. Only enabled has a
non-null domain. Read the domain list after already_on; ask the user to choose after
choice_required. Reuse an idempotency key for retries of the same setup attempt.

API-key and service-account calls require Insights preview access for your organization.
   *
   * @example Enable automatic monitoring and inspect the outcome
   * // Requires Insights preview access for the organization.
   * const result = await bird.email.inboxInsights.domainMonitoring.upsert();
   * console.log(result.outcome, result.domain);
   */
  upsert(options?: RequestOptions): APIPromise<EmailInboxInsightsDomainMonitoringResult> {
    return this.call<EmailInboxInsightsDomainMonitoringResult>("POST", options, ({ signal, headers }) =>
      upsertEmailInboxInsightsDomainMonitoring({ client: this.client, headers, signal }));
  }
}
