// Code generated by surface-gen; DO NOT EDIT.
import { listEsimDeliveries } from "../generated/sdk.gen.js";
import type { EsimDeliveryList, ListEsimDeliveriesData } from "../generated/types.gen.js";
import { Resource } from "./base.js";
import type { APIPromise, RequestOptions } from "../core/result.js";

export type { EsimDeliveryList };

export class EsimDeliveriesResource extends Resource {
  /**
   * List the install-credential deliveries sent for this eSIM, newest first, with each delivery's status and failure code. Use this to answer "did the traveler get the email or SMS" without having consumed the webhook events.
   */
  list(esimId: string, options?: RequestOptions): APIPromise<EsimDeliveryList> {
    return this.call<EsimDeliveryList>("GET", options, ({ signal, headers }) =>
      listEsimDeliveries({ client: this.client, path: { esim_id: esimId }, headers, signal }));
  }
}
