// Code generated by surface-gen; DO NOT EDIT.
import { createEsimAssignment, getEsimAssignment } from "../generated/sdk.gen.js";
import type { CreateEsimAssignmentData, EsimAssignment, GetEsimAssignmentData } from "../generated/types.gen.js";
import { Resource } from "./base.js";
import type { APIPromise, RequestOptions } from "../core/result.js";

export type { EsimAssignment };
export type EsimAssignmentCreateParams = NonNullable<CreateEsimAssignmentData["body"]>;

export class EsimAssignmentResource extends Resource {
  /**
   * Returns the assigned person. An unassigned eSIM or a resource outside this workspace returns 404.
   */
  get(esimId: string, options?: RequestOptions): APIPromise<EsimAssignment> {
    return this.call<EsimAssignment>("GET", options, ({ signal, headers }) =>
      getEsimAssignment({ client: this.client, path: { esim_id: esimId }, headers, signal }));
  }

  /**
   * Assigns an existing, allocated eSIM to a subscriber in the same workspace. Unavailable profile states return 409. Identification guidance does not gate assignment; customers handle identification collection and compliance. Repeating the same assignment returns its existing record; assigning a different person returns 409. This does not change paid packages, deliver credentials, or grant access to them.
   */
  create(esimId: string, params: EsimAssignmentCreateParams, options?: RequestOptions): APIPromise<EsimAssignment> {
    return this.call<EsimAssignment>("POST", options, ({ signal, headers }) =>
      createEsimAssignment({ client: this.client, path: { esim_id: esimId }, body: params, headers, signal }));
  }
}
