// Code generated by surface-gen; DO NOT EDIT.
import { deleteEsimPackage, getEsimPackage, listEsimPackages } from "../generated/sdk.gen.js";
import type { DeleteEsimPackageData, EsimPackage, EsimPackageList, GetEsimPackageData, ListEsimPackagesData } from "../generated/types.gen.js";
import { Resource } from "./base.js";
import type { APIPromise, RequestOptions } from "../core/result.js";
import type { FetchOutcome } from "../core/http.js";

export type { EsimPackageList };
export type { EsimPackage };
export type EsimPackagesDeleteQuery = NonNullable<DeleteEsimPackageData["query"]>;

export class EsimPackagesResource extends Resource {
  /**
   * Returns the eSIM's data packages with per-zone balances, validity, and status, newest first and in full: an eSIM holds at most package_limit concurrent packages. Balances update as mobile networks report usage; `balance.as_of` tells you how fresh they are.
   */
  list(esimId: string, options?: RequestOptions): APIPromise<EsimPackageList> {
    return this.call<EsimPackageList>("GET", options, ({ signal, headers }) =>
      listEsimPackages({ client: this.client, path: { esim_id: esimId }, headers, signal }));
  }

  /**
   * Returns one data package with its balance, validity, speed class, and status.
   */
  get(esimId: string, packageId: string, options?: RequestOptions): APIPromise<EsimPackage> {
    return this.call<EsimPackage>("GET", options, ({ signal, headers }) =>
      getEsimPackage({ client: this.client, path: { esim_id: esimId, package_id: packageId }, headers, signal }));
  }

  /**
   * Remove a data package from an eSIM, freeing room under its package_limit. DESTRUCTIVE: any remaining balance is forfeited and removal itself never credits anything back; requires acknowledge_balance_forfeit=true when balance remains.
   */
  delete(esimId: string, packageId: string, query?: EsimPackagesDeleteQuery, options?: RequestOptions): APIPromise<void> {
    return this.call<void>("DELETE", options, ({ signal, headers }) =>
      deleteEsimPackage({ client: this.client, path: { esim_id: esimId, package_id: packageId }, query, headers, signal }) as Promise<FetchOutcome<void>>);
  }
}
