// Code generated by surface-gen; DO NOT EDIT.
import { getEsimOffer, getEsimOfferCheckoutOptions, getEsimOfferRecurrence, getEsimOfferRequirements, listEsimOffers } from "../generated/sdk.gen.js";
import type { EsimCheckoutOptions, EsimOffer, EsimOfferRequirements, EsimOfferSummary, EsimRecurringOffer, GetEsimOfferCheckoutOptionsData, GetEsimOfferData, GetEsimOfferRecurrenceData, GetEsimOfferRequirementsData, ListEsimOffersData } from "../generated/types.gen.js";
import { Resource } from "./base.js";
import type { APIPromise, PaginatedPromise, RequestOptions } from "../core/result.js";

export type { EsimOfferSummary };
export type { EsimOffer };
export type { EsimOfferRequirements };
export type { EsimCheckoutOptions };
export type { EsimRecurringOffer };
export type EsimOffersListQuery = NonNullable<ListEsimOffersData["query"]>;

export class EsimOffersResource extends Resource {
  /**
   * List the prepaid travel eSIM offers available to this workspace as a cursor page ({data, next_cursor, ...}). Filter by country (ISO 3166-1 alpha-2) to find offers that cover a destination, or by zone_id for one coverage footprint. Each row carries the offer's pricing (data allowance, validity, and the price billed per provisioned package) and its zone_id; fetch the offer or the zone for the country list.
   */
  list(query?: EsimOffersListQuery, options?: RequestOptions): PaginatedPromise<EsimOfferSummary> {
    return this.paginated<EsimOfferSummary>("GET", options, ({ signal, headers }, cursor) =>
      listEsimOffers({ client: this.client, query: { ...query, starting_after: cursor ?? query?.starting_after, ending_before: cursor === undefined ? query?.ending_before : undefined }, headers, signal }));
  }

  /**
   * Returns one eSIM offer with its pricing and embedded coverage zone.
   */
  get(offerId: string, options?: RequestOptions): APIPromise<EsimOffer> {
    return this.call<EsimOffer>("GET", options, ({ signal, headers }) =>
      getEsimOffer({ client: this.client, path: { offer_id: offerId }, headers, signal }));
  }

  /**
   * Returns a complete JSON Schema for each country in the offer coverage zone. First name, last name, and email are always required, including where no country definition exists. Customers collect and validate information themselves; enable JSON Schema format assertion for email and dates. Bird receives no answers and does not use these schemas to authorize purchase or assignment.
   */
  requirements(offerId: string, options?: RequestOptions): APIPromise<EsimOfferRequirements> {
    return this.call<EsimOfferRequirements>("GET", options, ({ signal, headers }) =>
      getEsimOfferRequirements({ client: this.client, path: { offer_id: offerId }, headers, signal }));
  }

  /**
   * Returns published one-time terms and automatic renewal availability for a new eSIM. Automatic renewal includes its own price and cadence when an eligible mobile network is available. Availability is checked again when purchasing; this read does not reserve a package.
   */
  checkoutOptions(offerId: string, options?: RequestOptions): APIPromise<EsimCheckoutOptions> {
    return this.call<EsimCheckoutOptions>("GET", options, ({ signal, headers }) =>
      getEsimOfferCheckoutOptions({ client: this.client, path: { offer_id: offerId }, headers, signal }));
  }

  /**
   * Returns the published whole-package recurring price and calendar-month or fixed-day cadence. Enrollment additionally checks that the assigned eSIM mobile network supports these terms.
   */
  recurrence(offerId: string, options?: RequestOptions): APIPromise<EsimRecurringOffer> {
    return this.call<EsimRecurringOffer>("GET", options, ({ signal, headers }) =>
      getEsimOfferRecurrence({ client: this.client, path: { offer_id: offerId }, headers, signal }));
  }
}
