// Code generated by surface-gen; DO NOT EDIT.
import { getEsimZone, listEsimZones } from "../generated/sdk.gen.js";
import type { EsimZone, GetEsimZoneData, ListEsimZonesData } from "../generated/types.gen.js";
import { Resource } from "./base.js";
import type { APIPromise, PaginatedPromise, RequestOptions } from "../core/result.js";

export type { EsimZone };
export type EsimZonesListQuery = NonNullable<ListEsimZonesData["query"]>;

export class EsimZonesResource extends Resource {
  /**
   * List the coverage zones eSIM offers sell, as a cursor page ({data, next_cursor, ...}). Each zone carries its authoritative country list. Filter by country (ISO 3166-1 alpha-2) to find zones covering a destination, then list offers by zone_id to see what can be ordered there.
   */
  list(query?: EsimZonesListQuery, options?: RequestOptions): PaginatedPromise<EsimZone> {
    return this.paginated<EsimZone>("GET", options, ({ signal, headers }, cursor) =>
      listEsimZones({ client: this.client, query: { ...query, starting_after: cursor ?? query?.starting_after, ending_before: cursor === undefined ? query?.ending_before : undefined }, headers, signal }));
  }

  /**
   * Returns one coverage zone with its authoritative country list.
   */
  get(zoneId: string, options?: RequestOptions): APIPromise<EsimZone> {
    return this.call<EsimZone>("GET", options, ({ signal, headers }) =>
      getEsimZone({ client: this.client, path: { zone_id: zoneId }, headers, signal }));
  }
}
