// Code generated by surface-gen; DO NOT EDIT.
import { cancelEsimRecurringSubscription, createEsimRecurringSubscription, getEsimRecurringSubscription, listEsimRecurringPeriods, listEsimRecurringSubscriptions } from "../generated/sdk.gen.js";
import type { CancelEsimRecurringSubscriptionData, CreateEsimRecurringSubscriptionData, EsimRecurringPeriod, EsimRecurringSubscription, GetEsimRecurringSubscriptionData, ListEsimRecurringPeriodsData, ListEsimRecurringSubscriptionsData } from "../generated/types.gen.js";
import { Resource } from "./base.js";
import type { APIPromise, PaginatedPromise, RequestOptions } from "../core/result.js";

export type { EsimRecurringSubscription };
export type { EsimRecurringPeriod };
export type EsimRecurringSubscriptionsCreateParams = NonNullable<CreateEsimRecurringSubscriptionData["body"]>;
export type EsimRecurringSubscriptionsListQuery = NonNullable<ListEsimRecurringSubscriptionsData["query"]>;
export type EsimRecurringSubscriptionsPeriodsQuery = NonNullable<ListEsimRecurringPeriodsData["query"]>;

export class EsimRecurringSubscriptionsResource extends Resource {
  /**
   * Purchase the first recurring period on an assigned eSIM. Reuse the required Idempotency-Key and identical request to recover enrollment. Check subscription and period history for payment and delivery outcomes. Changed prices, unfunded renewal, or confirmed delivery failure stop future renewal.
   */
  create(params: EsimRecurringSubscriptionsCreateParams, options?: RequestOptions): APIPromise<EsimRecurringSubscription> {
    return this.call<EsimRecurringSubscription>("POST", options, ({ signal, headers }) =>
      createEsimRecurringSubscription({ client: this.client, body: params, headers: { ...headers, "Idempotency-Key": headers["Idempotency-Key"]! }, signal }));
  }

  /**
   * Returns recurring services for assigned eSIMs in this workspace.
   */
  list(query?: EsimRecurringSubscriptionsListQuery, options?: RequestOptions): PaginatedPromise<EsimRecurringSubscription> {
    return this.paginated<EsimRecurringSubscription>("GET", options, ({ signal, headers }, cursor) =>
      listEsimRecurringSubscriptions({ client: this.client, query: { ...query, starting_after: cursor ?? query?.starting_after, ending_before: cursor === undefined ? query?.ending_before : undefined }, headers, signal }));
  }

  /**
   * Returns the current paid period separately from package delivery and cancellation state.
   */
  get(subscriptionId: string, options?: RequestOptions): APIPromise<EsimRecurringSubscription> {
    return this.call<EsimRecurringSubscription>("GET", options, ({ signal, headers }) =>
      getEsimRecurringSubscription({ client: this.client, path: { subscription_id: subscriptionId }, headers, signal }));
  }

  /**
   * Stops future package renewal at the current paid boundary. A period already committed remains payable. The installed profile and separately purchased packages are preserved.
   */
  cancel(subscriptionId: string, options?: RequestOptions): APIPromise<EsimRecurringSubscription> {
    return this.call<EsimRecurringSubscription>("POST", options, ({ signal, headers }) =>
      cancelEsimRecurringSubscription({ client: this.client, path: { subscription_id: subscriptionId }, headers, signal }));
  }

  /**
   * Returns funded periods with their original charges, confirmed credits, and delivery orders. Unfunded renewals do not create a paid period.
   */
  periods(subscriptionId: string, query?: EsimRecurringSubscriptionsPeriodsQuery, options?: RequestOptions): PaginatedPromise<EsimRecurringPeriod> {
    return this.paginated<EsimRecurringPeriod>("GET", options, ({ signal, headers }, cursor) =>
      listEsimRecurringPeriods({ client: this.client, path: { subscription_id: subscriptionId }, query: { ...query, starting_after: cursor ?? query?.starting_after, ending_before: cursor === undefined ? query?.ending_before : undefined }, headers, signal }));
  }
}
