// Code generated by surface-gen; DO NOT EDIT.
import { deliverEsimCredentials, getEsimCredentials } from "../generated/sdk.gen.js";
import type { DeliverEsimCredentialsData, EsimCredentials, EsimCredentialsDelivery, GetEsimCredentialsData } from "../generated/types.gen.js";
import { Resource } from "./base.js";
import type { APIPromise, RequestOptions } from "../core/result.js";

export type { EsimCredentials };
export type { EsimCredentialsDelivery };
export type EsimCredentialsDeliverParams = NonNullable<DeliverEsimCredentialsData["body"]>;

export class EsimCredentialsResource extends Resource {
  /**
   * Read private installation credentials and device instructions. Requires esim_credentials permission. iOS links and manual details are supported; Android installation links and hosted QR image URLs return null. Returns a conflict for an uninstallable profile and service unavailable when credentials cannot be retrieved.
   */
  get(esimId: string, options?: RequestOptions): APIPromise<EsimCredentials> {
    return this.call<EsimCredentials>("GET", options, ({ signal, headers }) =>
      getEsimCredentials({ client: this.client, path: { esim_id: esimId }, headers, signal }));
  }

  /**
   * Send an eSIM's install credentials to the traveler by email or SMS, in English. Use after purchase or to resend installation details.
   */
  deliver(esimId: string, params: EsimCredentialsDeliverParams, options?: RequestOptions): APIPromise<EsimCredentialsDelivery> {
    return this.call<EsimCredentialsDelivery>("POST", options, ({ signal, headers }) =>
      deliverEsimCredentials({ client: this.client, path: { esim_id: esimId }, body: params, headers, signal }));
  }
}
