// Code generated by surface-gen; DO NOT EDIT.
import { cancelEsimOrder, createEsimOrder, getEsimOrder, listEsimOrders } from "../generated/sdk.gen.js";
import type { CancelEsimOrderData, CreateEsimOrderData, EsimOrder, GetEsimOrderData, ListEsimOrdersData } from "../generated/types.gen.js";
import { Resource } from "./base.js";
import type { APIPromise, PaginatedPromise, RequestOptions } from "../core/result.js";

export type { EsimOrder };
export type EsimOrdersCreateParams = NonNullable<CreateEsimOrderData["body"]>;
export type EsimOrdersListQuery = NonNullable<ListEsimOrdersData["query"]>;

export class EsimOrdersResource extends Resource {
  /**
   * Purchase an eSIM data package. Without esim_id a new eSIM is provisioned with the package; with esim_id the package is added to that eSIM. The order locks the offer's price at creation. Inspect status even on HTTP 201: the order can be completed or failed. On HTTP 202, poll until completed or failed. Omit delivery; after completion use `esim.credentials.deliver` to send install credentials to the traveler.
   */
  create(params: EsimOrdersCreateParams, options?: RequestOptions): APIPromise<EsimOrder> {
    return this.call<EsimOrder>("POST", options, ({ signal, headers }) =>
      createEsimOrder({ client: this.client, body: params, headers, signal }));
  }

  /**
   * Returns the workspace's orders as a cursor-paginated list, newest first. Filter by `status` to find in-flight or failed purchases, by `esim_id` for one eSIM's purchase history, or by `mode` to separate test purchases from real ones. Test orders are listed alongside real ones by default, each carrying its own `mode`.
   */
  list(query?: EsimOrdersListQuery, options?: RequestOptions): PaginatedPromise<EsimOrder> {
    return this.paginated<EsimOrder>("GET", options, ({ signal, headers }, cursor) =>
      listEsimOrders({ client: this.client, query: { ...query, starting_after: cursor ?? query?.starting_after, ending_before: cursor === undefined ? query?.ending_before : undefined }, headers, signal }));
  }

  /**
   * Returns one order. Poll until `status` is `completed` or `failed`; a completed order names the eSIM and package it produced.
   */
  get(orderId: string, options?: RequestOptions): APIPromise<EsimOrder> {
    return this.call<EsimOrder>("GET", options, ({ signal, headers }) =>
      getEsimOrder({ client: this.client, path: { order_id: orderId }, headers, signal }));
  }

  /**
   * Cancel an order waiting for funds. Inspect the returned status: an unfunded order fails with failure_code canceled; an initial recurring order whose payment was recovered continues delivery with future renewal stopped. One-time orders already funded return a conflict.
   */
  cancel(orderId: string, options?: RequestOptions): APIPromise<EsimOrder> {
    return this.call<EsimOrder>("POST", options, ({ signal, headers }) =>
      cancelEsimOrder({ client: this.client, path: { order_id: orderId }, headers, signal }));
  }
}
