// Code generated by surface-gen; DO NOT EDIT.
import { createEsimInstallLink, deleteEsimInstallLink } from "../generated/sdk.gen.js";
import type { CreateEsimInstallLinkData, DeleteEsimInstallLinkData, EsimInstallLink } from "../generated/types.gen.js";
import { Resource } from "./base.js";
import type { APIPromise, RequestOptions } from "../core/result.js";

export type { EsimInstallLink };

export class EsimInstallLinksResource extends Resource {
  /**
   * Create a private hosted installation link for one eSIM. The recipient needs no Bird login. Links expire after seven days; earlier links remain valid until expiry or revocation. Requires esim_credentials permission. Returns 501 when new hosted links are unavailable.
   */
  create(esimId: string, options?: RequestOptions): APIPromise<EsimInstallLink> {
    return this.call<EsimInstallLink>("POST", options, ({ signal, headers }) =>
      createEsimInstallLink({ client: this.client, path: { esim_id: esimId }, headers, signal }));
  }

  /**
   * Revoke a hosted install link so its url stops installing the eSIM. Use it when a link went to the wrong person. Already-revoked and expired links succeed. Requires the esim_credentials scope.
   */
  delete(esimId: string, installLinkId: string, options?: RequestOptions): APIPromise<void> {
    return this.call<void>("DELETE", options, ({ signal, headers }) =>
      deleteEsimInstallLink({ client: this.client, path: { esim_id: esimId, install_link_id: installLinkId }, headers, signal }));
  }
}
