// Code generated by surface-gen; DO NOT EDIT.
import { createEsimSubscriber, getEsimSubscriber, listEsimSubscribers } from "../generated/sdk.gen.js";
import type { CreateEsimSubscriberData, EsimSubscriber, GetEsimSubscriberData, ListEsimSubscribersData } from "../generated/types.gen.js";
import { Resource } from "./base.js";
import type { APIPromise, PaginatedPromise, RequestOptions } from "../core/result.js";

export type { EsimSubscriber };
export type EsimSubscribersCreateParams = NonNullable<CreateEsimSubscriberData["body"]>;
export type EsimSubscribersListQuery = NonNullable<ListEsimSubscribersData["query"]>;

export class EsimSubscribersResource extends Resource {
  /**
   * Create or return a subscriber for a workspace contact. Requires email_marketing read and esim write. Does not buy or assign an eSIM. The association blocks contact deletion and cannot currently be removed, including after the service ends.
   */
  create(params: EsimSubscribersCreateParams, options?: RequestOptions): APIPromise<EsimSubscriber> {
    return this.call<EsimSubscriber>("POST", options, ({ signal, headers }) =>
      createEsimSubscriber({ client: this.client, body: params, headers, signal }));
  }

  /**
   * Returns person references in this workspace, newest first. Filter by contact_id to find an existing subscriber.
   */
  list(query?: EsimSubscribersListQuery, options?: RequestOptions): PaginatedPromise<EsimSubscriber> {
    return this.paginated<EsimSubscriber>("GET", options, ({ signal, headers }, cursor) =>
      listEsimSubscribers({ client: this.client, query: { ...query, starting_after: cursor ?? query?.starting_after, ending_before: cursor === undefined ? query?.ending_before : undefined }, headers, signal }));
  }

  /**
   * Returns the contact reference for a subscriber in this workspace. Contact details remain available through Contacts with its separate permissions.
   */
  get(subscriberId: string, options?: RequestOptions): APIPromise<EsimSubscriber> {
    return this.call<EsimSubscriber>("GET", options, ({ signal, headers }) =>
      getEsimSubscriber({ client: this.client, path: { subscriber_id: subscriberId }, headers, signal }));
  }
}
