// Code generated by surface-gen; DO NOT EDIT.
import { createEmailLookup, createPhoneNumberLookup } from "../generated/sdk.gen.js";
import type { CreateEmailLookupData, CreatePhoneNumberLookupData, EmailLookup, PhoneNumberLookup } from "../generated/types.gen.js";
import { Resource } from "./base.js";
import type { APIPromise, RequestOptions } from "../core/result.js";

export type { PhoneNumberLookup };
export type { EmailLookup };
export type LookupPhoneNumberParams = NonNullable<CreatePhoneNumberLookupData["body"]>;
export type LookupEmailParams = NonNullable<CreateEmailLookupData["body"]>;

export class LookupResource extends Resource {
  /**
   * Create a lookup for a phone number's networks, porting state, country, and line type. Pass `type` to request separately billed `classification`, `porting`, `presence`, `roaming`, `sim_swap`, or `score` blocks. Each block reports its own status, and only blocks with an `ok` status add a charge; the lookup does not contact the number.
   *
   * @example Look up a number, buying two extra blocks
   * const answer = await bird.lookup.phoneNumber({
   *   phone_number: "+31612345678",
   *   type: ["classification", "score"],
   * });
   * console.log(answer.country_code, answer.line_type);
   * // Only a block whose status is ok carries a value, and only that one is billed.
   * if (answer.score?.status === "ok") console.log(answer.score.value);
   */
  phoneNumber(params: LookupPhoneNumberParams, options?: RequestOptions): APIPromise<PhoneNumberLookup> {
    return this.call<PhoneNumberLookup>("POST", options, ({ signal, headers }) =>
      createPhoneNumberLookup({ client: this.client, body: params, headers, signal }));
  }

  /**
   * Create a deliverability lookup for one email address. Returns `result`, `delivery_confidence`, address `flags`, an undeliverable `reason`, and `did_you_mean` when a correction is available. Treat unknown `result` and `reason` values as valid additions and use `delivery_confidence` as the fallback; each completed lookup incurs the same charge.
   *
   * @example Check whether an address is worth sending to
   * const answer = await bird.lookup.email({ email: "aisha.khan@example.com" });
   * // result is an open vocabulary; delivery_confidence is always comparable.
   * console.log(answer.result, answer.delivery_confidence);
   */
  email(params: LookupEmailParams, options?: RequestOptions): APIPromise<EmailLookup> {
    return this.call<EmailLookup>("POST", options, ({ signal, headers }) =>
      createEmailLookup({ client: this.client, body: params, headers, signal }));
  }
}
