// Code generated by surface-gen; DO NOT EDIT.
import { createNumbersOrder, getNumbersOrder, listNumbersOrders } from "../generated/sdk.gen.js";
import type { CreateNumbersOrderData, GetNumbersOrderData, ListNumbersOrdersData, NumbersOrder } from "../generated/types.gen.js";
import { Resource } from "./base.js";
import type { APIPromise, PaginatedPromise, RequestOptions } from "../core/result.js";

export type { NumbersOrder };
export type NumbersOrdersCreateParams = NonNullable<CreateNumbersOrderData["body"]>;
export type NumbersOrdersListQuery = NonNullable<ListNumbersOrdersData["query"]>;

export class NumbersOrdersResource extends Resource {
  /**
   * Buys a number and starts its monthly charge. Most orders settle inline; one waiting on a carrier comes back pending and is followed with `numbers.orders.get`. A setup fee already taken is not refunded if the order then fails.
   *
   * @example Buy a number
   * const order = await bird.numbers.orders.create({ number: "+447700900201" });
   * // Most orders finish inside the request. One that has to wait on a carrier
   * // comes back without a number_id. Poll it until it is completed or failed.
   * if (order.status === "completed") {
   *   console.log("allocated as", order.number_id);
   * } else {
   *   console.log("still", order.status, "; poll", order.id);
   * }
   */
  create(params: NumbersOrdersCreateParams, options?: RequestOptions): APIPromise<NumbersOrder> {
    return this.call<NumbersOrder>("POST", options, ({ signal, headers }) =>
      createNumbersOrder({ client: this.client, body: params, headers, signal }));
  }

  /**
   * Pages the workspace's purchase attempts, newest first, filtered by status. An order outlives its attempt, so a failure stays readable with the reason it carried.
   *
   * @example Find the purchases that did not complete
   * const page = await bird.numbers.orders.list({ status: "failed" });
   * for (const order of page.data) {
   *   console.log(order.number, order.failure_reason ?? "");
   * }
   */
  list(query?: NumbersOrdersListQuery, options?: RequestOptions): PaginatedPromise<NumbersOrder> {
    return this.paginated<NumbersOrder>("GET", options, ({ signal, headers }, cursor) =>
      listNumbersOrders({ client: this.client, query: { ...query, starting_after: cursor ?? query?.starting_after }, headers, signal }));
  }

  /**
   * Reads one order's current state, and the number it produced once completed. This is the poll for an order that came back pending.
   *
   * @example Poll an order that did not finish inline
   * const order = await bird.numbers.orders.get("nor_01krdgeqcxet5s7t44vh8rt9mg");
   * // failure_reason says what went wrong, and only ever on a failed order.
   * console.log(order.status, order.failure_reason ?? "");
   */
  get(orderId: string, options?: RequestOptions): APIPromise<NumbersOrder> {
    return this.call<NumbersOrder>("GET", options, ({ signal, headers }) =>
      getNumbersOrder({ client: this.client, path: { order_id: orderId }, headers, signal }));
  }
}
