// Code generated by surface-gen; DO NOT EDIT.
import { getAvailableNumber, listAvailableNumbers } from "../generated/sdk.gen.js";
import type { AvailableNumber, GetAvailableNumberData, ListAvailableNumbersData } from "../generated/types.gen.js";
import { Resource } from "./base.js";
import type { APIPromise, PaginatedPromise, RequestOptions } from "../core/result.js";

export type { AvailableNumber };
export type NumbersAvailableListQuery = NonNullable<ListAvailableNumbersData["query"]>;

export class NumbersAvailableResource extends Resource {
  /**
   * Searches one country's numbers on sale. Our own inventory answers first and pages; the last page can carry a live carrier snapshot, so a number seen here may be gone by the time it is ordered.
   *
   * @example Find a number to buy in one country
   * // The search is always country-scoped, so country_code is required.
   * const page = await bird.numbers.available.list({
   *   country_code: "GB",
   *   capabilities: ["sms", "voice"],
   * });
   * for (const candidate of page.data) {
   *   console.log(candidate.number, candidate.number_type);
   * }
   */
  list(query: NumbersAvailableListQuery, options?: RequestOptions): PaginatedPromise<AvailableNumber> {
    return this.paginated<AvailableNumber>("GET", options, ({ signal, headers }, cursor) =>
      listAvailableNumbers({ client: this.client, query: { ...query, starting_after: cursor ?? query?.starting_after }, headers, signal }));
  }

  /**
   * Re-checks one number from `numbers.available.list` against the carrier, so a stale search result is caught before it is ordered.
   *
   * @example Check one number is still for sale
   * // A number a carrier supplies is only on sale while the carrier still has it,
   * // so a 404 here means someone else took it.
   * const candidate = await bird.numbers.available.get("+447700900201");
   * console.log(candidate.country_code, candidate.capabilities);
   */
  get(number: string, options?: RequestOptions): APIPromise<AvailableNumber> {
    return this.call<AvailableNumber>("GET", options, ({ signal, headers }) =>
      getAvailableNumber({ client: this.client, path: { number: number }, headers, signal }));
  }
}
