// Code generated by surface-gen; DO NOT EDIT.
import { getWorkspaceNumber, listWorkspaceNumbers, releaseWorkspaceNumber, updateWorkspaceNumber } from "../generated/sdk.gen.js";
import type { GetWorkspaceNumberData, ListWorkspaceNumbersData, Number, ReleaseWorkspaceNumberData, UpdateWorkspaceNumberData } from "../generated/types.gen.js";
import { Resource } from "./base.js";
import type { APIPromise, PaginatedPromise, RequestOptions } from "../core/result.js";

export type { Number };
export type NumbersListQuery = NonNullable<ListWorkspaceNumbersData["query"]>;
export type NumbersUpdateParams = NonNullable<UpdateWorkspaceNumberData["body"]>;

export class NumbersResourceBase extends Resource {
  /**
   * Pages the numbers allocated to the workspace, dedicated and shared alike. Narrows on country, type, prefix and capability, so one number is reached without walking every page.
   *
   * @example List the numbers allocated to you
   * for await (const allocated of bird.numbers.list({ country_code: "GB" })) {
   *   // kind distinguishes a number you bought from one Bird manages.
   *   console.log(allocated.number, allocated.kind, allocated.status);
   * }
   */
  list(query?: NumbersListQuery, options?: RequestOptions): PaginatedPromise<Number> {
    return this.paginated<Number>("GET", options, ({ signal, headers }, cursor) =>
      listWorkspaceNumbers({ client: this.client, query: { ...query, starting_after: cursor ?? query?.starting_after, ending_before: cursor === undefined ? query?.ending_before : undefined }, headers, signal }));
  }

  /**
   * Reads one allocated number by the id `numbers.list` returns. Carries its status and, where a country demands ownership paperwork, what is still outstanding on it.
   *
   * @example Read one number allocated to you
   * const allocated = await bird.numbers.get("nda_01krdgeqcxet5s7t44vh8rt9mg");
   * // A country that asks for ownership paperwork answers here; most answer null.
   * console.log(allocated.status, allocated.ownership ?? "no paperwork required");
   */
  get(numberId: string, options?: RequestOptions): APIPromise<Number> {
    return this.call<Number>("GET", options, ({ signal, headers }) =>
      getWorkspaceNumber({ client: this.client, path: { number_id: numberId }, headers, signal }));
  }

  /**
   * Set the name or your own reference on an allocated number. Omit a field to preserve it, or send null to clear it. Applies to dedicated and shared numbers.
   *
   * @example Name a number and add your own reference
   * const allocated = await bird.numbers.update("nda_01krdgeqcxet5s7t44vh8rt9mg", {
   *   name: "Support line",
   *   reference: "STORE-042",
   * });
   * console.log(allocated.name, allocated.reference);
   */
  update(numberId: string, params: NumbersUpdateParams = {}, options?: RequestOptions): APIPromise<Number> {
    return this.call<Number>("PATCH", options, ({ signal, headers }) =>
      updateWorkspaceNumber({ client: this.client, path: { number_id: numberId }, body: params, headers, signal }));
  }

  /**
   * Gives a dedicated number back and stops its monthly charge. Irreversible: the number leaves the workspace and the channels built on it stop sending. A shared number cannot be released.
   *
   * @example Give a dedicated number back
   * // Releasing stops the monthly charge and the number stops working for you.
   * // Only a dedicated number can be released; a shared one answers E14002.
   * await bird.numbers.release("nda_01krdgeqcxet5s7t44vh8rt9mg");
   */
  release(numberId: string, options?: RequestOptions): APIPromise<void> {
    return this.call<void>("DELETE", options, ({ signal, headers }) =>
      releaseWorkspaceNumber({ client: this.client, path: { number_id: numberId }, headers, signal }));
  }
}
