// Code generated by surface-gen; DO NOT EDIT.
import { getPreference, listPreferences } from "../generated/sdk.gen.js";
import type { GetPreferenceData, ListPreferencesData, Preference } from "../generated/types.gen.js";
import { Resource } from "./base.js";
import type { APIPromise, PaginatedPromise, RequestOptions } from "../core/result.js";

export type { Preference };
export type PreferencesListQuery = NonNullable<ListPreferencesData["query"]>;

export class PreferencesResourceBase extends Resource {
  /**
   * List the workspace's stated messaging preferences (consent grants and opt-outs) as a cursor page. Filter by channel, and by handle within a channel, to look up one person before messaging them.
   *
   * @example List stated preferences for a channel
   * for await (const preference of bird.preferences.list({ channel: "sms" })) {
   *   console.log(preference.handle, preference.status);
   * }
   */
  list(query?: PreferencesListQuery, options?: RequestOptions): PaginatedPromise<Preference> {
    return this.paginated<Preference>("GET", options, ({ signal, headers }, cursor) =>
      listPreferences({ client: this.client, query: { ...query, starting_after: cursor ?? query?.starting_after }, headers, signal }));
  }

  /**
   * Read one recorded preference by ID: the channel and handle it is about, whether it grants or revokes, how much traffic it covers, and where the statement came from.
   *
   * @example Read one preference
   * const preference = await bird.preferences.get(
   *   "prf_01krdgeqcxet5s7t44vh8rt9mg",
   * );
   * console.log(preference.status, preference.coverage);
   */
  get(preferenceId: string, options?: RequestOptions): APIPromise<Preference> {
    return this.call<Preference>("GET", options, ({ signal, headers }) =>
      getPreference({ client: this.client, path: { preference_id: preferenceId }, headers, signal }));
  }
}
