// Code generated by surface-gen; DO NOT EDIT.
import { getSmsMessage, listSmsMessageEvents, listSmsMessages } from "../generated/sdk.gen.js";
import type { GetSmsMessageData, ListSmsMessageEventsData, ListSmsMessagesData, SmsEventList, SmsMessage } from "../generated/types.gen.js";
import { Resource } from "./base.js";
import type { APIPromise, PaginatedPromise, RequestOptions } from "../core/result.js";

export type { SmsMessage };
export type { SmsEventList };
export type SmsListQuery = NonNullable<ListSmsMessagesData["query"]>;
export type SmsListEventsQuery = NonNullable<ListSmsMessageEventsData["query"]>;

export class SmsResourceBase extends Resource {
  /**
   * Get one SMS message by ID: its current delivery status, segment breakdown, cost, and failure detail if it failed.
   *
   * @example Read a message back
   * const msg = await bird.sms.get("sms_abc123");
   * msg.status; // "accepted" | "delivered" | …
   */
  get(messageId: string, options?: RequestOptions): APIPromise<SmsMessage> {
    return this.call<SmsMessage>("GET", options, ({ signal, headers }) =>
      getSmsMessage({ client: this.client, path: { message_id: messageId }, headers, signal }));
  }

  /**
   * List SMS messages, newest first, as a cursor page (`data`, `next_cursor`). Pass `next_cursor` back as `starting_after` to fetch the next page. Filter by direction, status, category, recipient, sender, or tag.
   *
   * @example Iterate outbound messages
   * for await (const msg of bird.sms.list({ direction: "outbound" })) {
   *   console.log(msg.id, msg.status);
   * }
   */
  list(query?: SmsListQuery, options?: RequestOptions): PaginatedPromise<SmsMessage> {
    return this.paginated<SmsMessage>("GET", options, ({ signal, headers }, cursor) =>
      listSmsMessages({ client: this.client, query: { ...query, starting_after: cursor ?? query?.starting_after }, headers, signal }));
  }

  /**
   * The lifecycle event timeline for one SMS, oldest first: what happened to it and when. Filter with `type` (for example `sms.delivered`) to keep one kind of event. Use `sms.get` for the message's current state and `sms.list` to find its ID.
   *
   * @example Read one message's lifecycle timeline
   * const events = await bird.sms.listEvents("sms_abc123");
   * for (const event of events.data ?? []) {
   *   console.log(event.type, event.occurred_at);
   * }
   */
  listEvents(messageId: string, query?: SmsListEventsQuery, options?: RequestOptions): APIPromise<SmsEventList> {
    return this.call<SmsEventList>("GET", options, ({ signal, headers }) =>
      listSmsMessageEvents({ client: this.client, path: { message_id: messageId }, query, headers, signal }));
  }
}
