// Code generated by surface-gen; DO NOT EDIT.
import { getSmsStatsByCarrier, getSmsStatsByCategory, getSmsStatsByCountry, getSmsStatsByErrorCode, getSmsStatsByOriginator, getSmsStatsByStatus, getSmsStatsByTag, getSmsStatsDaily, getSmsStatsHourly, getSmsStatsSummary } from "../generated/sdk.gen.js";
import type { GetSmsStatsByCarrierData, GetSmsStatsByCategoryData, GetSmsStatsByCountryData, GetSmsStatsByErrorCodeData, GetSmsStatsByOriginatorData, GetSmsStatsByStatusData, GetSmsStatsByTagData, GetSmsStatsDailyData, GetSmsStatsHourlyData, GetSmsStatsSummaryData, SmsStatsByCarrierResponse, SmsStatsByCategoryResponse, SmsStatsByCountryResponse, SmsStatsByErrorCodeResponse, SmsStatsByOriginatorResponse, SmsStatsByStatusResponse, SmsStatsByTagResponse, SmsStatsResponse, SmsStatsSummary } from "../generated/types.gen.js";
import { Resource } from "./base.js";
import type { APIPromise, RequestOptions } from "../core/result.js";

export type { SmsStatsSummary };
export type { SmsStatsResponse };
export type { SmsStatsByCountryResponse };
export type { SmsStatsByCarrierResponse };
export type { SmsStatsByCategoryResponse };
export type { SmsStatsByOriginatorResponse };
export type { SmsStatsByStatusResponse };
export type { SmsStatsByErrorCodeResponse };
export type { SmsStatsByTagResponse };
export type SmsStatsSummaryQuery = NonNullable<GetSmsStatsSummaryData["query"]>;
export type SmsStatsDailyQuery = NonNullable<GetSmsStatsDailyData["query"]>;
export type SmsStatsHourlyQuery = NonNullable<GetSmsStatsHourlyData["query"]>;
export type SmsStatsByCountryQuery = NonNullable<GetSmsStatsByCountryData["query"]>;
export type SmsStatsByCarrierQuery = NonNullable<GetSmsStatsByCarrierData["query"]>;
export type SmsStatsByCategoryQuery = NonNullable<GetSmsStatsByCategoryData["query"]>;
export type SmsStatsByOriginatorQuery = NonNullable<GetSmsStatsByOriginatorData["query"]>;
export type SmsStatsByStatusQuery = NonNullable<GetSmsStatsByStatusData["query"]>;
export type SmsStatsByErrorCodeQuery = NonNullable<GetSmsStatsByErrorCodeData["query"]>;
export type SmsStatsByTagQuery = NonNullable<GetSmsStatsByTagData["query"]>;

export class SmsStatsResourceBase extends Resource {
  /**
   * Aggregate SMS KPIs for one period: accepted, sent, delivered, undelivered, failed, rejected and expired counts, the derived delivery and failure rates, and latency percentiles. The `from` and `to` values are both YYYY-MM-DD days or both RFC 3339 instants (hour grain). Add `compare=previous_period` for deltas against the preceding window. For a per-day or per-hour series use `sms.stats.daily` or `sms.stats.hourly`.
   *
   * @example Aggregate KPIs for a window
   * const summary = await bird.sms.stats.summary({
   *   from: "2026-05-01", // both calendar days for a day window, or
   *   to: "2026-05-31", //   both RFC 3339 instants for an hour window
   * });
   * console.log(summary.delivery, summary.latency);
   */
  summary(query?: SmsStatsSummaryQuery, options?: RequestOptions): APIPromise<SmsStatsSummary> {
    return this.call<SmsStatsSummary>("GET", options, ({ signal, headers }) =>
      getSmsStatsSummary({ client: this.client, query, headers, signal }));
  }

  /**
   * One row of SMS lifecycle counts per calendar day, for charts and trend lines. The window is at most 365 days; set `timezone` to get local calendar days instead of UTC. Rates and latency percentiles are whole-window figures, so read those from `sms.stats.summary`.
   *
   * @example One row per calendar day
   * const stats = await bird.sms.stats.daily({ from: "2026-05-01", to: "2026-05-31" });
   * for (const point of stats.data ?? []) {
   *   console.log(point.bucket, point.delivery);
   * }
   */
  daily(query?: SmsStatsDailyQuery, options?: RequestOptions): APIPromise<SmsStatsResponse> {
    return this.call<SmsStatsResponse>("GET", options, ({ signal, headers }) =>
      getSmsStatsDaily({ client: this.client, query, headers, signal }));
  }

  /**
   * One row of SMS lifecycle counts per hour, for inspecting send rate and deliverability inside a single day. The window is at most 30 days (720 rows) and both bounds round down to the hour. For longer ranges use `sms.stats.daily`.
   *
   * @example One row per hour, up to 30 days
   * const stats = await bird.sms.stats.hourly({
   *   from: "2026-05-30T00:00:00Z",
   *   to: "2026-05-31T00:00:00Z",
   * });
   * for (const point of stats.data ?? []) {
   *   console.log(point.bucket, point.delivery);
   * }
   */
  hourly(query?: SmsStatsHourlyQuery, options?: RequestOptions): APIPromise<SmsStatsResponse> {
    return this.call<SmsStatsResponse>("GET", options, ({ signal, headers }) =>
      getSmsStatsHourly({ client: this.client, query, headers, signal }));
  }

  /**
   * SMS delivery and latency stats grouped by destination country, ranked by the `sort` metric (default `accepted`) and capped by `limit` (default 50, maximum 200). Use it to find where delivery is worst before drilling into `sms.stats.by_error_code`.
   *
   * @example Find where delivery is worst
   * const stats = await bird.sms.stats.byCountry({
   *   from: "2026-05-01",
   *   to: "2026-05-31",
   *   sort: "delivery_rate",
   * });
   * for (const row of stats.data ?? []) {
   *   console.log(row.country, row.delivery);
   * }
   */
  byCountry(query?: SmsStatsByCountryQuery, options?: RequestOptions): APIPromise<SmsStatsByCountryResponse> {
    return this.call<SmsStatsByCountryResponse>("GET", options, ({ signal, headers }) =>
      getSmsStatsByCountry({ client: this.client, query, headers, signal }));
  }

  /**
   * SMS delivery and latency stats grouped by the carrier that handled the message, ranked by the `sort` metric (default `accepted`) and capped by `limit` (default 50, maximum 200). Use it to compare delivery performance across carriers.
   *
   * @example Compare delivery across carriers
   * const stats = await bird.sms.stats.byCarrier({ from: "2026-05-01", to: "2026-05-31" });
   * for (const row of stats.data ?? []) {
   *   console.log(row.carrier, row.delivery);
   * }
   */
  byCarrier(query?: SmsStatsByCarrierQuery, options?: RequestOptions): APIPromise<SmsStatsByCarrierResponse> {
    return this.call<SmsStatsByCarrierResponse>("GET", options, ({ signal, headers }) =>
      getSmsStatsByCarrier({ client: this.client, query, headers, signal }));
  }

  /**
   * SMS delivery and latency stats grouped by the category you sent under, ranked by the `sort` metric (default `accepted`) and capped by `limit` (default 50, maximum 200).
   *
   * @example Split a window by category
   * const stats = await bird.sms.stats.byCategory({ from: "2026-05-01", to: "2026-05-31" });
   * for (const row of stats.data ?? []) {
   *   console.log(row.category, row.delivery);
   * }
   */
  byCategory(query?: SmsStatsByCategoryQuery, options?: RequestOptions): APIPromise<SmsStatsByCategoryResponse> {
    return this.call<SmsStatsByCategoryResponse>("GET", options, ({ signal, headers }) =>
      getSmsStatsByCategory({ client: this.client, query, headers, signal }));
  }

  /**
   * SMS delivery and latency stats grouped by originator, the sender address messages went out from, ranked by the `sort` metric (default `accepted`) and capped by `limit` (default 50, maximum 200). Use it to compare how your senders perform.
   *
   * @example Compare how each sender performs
   * const stats = await bird.sms.stats.byOriginator({ from: "2026-05-01", to: "2026-05-31" });
   * for (const row of stats.data ?? []) {
   *   console.log(row.originator, row.delivery);
   * }
   */
  byOriginator(query?: SmsStatsByOriginatorQuery, options?: RequestOptions): APIPromise<SmsStatsByOriginatorResponse> {
    return this.call<SmsStatsByOriginatorResponse>("GET", options, ({ signal, headers }) =>
      getSmsStatsByOriginator({ client: this.client, query, headers, signal }));
  }

  /**
   * How many messages ended the period in each lifecycle status: accepted, sent, delivered, undelivered, failed, rejected, expired, ordered by count. The "where did my messages end up" view, suitable for a status-distribution chart.
   *
   * @example Where the window's messages ended up
   * const stats = await bird.sms.stats.byStatus({ from: "2026-05-01", to: "2026-05-31" });
   * for (const row of stats.data ?? []) {
   *   console.log(row.status, row.count);
   * }
   */
  byStatus(query?: SmsStatsByStatusQuery, options?: RequestOptions): APIPromise<SmsStatsByStatusResponse> {
    return this.call<SmsStatsByStatusResponse>("GET", options, ({ signal, headers }) =>
      getSmsStatsByStatus({ client: this.client, query, headers, signal }));
  }

  /**
   * SMS stats grouped by our normalized failure reason, which answers which reasons are driving your failures. The grouping key is the same value as the `error_code` filter on `sms.list`, so a row joins straight to the messages behind it. Ranked by the `sort` metric (default `failed`) and capped by `limit`.
   *
   * @example Which reasons drive failures
   * const stats = await bird.sms.stats.byErrorCode({ from: "2026-05-01", to: "2026-05-31" });
   * for (const row of stats.data ?? []) {
   *   // The same value as the error_code filter on bird.sms.list.
   *   console.log(row.error_code, row.delivery);
   * }
   */
  byErrorCode(query?: SmsStatsByErrorCodeQuery, options?: RequestOptions): APIPromise<SmsStatsByErrorCodeResponse> {
    return this.call<SmsStatsByErrorCodeResponse>("GET", options, ({ signal, headers }) =>
      getSmsStatsByErrorCode({ client: this.client, query, headers, signal }));
  }

  /**
   * SMS delivery and latency stats grouped by tag (`name:value`), ranked by the `sort` metric (default `accepted`) and capped by `limit` (default 50, maximum 200). Only tagged messages appear, and one carrying several tags counts once under each, so rows do not sum to the period total.
   *
   * @example Compare campaigns and segments
   * const stats = await bird.sms.stats.byTag({ from: "2026-05-01", to: "2026-05-31" });
   * for (const row of stats.data ?? []) {
   *   // A message carrying several tags counts once under each, so rows do not sum
   *   // to the period total.
   *   console.log(row.tag, row.delivery);
   * }
   */
  byTag(query?: SmsStatsByTagQuery, options?: RequestOptions): APIPromise<SmsStatsByTagResponse> {
    return this.call<SmsStatsByTagResponse>("GET", options, ({ signal, headers }) =>
      getSmsStatsByTag({ client: this.client, query, headers, signal }));
  }
}
