// Code generated by surface-gen; DO NOT EDIT.
import { getSmsInboundStatsByCountry, getSmsInboundStatsByNumber, getSmsInboundStatsByOperator, getSmsInboundStatsDaily, getSmsInboundStatsHourly, getSmsInboundStatsSummary } from "../generated/sdk.gen.js";
import type { GetSmsInboundStatsByCountryData, GetSmsInboundStatsByNumberData, GetSmsInboundStatsByOperatorData, GetSmsInboundStatsDailyData, GetSmsInboundStatsHourlyData, GetSmsInboundStatsSummaryData, SmsInboundStatsByCountryResponse, SmsInboundStatsByNumberResponse, SmsInboundStatsByOperatorResponse, SmsInboundStatsResponse, SmsInboundStatsSummaryResponse } from "../generated/types.gen.js";
import { Resource } from "./base.js";
import type { APIPromise, RequestOptions } from "../core/result.js";

export type { SmsInboundStatsSummaryResponse };
export type { SmsInboundStatsResponse };
export type { SmsInboundStatsByCountryResponse };
export type { SmsInboundStatsByOperatorResponse };
export type { SmsInboundStatsByNumberResponse };
export type SmsStatsInboundSummaryQuery = NonNullable<GetSmsInboundStatsSummaryData["query"]>;
export type SmsStatsInboundDailyQuery = NonNullable<GetSmsInboundStatsDailyData["query"]>;
export type SmsStatsInboundHourlyQuery = NonNullable<GetSmsInboundStatsHourlyData["query"]>;
export type SmsStatsInboundByCountryQuery = NonNullable<GetSmsInboundStatsByCountryData["query"]>;
export type SmsStatsInboundByOperatorQuery = NonNullable<GetSmsInboundStatsByOperatorData["query"]>;
export type SmsStatsInboundByNumberQuery = NonNullable<GetSmsInboundStatsByNumberData["query"]>;

export class SmsStatsInboundResource extends Resource {
  /**
   * Total messages your numbers received over a period. For a breakdown use `sms.stats.inbound.by_country`, `sms.stats.inbound.by_operator`, or `sms.stats.inbound.by_number`.
   *
   * @example Total messages received
   * const summary = await bird.sms.stats.inbound.summary({ from: "2026-05-01", to: "2026-05-31" });
   * console.log(summary.received);
   */
  summary(query?: SmsStatsInboundSummaryQuery, options?: RequestOptions): APIPromise<SmsInboundStatsSummaryResponse> {
    return this.call<SmsInboundStatsSummaryResponse>("GET", options, ({ signal, headers }) =>
      getSmsInboundStatsSummary({ client: this.client, query, headers, signal }));
  }

  /**
   * Messages your numbers received, one row per calendar day. Set `timezone` to get local calendar days instead of UTC.
   *
   * @example Received messages per day
   * const stats = await bird.sms.stats.inbound.daily({ from: "2026-05-01", to: "2026-05-31" });
   * for (const point of stats.data ?? []) {
   *   console.log(point.bucket, point.received);
   * }
   */
  daily(query?: SmsStatsInboundDailyQuery, options?: RequestOptions): APIPromise<SmsInboundStatsResponse> {
    return this.call<SmsInboundStatsResponse>("GET", options, ({ signal, headers }) =>
      getSmsInboundStatsDaily({ client: this.client, query, headers, signal }));
  }

  /**
   * Messages your numbers received, one row per hour, for inspecting inbound volume inside a single day.
   *
   * @example Received messages per hour
   * const stats = await bird.sms.stats.inbound.hourly({
   *   from: "2026-05-30T00:00:00Z",
   *   to: "2026-05-31T00:00:00Z",
   * });
   * for (const point of stats.data ?? []) {
   *   console.log(point.bucket, point.received);
   * }
   */
  hourly(query?: SmsStatsInboundHourlyQuery, options?: RequestOptions): APIPromise<SmsInboundStatsResponse> {
    return this.call<SmsInboundStatsResponse>("GET", options, ({ signal, headers }) =>
      getSmsInboundStatsHourly({ client: this.client, query, headers, signal }));
  }

  /**
   * Messages your numbers received, grouped by the country of the receiving number.
   *
   * @example Where senders messaged from
   * const stats = await bird.sms.stats.inbound.byCountry({ from: "2026-05-01", to: "2026-05-31" });
   * for (const row of stats.data ?? []) {
   *   console.log(row.country, row.received);
   * }
   */
  byCountry(query?: SmsStatsInboundByCountryQuery, options?: RequestOptions): APIPromise<SmsInboundStatsByCountryResponse> {
    return this.call<SmsInboundStatsByCountryResponse>("GET", options, ({ signal, headers }) =>
      getSmsInboundStatsByCountry({ client: this.client, query, headers, signal }));
  }

  /**
   * Messages your numbers received, grouped by the sender's mobile operator. Messages whose operator the carrier did not report are excluded, so these rows can sum to less than `sms.stats.inbound.summary` for the same period.
   *
   * @example Received messages per operator
   * const stats = await bird.sms.stats.inbound.byOperator({ from: "2026-05-01", to: "2026-05-31" });
   * for (const row of stats.data ?? []) {
   *   // Messages whose operator the carrier did not report are excluded, so these
   *   // rows can sum to less than the inbound summary for the same period.
   *   console.log(row.mcc_mnc, row.received);
   * }
   */
  byOperator(query?: SmsStatsInboundByOperatorQuery, options?: RequestOptions): APIPromise<SmsInboundStatsByOperatorResponse> {
    return this.call<SmsInboundStatsByOperatorResponse>("GET", options, ({ signal, headers }) =>
      getSmsInboundStatsByOperator({ client: this.client, query, headers, signal }));
  }

  /**
   * How many messages each of your numbers received, which is the view that shows whether a campaign's reply traffic is landing on the number you expect.
   *
   * @example Which number took the traffic
   * const stats = await bird.sms.stats.inbound.byNumber({ from: "2026-05-01", to: "2026-05-31" });
   * for (const row of stats.data ?? []) {
   *   console.log(row.number, row.received);
   * }
   */
  byNumber(query?: SmsStatsInboundByNumberQuery, options?: RequestOptions): APIPromise<SmsInboundStatsByNumberResponse> {
    return this.call<SmsInboundStatsByNumberResponse>("GET", options, ({ signal, headers }) =>
      getSmsInboundStatsByNumber({ client: this.client, query, headers, signal }));
  }
}
