// Code generated by surface-gen; DO NOT EDIT.
import { getSmsTemplateVersion, listSmsTemplateVersions } from "../generated/sdk.gen.js";
import type { GetSmsTemplateVersionData, ListSmsTemplateVersionsData, SmsTemplateVersion, SmsTemplateVersionSummary } from "../generated/types.gen.js";
import { Resource } from "./base.js";
import type { APIPromise, PaginatedPromise, RequestOptions } from "../core/result.js";

export type { SmsTemplateVersionSummary };
export type { SmsTemplateVersion };
export type SmsTemplatesVersionsListQuery = NonNullable<ListSmsTemplateVersionsData["query"]>;

export class SmsTemplatesVersionsResourceBase extends Resource {
  /**
   * List a template's permanent draft and immutable published versions, newest first. Built-in templates expose their current catalogue content as one synthetic published version.
   *
   * @example Walk a template's versions
   * for await (const version of bird.smsTemplates.versions.list("bird_otp_verification")) {
   *   console.log(version.id, version.version_number);
   * }
   */
  list(templateRef: string, query?: SmsTemplatesVersionsListQuery, options?: RequestOptions): PaginatedPromise<SmsTemplateVersionSummary> {
    return this.paginated<SmsTemplateVersionSummary>("GET", options, ({ signal, headers }, cursor) =>
      listSmsTemplateVersions({ client: this.client, path: { template_ref: templateRef }, query: { ...query, starting_after: cursor ?? query?.starting_after, ending_before: cursor === undefined ? query?.ending_before : undefined }, headers, signal }));
  }

  /**
   * Read one draft or published SMS template version, including its variables and text in every language. Built-in templates expose their current catalogue content through a synthetic published version.
   *
   * @example Read a version's content
   * const version = await bird.smsTemplates.versions.get(
   *   "bird_otp_verification",
   *   "smv_01ky4x8e4genzb7way45txfkm1",
   * );
   * console.log(version.id, Object.keys(version.languages));
   */
  get(templateRef: string, versionId: string, options?: RequestOptions): APIPromise<SmsTemplateVersion> {
    return this.call<SmsTemplateVersion>("GET", options, ({ signal, headers }) =>
      getSmsTemplateVersion({ client: this.client, path: { template_ref: templateRef, version_id: versionId }, headers, signal }));
  }
}
