// Code generated by surface-gen; DO NOT EDIT.
import { getSmsTemplate, listSmsTemplates } from "../generated/sdk.gen.js";
import type { GetSmsTemplateData, ListSmsTemplatesData, SmsTemplate, SmsTemplateList } from "../generated/types.gen.js";
import { Resource } from "./base.js";
import type { APIPromise, RequestOptions } from "../core/result.js";

export type { SmsTemplateList };
export type { SmsTemplate };
export type SmsTemplateListQuery = NonNullable<ListSmsTemplatesData["query"]>;

export class SmsTemplatesResource extends Resource {
  /**
   * List the SMS templates available to your workspace, including our built-in templates. Filter by scope, category, or language. The catalog is small and returned in full; this list is not paginated. Use `sms_templates.get` to read one template's variables before sending with it.
   *
   * @example List the built-in templates
   * const { data } = await bird.smsTemplates.list({ scope: "system" });
   * for (const tpl of data) console.log(tpl.id, tpl.slug);
   */
  list(query?: SmsTemplateListQuery, options?: RequestOptions): APIPromise<SmsTemplateList> {
    return this.call<SmsTemplateList>("GET", options, ({ signal, headers }) =>
      listSmsTemplates({ client: this.client, query, headers, signal }));
  }

  /**
   * Get one SMS template by its slug or ID, including its body and the variables it expects. Fetch it before `sms.send` to see which parameter keys a template send requires.
   *
   * @example Read one template by slug or id
   * const tpl = await bird.smsTemplates.get("bird_otp_verification");
   * console.log(tpl.body, tpl.variables);
   */
  get(templateRef: string, options?: RequestOptions): APIPromise<SmsTemplate> {
    return this.call<SmsTemplate>("GET", options, ({ signal, headers }) =>
      getSmsTemplate({ client: this.client, path: { template_ref: templateRef }, headers, signal }));
  }
}
