// Code generated by surface-gen; DO NOT EDIT.
import { createSuppression, deleteSuppression, getSuppression, listSuppressions } from "../generated/sdk.gen.js";
import type { CreateSuppressionData, DeleteSuppressionData, GetSuppressionData, ListSuppressionsData, Suppression } from "../generated/types.gen.js";
import { Resource } from "./base.js";
import type { APIPromise, PaginatedPromise, RequestOptions } from "../core/result.js";

export type { Suppression };
export type SuppressionsListQuery = NonNullable<ListSuppressionsData["query"]>;
export type SuppressionsAddParams = NonNullable<CreateSuppressionData["body"]>;

export class SuppressionsResource extends Resource {
  /**
   * List the workspace's email suppressions as a cursor page. A suppression blocks delivery to an address. The `email` parameter filters by prefix, so compare the complete addresses you get back before treating one as a match.
   *
   * @example Iterate the addresses you cannot send to
   * for await (const suppression of bird.suppressions.list()) {
   *   console.log(suppression.email, suppression.reason);
   * }
   */
  list(query?: SuppressionsListQuery, options?: RequestOptions): PaginatedPromise<Suppression> {
    return this.paginated<Suppression>("GET", options, ({ signal, headers }, cursor) =>
      listSuppressions({ client: this.client, query: { ...query, starting_after: cursor ?? query?.starting_after, ending_before: cursor === undefined ? query?.ending_before : undefined }, headers, signal }));
  }

  /**
   * Fetch one suppression record by its ID: the address, why it's suppressed, how the record originated, and which categories it blocks. Use `suppressions.list` with `email` when you only know the address. Compare complete addresses across all cursor pages because that filter matches by prefix.
   *
   * @example Read one suppression record
   * const suppression = await bird.suppressions.get("sup_abc123");
   * console.log(suppression.reason, suppression.applies_to);
   */
  get(suppressionId: string, options?: RequestOptions): APIPromise<Suppression> {
    return this.call<Suppression>("GET", options, ({ signal, headers }) =>
      getSuppression({ client: this.client, path: { suppression_id: suppressionId }, headers, signal }));
  }

  /**
   * Add an email address to the workspace suppression list to stop delivery to it. The record is created with reason `manual`, which blocks every message category, transactional mail included. Adding is idempotent, so an address that already carries a manual suppression comes back unchanged.
   *
   * @example Stop sending to an address
   * // Adding is idempotent: an existing `manual` record is returned unchanged.
   * const suppression = await bird.suppressions.add({
   *   email: "blocked@example.com",
   * });
   * console.log(suppression.id);
   */
  add(params: SuppressionsAddParams, options?: RequestOptions): APIPromise<Suppression> {
    return this.call<Suppression>("POST", options, ({ signal, headers }) =>
      createSuppression({ client: this.client, body: params, headers, signal }));
  }

  /**
   * Remove one suppression record by ID. Check for other blocking records before resuming delivery. Removing a block without cause can harm sender reputation. An API key cannot remove a `complaint` record; use the dashboard for that record.
   *
   * @example Remove one suppression record
   * // Check for remaining blocking records before resuming delivery.
   * await bird.suppressions.remove("sup_abc123");
   */
  remove(suppressionId: string, options?: RequestOptions): APIPromise<void> {
    return this.call<void>("DELETE", options, ({ signal, headers }) =>
      deleteSuppression({ client: this.client, path: { suppression_id: suppressionId }, headers, signal }));
  }
}
