// Code generated by surface-gen; DO NOT EDIT.
import { createVerification, createVerificationCheck, createVerificationNextChannel } from "../generated/sdk.gen.js";
import type { CreateVerificationCheckData, CreateVerificationData, CreateVerificationNextChannelData, Verification, VerificationCheckResult } from "../generated/types.gen.js";
import { Resource } from "./base.js";
import type { APIPromise, RequestOptions } from "../core/result.js";

export type { Verification };
export type { VerificationCheckResult };
export type VerifyVerificationsCreateParams = NonNullable<CreateVerificationData["body"]>;
export type VerifyVerificationsCheckParams = NonNullable<CreateVerificationCheckData["body"]>;
export type VerifyVerificationsNextChannelParams = NonNullable<CreateVerificationNextChannelData["body"]>;

export class VerifyVerificationsResource extends Resource {
  /**
   * Start a verification and send a one-time passcode to the email address, phone number, or both in `to`. Delivery uses one planned channel at a time and fails over when necessary. Calling again for the same recipient reuses the verification in progress and sends after the resend cooldown. The passcode is never returned; submit the recipient's code with `verify.verifications.check`. SMS, WhatsApp, and Telegram delivery draw on the workspace's balance.
   *
   * @example Start a verification over SMS
   * const verification = await bird.verify.verifications.create({
   *   to: { phone_number: "+15551234567" },
   * });
   * console.log(verification.id, verification.status);
   */
  create(params: VerifyVerificationsCreateParams, options?: RequestOptions): APIPromise<Verification> {
    return this.call<Verification>("POST", options, ({ signal, headers }) =>
      createVerification({ client: this.client, body: params, headers, signal }));
  }

  /**
   * Check a passcode a recipient submitted. Identify the verification by the same `to` recipient used to start it; no verification ID is needed. A wrong or expired code returns HTTP 200 with `success: false` and a `reason` (for example `incorrect_code` or `expired`). A verification that has already reached a final state is no longer checkable and returns 404, as does a missing verification; malformed input or rate limiting is also an error status.
   *
   * @example Check a submitted passcode
   * const result = await bird.verify.verifications.check({
   *   to: { phone_number: "+15551234567" },
   *   code: "123456",
   * });
   * console.log(result.success);
   */
  check(params: VerifyVerificationsCheckParams, options?: RequestOptions): APIPromise<VerificationCheckResult> {
    return this.call<VerificationCheckResult>("POST", options, ({ signal, headers }) =>
      createVerificationCheck({ client: this.client, body: params, headers, signal }));
  }

  /**
   * Advance an in-progress verification to its next channel and send a fresh passcode. Identify it with the same `to` recipient used to create it; no verification ID is required. This bypasses the resend cooldown, and earlier passcodes remain valid. `last_channel` identifies the most recent completed send. `422 NoNextChannel` means the plan is exhausted; create the verification again to resend on the current channel.
   *
   * @example Send the code again on the next channel
   * const verification = await bird.verify.verifications.nextChannel({
   *   to: { phone_number: "+15551234567" },
   * });
   * console.log(verification.last_channel);
   */
  nextChannel(params: VerifyVerificationsNextChannelParams, options?: RequestOptions): APIPromise<Verification> {
    return this.call<Verification>("POST", options, ({ signal, headers }) =>
      createVerificationNextChannel({ client: this.client, body: params, headers, signal }));
  }
}
