// Code generated by surface-gen; DO NOT EDIT.
import { createVoiceCall } from "../generated/sdk.gen.js";
import type { CreateVoiceCallData, VoiceCall } from "../generated/types.gen.js";
import { Resource } from "./base.js";
import type { APIPromise, RequestOptions } from "../core/result.js";

export type { VoiceCall };
export type VoiceCallsCreateParams = NonNullable<CreateVoiceCallData["body"]>;

export class VoiceCallsResource extends Resource {
  /**
   * Proposes a real outbound call for browser confirmation. Requires voice_management:write and voice:write; normal calling charges apply. Supply a stable idempotency_key and reuse it with identical input for retries. The confirmation expires after 90 minutes. After the person places the call, a 202 response reserves call, leg and run IDs; it does not prove connection. Use `voice.legs.get` with `initial_leg_id` to inspect the leg outcome, and inspect the sequence run in the dashboard. Never use a new key merely because an earlier result is missing.
   *
   * @example Start a published sequence call
   * const call = await bird.voice.calls.create({
   *   from: "+12025550100",
   *   to: "+12025550101",
   *   sequence: {
   *     id: "vsq_01krdgeqcxet5s7t44vh8rt9mg",
   *     entry_node_id: "start",
   *     trigger_data: {},
   *   },
   * });
   * console.log(call.id, call.initial_leg_id, call.sequence?.run_id);
   */
  create(params: VoiceCallsCreateParams, options?: RequestOptions): APIPromise<VoiceCall> {
    return this.call<VoiceCall>("POST", options, ({ signal, headers }) =>
      createVoiceCall({ client: this.client, body: params, headers, signal }));
  }
}
