// Code generated by surface-gen; DO NOT EDIT.
import { getVoiceLeg, listVoiceLegs } from "../generated/sdk.gen.js";
import type { GetVoiceLegData, ListVoiceLegsData, VoiceLeg } from "../generated/types.gen.js";
import { Resource } from "./base.js";
import type { APIPromise, PaginatedPromise, RequestOptions } from "../core/result.js";

export type { VoiceLeg };
export type VoiceLegsListQuery = NonNullable<ListVoiceLegsData["query"]>;

export class VoiceLegsResource extends Resource {
  /**
   * List the workspace's legs, newest first. Filter to `ringing`/`in_progress` for the legs in progress right now, to final statuses for completed records, or to any mix of the two. Use `from`/`to` for one known party number in international form, and `number` to search either side by fragment. These are per-leg records and do not include aggregate rates or totals. Use `voice.legs.get` to follow one leg to settlement.
   *
   * @example Iterate completed legs
   * for await (const leg of bird.voice.legs.list()) {
   *   console.log(leg.id, leg.status);
   * }
   */
  list(query?: VoiceLegsListQuery, options?: RequestOptions): PaginatedPromise<VoiceLeg> {
    return this.paginated<VoiceLeg>("GET", options, ({ signal, headers }, cursor) =>
      listVoiceLegs({ client: this.client, query: { ...query, starting_after: cursor ?? query?.starting_after, ending_before: cursor === undefined ? query?.ending_before : undefined }, headers, signal }));
  }

  /**
   * Fetch one leg by ID, at any point in its lifecycle. A leg still ringing or connected carries no economics yet: `duration_ms`, `billable_ms`, `ended_at`, and `cost` are null until it ends, and the same ID then returns the settled record. Poll here to watch one known leg; use `voice.legs.list` to find legs in the first place. When a leg was refused, `rejection_reason` names the gate that turned it away.
   *
   * @example Read one call back
   * const call = await bird.voice.legs.get("vcl_01k0p3v9wera3v6q6xw3e9y2mh");
   * // A call still ringing or connected carries no economics yet.
   * call.status; // "answered" | "no_answer" | "ringing" | …
   */
  get(legId: string, options?: RequestOptions): APIPromise<VoiceLeg> {
    return this.call<VoiceLeg>("GET", options, ({ signal, headers }) =>
      getVoiceLeg({ client: this.client, path: { leg_id: legId }, headers, signal }));
  }
}
