// Code generated by surface-gen; DO NOT EDIT.
import { getVoiceCall, listVoiceCalls } from "../generated/sdk.gen.js";
import type { GetVoiceCallData, ListVoiceCallsData, VoiceCall } from "../generated/types.gen.js";
import { Resource } from "./base.js";
import type { APIPromise, PaginatedPromise, RequestOptions } from "../core/result.js";

export type { VoiceCall };
export type VoiceListQuery = NonNullable<ListVoiceCallsData["query"]>;

export class VoiceResource extends Resource {
  /**
   * List the workspace's calls, newest first. Filter to `ringing`/`in_progress` for the calls in progress right now, to final statuses for completed records, or to any mix of the two. Use `from`/`to` for one known party number in international form, and `number` to search either side by fragment. These are per-call records and do not include aggregate rates or totals. Use `voice.get` to follow one call to settlement.
   *
   * @example Iterate the calls happening right now
   * for await (const call of bird.voice.list({ status: ["ringing", "in_progress"] })) {
   *   console.log(call.id, call.status);
   * }
   */
  list(query?: VoiceListQuery, options?: RequestOptions): PaginatedPromise<VoiceCall> {
    return this.paginated<VoiceCall>("GET", options, ({ signal, headers }, cursor) =>
      listVoiceCalls({ client: this.client, query: { ...query, starting_after: cursor ?? query?.starting_after }, headers, signal }));
  }

  /**
   * Fetch one call by ID, at any point in its lifecycle. A call still ringing or connected carries no economics yet: `duration_ms`, `billable_ms`, `ended_at`, and `cost` are null until it ends, and the same ID then returns the settled record. Poll here to watch one known call; use `voice.list` to find calls in the first place. When a call was refused, `rejection_reason` names the gate that turned it away.
   *
   * @example Read one call back
   * const call = await bird.voice.get("vcl_01k0p3v9wera3v6q6xw3e9y2mh");
   * // A call still ringing or connected carries no economics yet.
   * call.status; // "answered" | "no_answer" | "ringing" | …
   */
  get(callId: string, options?: RequestOptions): APIPromise<VoiceCall> {
    return this.call<VoiceCall>("GET", options, ({ signal, headers }) =>
      getVoiceCall({ client: this.client, path: { call_id: callId }, headers, signal }));
  }
}
