// Code generated by surface-gen; DO NOT EDIT.
import { createVoiceVerifiedNumber, deleteVoiceVerifiedNumber, getVoiceVerifiedNumber, listVoiceVerifiedNumbers, updateVoiceVerifiedNumber, verifyVoiceVerifiedNumber } from "../generated/sdk.gen.js";
import type { CreateVoiceVerifiedNumberData, DeleteVoiceVerifiedNumberData, GetVoiceVerifiedNumberData, ListVoiceVerifiedNumbersData, UpdateVoiceVerifiedNumberData, VerifyVoiceVerifiedNumberData, VoiceVerifiedNumber } from "../generated/types.gen.js";
import { Resource } from "./base.js";
import type { APIPromise, PaginatedPromise, RequestOptions } from "../core/result.js";

export type { VoiceVerifiedNumber };
export type VoiceVerifiedNumbersListQuery = NonNullable<ListVoiceVerifiedNumbersData["query"]>;
export type VoiceVerifiedNumbersVerifyParams = NonNullable<VerifyVoiceVerifiedNumberData["body"]>;
export type VoiceVerifiedNumbersCreateParams = NonNullable<CreateVoiceVerifiedNumberData["body"]>;
export type VoiceVerifiedNumbersUpdateParams = NonNullable<UpdateVoiceVerifiedNumberData["body"]>;

export class VoiceVerifiedNumbersResource extends Resource {
  /**
   * List the workspace's verified numbers and their verification status, as a cursor page. Only a verified number may be presented on an outbound call, so an unverified or missing entry here is a common reason a call is refused.
   *
   * @example List your registered numbers
   * for await (const verifiedNumber of bird.voice.verifiedNumbers.list()) {
   *   console.log(verifiedNumber.id, verifiedNumber.phone_number, verifiedNumber.status);
   * }
   */
  list(query?: VoiceVerifiedNumbersListQuery, options?: RequestOptions): PaginatedPromise<VoiceVerifiedNumber> {
    return this.paginated<VoiceVerifiedNumber>("GET", options, ({ signal, headers }, cursor) =>
      listVoiceVerifiedNumbers({ client: this.client, query: { ...query, starting_after: cursor ?? query?.starting_after, ending_before: cursor === undefined ? query?.ending_before : undefined }, headers, signal }));
  }

  /**
   * Fetch one verified number by ID, with its verification status. Use `voice.verified_numbers.list` to find the ID.
   *
   * @example Read one verified number
   * const verifiedNumber = await bird.voice.verifiedNumbers.get("vvn_01krdgeqcxet5s7t44vh8rt9mg");
   * console.log(verifiedNumber.phone_number, verifiedNumber.status, verifiedNumber.verified_at);
   */
  get(verifiedNumberId: string, options?: RequestOptions): APIPromise<VoiceVerifiedNumber> {
    return this.call<VoiceVerifiedNumber>("GET", options, ({ signal, headers }) =>
      getVoiceVerifiedNumber({ client: this.client, path: { verified_number_id: verifiedNumberId }, headers, signal }));
  }

  /**
   * Complete the ownership verification challenge that `voice.verified_numbers.create` started. Recovery may place another verification call and requires registration eligibility. Submit the code while ownership proof is pending. If proof was saved but outbound activation returned 412 or 503, resolve the issue and resubmit an empty object to reuse the proof. For an expired or exhausted challenge, delete the verified number and create it again, then submit the code against the ID that create returns.
   *
   * @example Submit a number verification code
   * const verifiedNumber = await bird.voice.verifiedNumbers.verify("vvn_01krdgeqcxet5s7t44vh8rt9mg", { code: "123456" });
   * console.log(verifiedNumber.id, verifiedNumber.status);
   */
  verify(verifiedNumberId: string, params: VoiceVerifiedNumbersVerifyParams = {}, options?: RequestOptions): APIPromise<VoiceVerifiedNumber> {
    return this.call<VoiceVerifiedNumber>("POST", options, ({ signal, headers }) =>
      verifyVoiceVerifiedNumber({ client: this.client, path: { verified_number_id: verifiedNumberId }, body: params, headers, signal }));
  }

  /**
   * Register a phone number as an outbound caller ID for the workspace. This places a verification call to the number that reads out a code, so register only a number the user controls. Returns the verified number in the "pending" state; submit the code with `voice.verified_numbers.verify`. A 412 means the organization's identity verification is incomplete, which is completed in the dashboard, or that an eligibility review or denial needs support. A 503 means the eligibility assessment is still pending; retry later.
   *
   * @example Register a number to present as caller ID
   * // This places a verification call to the number that reads out a code.
   * const verifiedNumber = await bird.voice.verifiedNumbers.create({ phone_number: "+14155551234", name: "Support line" });
   * console.log(verifiedNumber.id, verifiedNumber.status);
   */
  create(params: VoiceVerifiedNumbersCreateParams, options?: RequestOptions): APIPromise<VoiceVerifiedNumber> {
    return this.call<VoiceVerifiedNumber>("POST", options, ({ signal, headers }) =>
      createVoiceVerifiedNumber({ client: this.client, body: params, headers, signal }));
  }

  /**
   * Set or clear the label on a verified number; send `name` as null to clear it. The number and its verification state are unchanged, and the label never appears on a call.
   *
   * @example Rename a verified number
   * const verifiedNumber = await bird.voice.verifiedNumbers.update("vvn_01krdgeqcxet5s7t44vh8rt9mg", { name: "Sales line" });
   * console.log(verifiedNumber.name);
   */
  update(verifiedNumberId: string, params: VoiceVerifiedNumbersUpdateParams = {}, options?: RequestOptions): APIPromise<VoiceVerifiedNumber> {
    return this.call<VoiceVerifiedNumber>("PATCH", options, ({ signal, headers }) =>
      updateVoiceVerifiedNumber({ client: this.client, path: { verified_number_id: verifiedNumberId }, body: params, headers, signal }));
  }

  /**
   * Permanently delete a verified number by ID. After deletion the number can no longer be presented as the outbound caller ID and must be re-registered and verified to use it again. Deleting a pending registration and creating it again is how an expired or exhausted verification challenge is replaced.
   *
   * @example Delete a verified number
   * await bird.voice.verifiedNumbers.delete("vvn_01krdgeqcxet5s7t44vh8rt9mg");
   */
  delete(verifiedNumberId: string, options?: RequestOptions): APIPromise<void> {
    return this.call<void>("DELETE", options, ({ signal, headers }) =>
      deleteVoiceVerifiedNumber({ client: this.client, path: { verified_number_id: verifiedNumberId }, headers, signal }));
  }
}
