// Code generated by surface-gen; DO NOT EDIT.
import { getVoiceCallerId, listVoiceCallerIds, verifyVoiceCallerId } from "../generated/sdk.gen.js";
import type { GetVoiceCallerIdData, ListVoiceCallerIdsData, VerifyVoiceCallerIdData, VoiceCallerId } from "../generated/types.gen.js";
import { Resource } from "./base.js";
import type { APIPromise, PaginatedPromise, RequestOptions } from "../core/result.js";

export type { VoiceCallerId };
export type VoiceCallerIdsListQuery = NonNullable<ListVoiceCallerIdsData["query"]>;
export type VoiceCallerIdsVerifyParams = NonNullable<VerifyVoiceCallerIdData["body"]>;

export class VoiceCallerIdsResource extends Resource {
  /**
   * List the workspace's caller IDs and their verification status, as a cursor page. Only a verified caller ID may be presented on an outbound call, so an unverified or missing entry here is a common reason a call is refused.
   *
   * @example List your verified caller IDs
   * for await (const callerId of bird.voice.callerIds.list()) {
   *   console.log(callerId.id, callerId.phone_number, callerId.status);
   * }
   */
  list(query?: VoiceCallerIdsListQuery, options?: RequestOptions): PaginatedPromise<VoiceCallerId> {
    return this.paginated<VoiceCallerId>("GET", options, ({ signal, headers }, cursor) =>
      listVoiceCallerIds({ client: this.client, query: { ...query, starting_after: cursor ?? query?.starting_after, ending_before: cursor === undefined ? query?.ending_before : undefined }, headers, signal }));
  }

  /**
   * Fetch one caller ID by ID, with its verification status. Use `voice.caller_ids.list` to find the ID.
   *
   * @example Read one caller ID
   * const callerId = await bird.voice.callerIds.get("caller-id");
   * console.log(callerId.phone_number, callerId.status, callerId.verified_at);
   */
  get(callerId: string, options?: RequestOptions): APIPromise<VoiceCallerId> {
    return this.call<VoiceCallerId>("GET", options, ({ signal, headers }) =>
      getVoiceCallerId({ client: this.client, path: { caller_id: callerId }, headers, signal }));
  }

  /**
   * Complete a caller-ID verification challenge started in the dashboard. Recovery may place another verification call and requires registration eligibility. Submit the code while ownership proof is pending. If proof was saved but outbound activation returned 412 or 503, resolve the issue and resubmit an empty object to reuse the proof. For expired or exhausted challenges, use Get a new code in the dashboard and list caller IDs to obtain the replacement ID.
   *
   * @example Submit a caller-ID verification code
   * const callerId = await bird.voice.callerIds.verify("CALLER_ID", { code: "123456" });
   * console.log(callerId.id, callerId.status);
   */
  verify(callerId: string, params: VoiceCallerIdsVerifyParams = {}, options?: RequestOptions): APIPromise<VoiceCallerId> {
    return this.call<VoiceCallerId>("POST", options, ({ signal, headers }) =>
      verifyVoiceCallerId({ client: this.client, path: { caller_id: callerId }, body: params, headers, signal }));
  }
}
