// Code generated by surface-gen; DO NOT EDIT.
import { getVoiceNumber, listVoiceNumbers, updateVoiceNumber } from "../generated/sdk.gen.js";
import type { GetVoiceNumberData, ListVoiceNumbersData, UpdateVoiceNumberData, VoiceNumber } from "../generated/types.gen.js";
import { Resource } from "./base.js";
import type { APIPromise, PaginatedPromise, RequestOptions } from "../core/result.js";

export type { VoiceNumber };
export type VoiceNumbersListQuery = NonNullable<ListVoiceNumbersData["query"]>;
export type VoiceNumbersUpdateParams = NonNullable<UpdateVoiceNumberData["body"]>;

export class VoiceNumbersResource extends Resource {
  /**
   * List every phone number the workspace can use for voice, as a cursor page ordered by number. Each entry is one phone number, with where its calls go and whether it may be presented on an outbound call.
   *
   * @example List the numbers you can use for voice
   * for await (const number of bird.voice.numbers.list()) {
   *   console.log(number.id, number.phone_number, number.country_code);
   * }
   */
  list(query?: VoiceNumbersListQuery, options?: RequestOptions): PaginatedPromise<VoiceNumber> {
    return this.paginated<VoiceNumber>("GET", options, ({ signal, headers }, cursor) =>
      listVoiceNumbers({ client: this.client, query: { ...query, starting_after: cursor ?? query?.starting_after, ending_before: cursor === undefined ? query?.ending_before : undefined }, headers, signal }));
  }

  /**
   * Fetch one phone number the workspace can use for voice by id: where its calls go, whether it may be presented on an outbound call, and where it came from. Use `voice.numbers.list` to find the id.
   *
   * @example Read one number
   * const number = await bird.voice.numbers.get("number-id");
   * console.log(number.phone_number, number.directions);
   */
  get(numberId: string, options?: RequestOptions): APIPromise<VoiceNumber> {
    return this.call<VoiceNumber>("GET", options, ({ signal, headers }) =>
      getVoiceNumber({ client: this.client, path: { number_id: numberId }, headers, signal }));
  }

  /**
   * Change what happens to calls arriving for one number, or the workspace's own label for it. Set the route to `reject` to stop it answering, to `trunk` with a trunk_id to deliver to one of your SIP trunks, or to `forward` with a forward_to and a forward_as to place a call to one of your verified caller IDs. The route replaces whatever was set before, because a number has exactly one answer at a time, and `forward_as` must be stated on every forward. Only a number whose calls arrive at Bird can carry a route.
   *
   * @example Rename a number
   * const number = await bird.voice.numbers.update("number-id", { name: "Support line" });
   * console.log(number.id, number.name);
   */
  update(numberId: string, params: VoiceNumbersUpdateParams = {}, options?: RequestOptions): APIPromise<VoiceNumber> {
    return this.call<VoiceNumber>("PATCH", options, ({ signal, headers }) =>
      updateVoiceNumber({ client: this.client, path: { number_id: numberId }, body: params, headers, signal }));
  }
}
