// Code generated by surface-gen; DO NOT EDIT.
import { createVoiceCall } from "../generated/sdk.gen.js";
import type { CreateVoiceCallData, VoiceCall } from "../generated/types.gen.js";
import { Resource } from "./base.js";
import type { APIPromise, RequestOptions } from "../core/result.js";

export type { VoiceCall };
export type VoiceCallsCreateParams = NonNullable<CreateVoiceCallData["body"]>;

export class VoiceCallsResource extends Resource {
  /**
   * Places a real outbound call and starts the active published sequence after the recipient answers. Requires both voice management write and voice calling write permissions. Normal calling charges apply. Retain the acceptance IDs to inspect the run and initial leg.
   *
   * @example Start a published sequence call
   * const call = await bird.voice.calls.create({
   *   from: "+12025550100",
   *   to: "+12025550101",
   *   sequence: {
   *     id: "vsq_01krdgeqcxet5s7t44vh8rt9mg",
   *     entry_node_id: "start",
   *     trigger_data: {},
   *   },
   * });
   * console.log(call.id, call.initial_leg_id, call.sequence?.run_id);
   */
  create(params: VoiceCallsCreateParams, options?: RequestOptions): APIPromise<VoiceCall> {
    return this.call<VoiceCall>("POST", options, ({ signal, headers }) =>
      createVoiceCall({ client: this.client, body: params, headers, signal }));
  }
}
