// Code generated by surface-gen; DO NOT EDIT.
import { getVoiceVerifiedNumber, listVoiceVerifiedNumbers, verifyVoiceVerifiedNumber } from "../generated/sdk.gen.js";
import type { GetVoiceVerifiedNumberData, ListVoiceVerifiedNumbersData, VerifyVoiceVerifiedNumberData, VoiceVerifiedNumber } from "../generated/types.gen.js";
import { Resource } from "./base.js";
import type { APIPromise, PaginatedPromise, RequestOptions } from "../core/result.js";

export type { VoiceVerifiedNumber };
export type VoiceVerifiedNumbersListQuery = NonNullable<ListVoiceVerifiedNumbersData["query"]>;
export type VoiceVerifiedNumbersVerifyParams = NonNullable<VerifyVoiceVerifiedNumberData["body"]>;

export class VoiceVerifiedNumbersResource extends Resource {
  /**
   * List the workspace's verified numbers and their verification status, as a cursor page. Only a verified number may be presented on an outbound call, so an unverified or missing entry here is a common reason a call is refused.
   *
   * @example List your registered numbers
   * for await (const verifiedNumber of bird.voice.verifiedNumbers.list()) {
   *   console.log(verifiedNumber.id, verifiedNumber.phone_number, verifiedNumber.status);
   * }
   */
  list(query?: VoiceVerifiedNumbersListQuery, options?: RequestOptions): PaginatedPromise<VoiceVerifiedNumber> {
    return this.paginated<VoiceVerifiedNumber>("GET", options, ({ signal, headers }, cursor) =>
      listVoiceVerifiedNumbers({ client: this.client, query: { ...query, starting_after: cursor ?? query?.starting_after, ending_before: cursor === undefined ? query?.ending_before : undefined }, headers, signal }));
  }

  /**
   * Fetch one verified number by ID, with its verification status. Use `voice.verified_numbers.list` to find the ID.
   *
   * @example Read one verified number
   * const verifiedNumber = await bird.voice.verifiedNumbers.get("vvn_01krdgeqcxet5s7t44vh8rt9mg");
   * console.log(verifiedNumber.phone_number, verifiedNumber.status, verifiedNumber.verified_at);
   */
  get(verifiedNumberId: string, options?: RequestOptions): APIPromise<VoiceVerifiedNumber> {
    return this.call<VoiceVerifiedNumber>("GET", options, ({ signal, headers }) =>
      getVoiceVerifiedNumber({ client: this.client, path: { verified_number_id: verifiedNumberId }, headers, signal }));
  }

  /**
   * Complete a number ownership verification challenge started in the dashboard. Recovery may place another verification call and requires registration eligibility. Submit the code while ownership proof is pending. If proof was saved but outbound activation returned 412 or 503, resolve the issue and resubmit an empty object to reuse the proof. For expired or exhausted challenges, use Get a new code in the dashboard and list verified numbers to obtain the replacement ID.
   *
   * @example Submit a number verification code
   * const verifiedNumber = await bird.voice.verifiedNumbers.verify("vvn_01krdgeqcxet5s7t44vh8rt9mg", { code: "123456" });
   * console.log(verifiedNumber.id, verifiedNumber.status);
   */
  verify(verifiedNumberId: string, params: VoiceVerifiedNumbersVerifyParams = {}, options?: RequestOptions): APIPromise<VoiceVerifiedNumber> {
    return this.call<VoiceVerifiedNumber>("POST", options, ({ signal, headers }) =>
      verifyVoiceVerifiedNumber({ client: this.client, path: { verified_number_id: verifiedNumberId }, body: params, headers, signal }));
  }
}
