// Code generated by surface-gen; DO NOT EDIT.
import { createVoiceTrunk, deleteVoiceTrunk, getVoiceTrunk, listVoiceTrunks, updateVoiceTrunk } from "../generated/sdk.gen.js";
import type { CreateVoiceTrunkData, DeleteVoiceTrunkData, GetVoiceTrunkData, ListVoiceTrunksData, UpdateVoiceTrunkData, VoiceTrunk } from "../generated/types.gen.js";
import { Resource } from "./base.js";
import type { APIPromise, PaginatedPromise, RequestOptions } from "../core/result.js";

export type { VoiceTrunk };
export type VoiceTrunksListQuery = NonNullable<ListVoiceTrunksData["query"]>;
export type VoiceTrunksCreateParams = NonNullable<CreateVoiceTrunkData["body"]>;
export type VoiceTrunksUpdateParams = NonNullable<UpdateVoiceTrunkData["body"]>;

export class VoiceTrunksResourceBase extends Resource {
  /**
   * List the workspace's SIP trunks as a cursor page. Each carries the Bird-assigned `domain` the customer's equipment sends calls to. The `ip_acls` and `allowed_api_key_ids` fields control which calls are admitted; a trunk with both empty admits nothing when `session_credentials_enabled` is false. Keys listed in `ineligible_api_key_ids` cannot authenticate even though they remain bound to the trunk.
   *
   * @example Find the trunk a call arrives on
   * for await (const trunk of bird.voice.trunks.list()) {
   *   // A trunk with no allow list and no session credentials admits nothing.
   *   console.log(trunk.id, trunk.domain, trunk.inbound_enabled);
   * }
   */
  list(query?: VoiceTrunksListQuery, options?: RequestOptions): PaginatedPromise<VoiceTrunk> {
    return this.paginated<VoiceTrunk>("GET", options, ({ signal, headers }, cursor) =>
      listVoiceTrunks({ client: this.client, query: { ...query, starting_after: cursor ?? query?.starting_after, ending_before: cursor === undefined ? query?.ending_before : undefined }, headers, signal }));
  }

  /**
   * Fetch one SIP trunk by ID: its `domain`, `ip_acls`, and `allowed_api_key_ids`. Use `voice.trunks.list` to find the ID.
   *
   * @example Read one trunk's configuration
   * const trunk = await bird.voice.trunks.get("trunk-id");
   * console.log(trunk.name, trunk.inbound_enabled, trunk.outbound_enabled);
   */
  get(trunkId: string, options?: RequestOptions): APIPromise<VoiceTrunk> {
    return this.call<VoiceTrunk>("GET", options, ({ signal, headers }) =>
      getVoiceTrunk({ client: this.client, path: { trunk_id: trunkId }, headers, signal }));
  }

  /**
   * Create a new SIP trunk for the workspace. Returns the Bird-assigned domain to configure in the customer's PBX or SIP client.
   *
   * @example Register a SIP trunk
   * const trunk = await bird.voice.trunks.create({
   *   name: "Lisbon office",
   *   outbound_enabled: true,
   *   inbound_enabled: true,
   * });
   * console.log(trunk.id, trunk.domain);
   */
  create(params: VoiceTrunksCreateParams, options?: RequestOptions): APIPromise<VoiceTrunk> {
    return this.call<VoiceTrunk>("POST", options, ({ signal, headers }) =>
      createVoiceTrunk({ client: this.client, body: params, headers, signal }));
  }

  /**
   * Change a SIP trunk's directions, name, access control and Digest offer. A direction has to be enabled before its settings can be set, and one update can do both, so this is the operation that clears `VoiceTrunkOutboundNotEnabled` and `VoiceTrunkInboundNotEnabled`. The `ip_acls`, `allowed_api_key_ids` and `digest_algorithms` fields each REPLACE their whole list, so read `voice.trunks.get` first and send the list you want to end up with. An empty array clears an allow list; an empty `digest_algorithms` array restores the default offer. Turning `inbound_enabled` off resets number routes that use this trunk to reject incoming calls. Turning it back on does not restore those routes, so confirm that change with the user first.
   *
   * @example Replace a trunk's IP allow list
   * const trunk = await bird.voice.trunks.update("spt_01krdgeqcxet5s7t44vh8rt9mg", {
   *   // Each list replaces the previous one, so send what you want to end up with.
   *   ip_acls: [{ cidr: "203.0.113.0/24", description: "Amsterdam PBX" }],
   * });
   * console.log(trunk.ip_acls);
   */
  update(trunkId: string, params: VoiceTrunksUpdateParams = {}, options?: RequestOptions): APIPromise<VoiceTrunk> {
    return this.call<VoiceTrunk>("PATCH", options, ({ signal, headers }) =>
      updateVoiceTrunk({ client: this.client, path: { trunk_id: trunkId }, body: params, headers, signal }));
  }

  /**
   * Delete a SIP trunk by ID. Calls in progress are not affected; new calls cannot use the trunk. Its generated domain is not reused.
   *
   * @example Remove a trunk
   * await bird.voice.trunks.delete("trunk-id");
   */
  delete(trunkId: string, options?: RequestOptions): APIPromise<void> {
    return this.call<void>("DELETE", options, ({ signal, headers }) =>
      deleteVoiceTrunk({ client: this.client, path: { trunk_id: trunkId }, headers, signal }));
  }
}
