// Code generated by surface-gen; DO NOT EDIT.
import { createWebhook, deleteWebhook, getWebhook, listWebhookAttempts, listWebhooks, rotateWebhookSecret, testWebhook, updateWebhook } from "../generated/sdk.gen.js";
import type { CreateWebhookData, DeleteWebhookData, GetWebhookData, ListWebhookAttemptsData, ListWebhooksData, RotateWebhookSecretData, TestWebhookData, UpdateWebhookData, WebhookAttemptList, WebhookEndpoint, WebhookEndpointCreated, WebhookRotateSecretResponse, WebhookTestResponse } from "../generated/types.gen.js";
import { Resource } from "./base.js";
import type { APIPromise, PaginatedPromise, RequestOptions } from "../core/result.js";

export type { WebhookEndpoint };
export type { WebhookEndpointCreated };
export type { WebhookTestResponse };
export type { WebhookAttemptList };
export type { WebhookRotateSecretResponse };
export type WebhooksListQuery = NonNullable<ListWebhooksData["query"]>;
export type WebhooksCreateParams = NonNullable<CreateWebhookData["body"]>;
export type WebhooksTestParams = NonNullable<TestWebhookData["body"]>;
export type WebhooksAttemptsQuery = NonNullable<ListWebhookAttemptsData["query"]>;
export type WebhooksUpdateParams = NonNullable<UpdateWebhookData["body"]>;

export class WebhooksResourceBase extends Resource {
  /**
   * List the workspace's webhook endpoints (URL, subscribed events, status) as a cursor page.
   *
   * @example Iterate every webhook endpoint
   * for await (const endpoint of bird.webhooks.list()) {
   *   console.log(endpoint.id, endpoint.url, endpoint.status);
   * }
   */
  list(query?: WebhooksListQuery, options?: RequestOptions): PaginatedPromise<WebhookEndpoint> {
    return this.paginated<WebhookEndpoint>("GET", options, ({ signal, headers }, cursor) =>
      listWebhooks({ client: this.client, query: { ...query, starting_after: cursor ?? query?.starting_after }, headers, signal }));
  }

  /**
   * Read one endpoint's URL, subscribed event types, and current delivery status. The signing secret is never included, and can only be rotated rather than retrieved.
   *
   * @example Fetch one endpoint by id
   * const endpoint = await bird.webhooks.get("whk_01krdgeqcxet5s7t44vh8rt9mg");
   * console.log(endpoint.url, endpoint.events);
   */
  get(webhookId: string, options?: RequestOptions): APIPromise<WebhookEndpoint> {
    return this.call<WebhookEndpoint>("GET", options, ({ signal, headers }) =>
      getWebhook({ client: this.client, path: { webhook_id: webhookId }, headers, signal }));
  }

  /**
   * Register an HTTPS endpoint to receive this workspace's events, subscribed to the event types in `events` and active immediately. The response is the only place the signing secret appears, and it can never be read back afterward, only rotated.
   *
   * @example Subscribe an endpoint to events
   * const created = await bird.webhooks.create({
   *   url: "https://acme.com/hooks/bird",
   *   events: ["email.delivered", "email.bounced"],
   *   description: "Delivery pipeline",
   * });
   * console.log(created.id, created.secret);
   */
  create(params: WebhooksCreateParams, options?: RequestOptions): APIPromise<WebhookEndpointCreated> {
    return this.call<WebhookEndpointCreated>("POST", options, ({ signal, headers }) =>
      createWebhook({ client: this.client, body: params, headers, signal }));
  }

  /**
   * Send a signed synthetic event and get the outcome synchronously: whether the endpoint accepted, the HTTP status it returned, and the round-trip latency. An unreachable endpoint comes back as a failed status in the body rather than a request error. The receiver has 10 seconds, the body is a minimal stub carrying only the event type, and a test reaches even a paused endpoint without being recorded in the delivery attempts.
   *
   * @example Send a test event to an endpoint
   * const result = await bird.webhooks.test("whk_01krdgeqcxet5s7t44vh8rt9mg", {
   *   event_type: "email.delivered",
   * });
   * console.log(result.status);
   */
  test(webhookId: string, params: WebhooksTestParams = {}, options?: RequestOptions): APIPromise<WebhookTestResponse> {
    return this.call<WebhookTestResponse>("POST", options, ({ signal, headers }) =>
      testWebhook({ client: this.client, path: { webhook_id: webhookId }, body: params, headers, signal }));
  }

  /**
   * Permanently remove an endpoint and stop every delivery to it, including retries of earlier failures. Recreating it later mints a new ID and signing secret; to stop deliveries temporarily instead, set its status to `paused`.
   *
   * @example Stop delivery to an endpoint
   * await bird.webhooks.delete("whk_01krdgeqcxet5s7t44vh8rt9mg");
   */
  delete(webhookId: string, options?: RequestOptions): APIPromise<void> {
    return this.call<void>("DELETE", options, ({ signal, headers }) =>
      deleteWebhook({ client: this.client, path: { webhook_id: webhookId }, headers, signal }));
  }

  /**
   * List an endpoint's recent delivery attempts, newest first. Each entry is one HTTP request, so a retried event appears once per try. Pagination uses the `before`/`after` timestamps; page further back by passing the oldest `attempted_at` you received as `before`.
   *
   * @example Inspect recent delivery attempts
   * const attempts = await bird.webhooks.attempts(
   *   "whk_01krdgeqcxet5s7t44vh8rt9mg",
   * );
   * for (const attempt of attempts.data) {
   *   console.log(attempt.status, attempt.response_status_code);
   * }
   */
  attempts(webhookId: string, query?: WebhooksAttemptsQuery, options?: RequestOptions): APIPromise<WebhookAttemptList> {
    return this.call<WebhookAttemptList>("GET", options, ({ signal, headers }) =>
      listWebhookAttempts({ client: this.client, path: { webhook_id: webhookId }, query, headers, signal }));
  }

  /**
   * Mint a new signing secret and return it exactly once; it cannot be retrieved afterward. Both the old and new secrets sign every delivery for 24 hours, after which the old one stops signing. An endpoint holds at most 5 valid secrets, so rotating repeatedly inside that window fails.
   *
   * @example Rotate an endpoint's signing secret
   * const rotated = await bird.webhooks.rotateSecret(
   *   "whk_01krdgeqcxet5s7t44vh8rt9mg",
   * );
   * console.log(rotated.secret);
   */
  rotateSecret(webhookId: string, options?: RequestOptions): APIPromise<WebhookRotateSecretResponse> {
    return this.call<WebhookRotateSecretResponse>("POST", options, ({ signal, headers }) =>
      rotateWebhookSecret({ client: this.client, path: { webhook_id: webhookId }, headers, signal }));
  }

  /**
   * Change an endpoint's URL, description, subscribed event types, or delivery status. Only the fields sent change: `events` replaces the whole subscription set, and `status` pauses or re-enables delivery. Events fired while paused are not delivered.
   *
   * @example Change the subscribed event types
   * const endpoint = await bird.webhooks.update("whk_01krdgeqcxet5s7t44vh8rt9mg", {
   *   events: ["email.delivered"],
   * });
   * console.log(endpoint.events);
   */
  update(webhookId: string, params: WebhooksUpdateParams = {}, options?: RequestOptions): APIPromise<WebhookEndpoint> {
    return this.call<WebhookEndpoint>("PATCH", options, ({ signal, headers }) =>
      updateWebhook({ client: this.client, path: { webhook_id: webhookId }, body: params, headers, signal }));
  }
}
