// Code generated by surface-gen; DO NOT EDIT.
import { createWhatsAppKeywordRule, deleteWhatsAppKeywordRule, getWhatsAppKeywordRule, listWhatsAppKeywordRules, updateWhatsAppKeywordRule } from "../generated/sdk.gen.js";
import type { CreateWhatsAppKeywordRuleData, DeleteWhatsAppKeywordRuleData, GetWhatsAppKeywordRuleData, ListWhatsAppKeywordRulesData, UpdateWhatsAppKeywordRuleData, WhatsAppKeywordRule, WhatsAppKeywordRuleList } from "../generated/types.gen.js";
import { Resource } from "./base.js";
import type { APIPromise, RequestOptions } from "../core/result.js";

export type { WhatsAppKeywordRuleList };
export type { WhatsAppKeywordRule };
export type WhatsappKeywordRulesListQuery = NonNullable<ListWhatsAppKeywordRulesData["query"]>;
export type WhatsappKeywordRulesCreateParams = NonNullable<CreateWhatsAppKeywordRuleData["body"]>;
export type WhatsappKeywordRulesUpdateParams = NonNullable<UpdateWhatsAppKeywordRuleData["body"]>;

export class WhatsappKeywordRulesResource extends Resource {
  /**
   * List the keyword rules that apply to inbound WhatsApp messages, most specific first. Filter by `country`, `waba`, `operation`, or `scope`. Opt-out and opt-in work with no setup, so this returns Bird's own rules even before the workspace has configured anything.
   *
   * @example See what a STOP reply does
   * const rules = await bird.whatsapp.keywordRules.list({ operation: "opt_out" });
   * for (const rule of rules.data ?? []) {
   *   console.log(rule.scope, rule.effective_keywords);
   * }
   */
  list(query?: WhatsappKeywordRulesListQuery, options?: RequestOptions): APIPromise<WhatsAppKeywordRuleList> {
    return this.call<WhatsAppKeywordRuleList>("GET", options, ({ signal, headers }) =>
      listWhatsAppKeywordRules({ client: this.client, query, headers, signal }));
  }

  /**
   * Read one keyword rule, Bird's own or your workspace's. Its `scope` says which: a `workspace` rule can be changed with `whatsapp.keyword_rules.update`, one of Bird's cannot.
   *
   * @example Read one rule
   * // Bird's rules and yours share the `wkr_` id space; `scope` tells them apart.
   * const rule = await bird.whatsapp.keywordRules.get("wkr_01m2kj8x4te9p0rr7e5w2n1abc");
   * console.log(rule.scope, rule.reply);
   */
  get(id: string, options?: RequestOptions): APIPromise<WhatsAppKeywordRule> {
    return this.call<WhatsAppKeywordRule>("GET", options, ({ signal, headers }) =>
      getWhatsAppKeywordRule({ client: this.client, path: { id: id }, headers, signal }));
  }

  /**
   * Replace the reply Bird sends for opt-out or opt-in, or add keywords of your own. Your rule takes precedence over Bird's at the same grain and keeps Bird's keywords unless you add more. A keyword Bird has bound to one operation cannot be reused for the other.
   *
   * @example Override Bird's opt-out reply
   * const rule = await bird.whatsapp.keywordRules.create({
   *   operation: "opt_out",
   *   country: "US", // the SENDER's country, from their own number
   *   reply: "You're off the list. ACME Courier won't message you again.",
   * });
   * // effective_keywords is Bird's set plus any of your own.
   * console.log(rule.id, rule.effective_keywords);
   */
  create(params: WhatsappKeywordRulesCreateParams, options?: RequestOptions): APIPromise<WhatsAppKeywordRule> {
    return this.call<WhatsAppKeywordRule>("POST", options, ({ signal, headers }) =>
      createWhatsAppKeywordRule({ client: this.client, body: params, headers, signal }));
  }

  /**
   * Change one of your own keyword rules: its reply or its extra keywords. Bird's own rules cannot be changed; create your own instead with `whatsapp.keyword_rules.create`. Omitting `keywords` leaves the set alone, while sending an empty list clears your additions back to Bird's.
   *
   * @example Change a rule you created
   * // Omitting keywords leaves the set alone; an empty array clears your additions
   * // back to Bird's. reply: null switches the auto-reply off and still records
   * // the opt-out.
   * const rule = await bird.whatsapp.keywordRules.update("wkr_01m2kj8x4te9p0rr7e5w2n1abc", {
   *   keywords: ["no more texts", "remove me"],
   * });
   * console.log(rule.effective_keywords);
   */
  update(id: string, params: WhatsappKeywordRulesUpdateParams = {}, options?: RequestOptions): APIPromise<WhatsAppKeywordRule> {
    return this.call<WhatsAppKeywordRule>("PATCH", options, ({ signal, headers }) =>
      updateWhatsAppKeywordRule({ client: this.client, path: { id: id }, body: params, headers, signal }));
  }

  /**
   * Delete one of your own keyword rules. The next rule in the ladder answers that scope instead, which is not always one of yours: Bird's rule for the sender's country outranks your worldwide rule. The keywords the deleted rule added go with it, so a word only it matched stops matching. List the rules to read the order. Bird's rules cannot be deleted.
   *
   * @example Drop your override
   * // The next rule in the ladder answers the scope, which is another rule of yours if you hold a less specific one; STOP never stops working.
   * await bird.whatsapp.keywordRules.delete("wkr_01m2kj8x4te9p0rr7e5w2n1abc");
   */
  delete(id: string, options?: RequestOptions): APIPromise<void> {
    return this.call<void>("DELETE", options, ({ signal, headers }) =>
      deleteWhatsAppKeywordRule({ client: this.client, path: { id: id }, headers, signal }));
  }
}
