// Code generated by surface-gen; DO NOT EDIT.
import { approveWhatsAppGroupJoinRequests, listWhatsAppGroupJoinRequests, rejectWhatsAppGroupJoinRequests } from "../generated/sdk.gen.js";
import type { ApproveWhatsAppGroupJoinRequestsData, ListWhatsAppGroupJoinRequestsData, RejectWhatsAppGroupJoinRequestsData, WhatsAppGroupJoinRequest, WhatsAppGroupJoinRequestDecisionResult } from "../generated/types.gen.js";
import { Resource } from "./base.js";
import type { APIPromise, PaginatedPromise, RequestOptions } from "../core/result.js";

export type { WhatsAppGroupJoinRequest };
export type { WhatsAppGroupJoinRequestDecisionResult };
export type WhatsappGroupsJoinRequestsListQuery = NonNullable<ListWhatsAppGroupJoinRequestsData["query"]>;
export type WhatsappGroupsJoinRequestsApproveParams = NonNullable<ApproveWhatsAppGroupJoinRequestsData["body"]>;
export type WhatsappGroupsJoinRequestsRejectParams = NonNullable<RejectWhatsAppGroupJoinRequestsData["body"]>;

export class WhatsappGroupsJoinRequestsResource extends Resource {
  /**
   * List the people waiting to be let into a group, oldest first, as a cursor page. Only a group created with join_approval_mode approval_required collects them. Decide them with the batch-approve and batch-reject operations.
   *
   * @example See who is waiting to get in
   * for await (const request of bird.whatsapp.groups.joinRequests.list(
   *   "wag_01krdgeqcxet5s7t44vh8rt9mg",
   * )) {
   *   console.log(request.id, request.bsuid);
   * }
   */
  list(groupId: string, query?: WhatsappGroupsJoinRequestsListQuery, options?: RequestOptions): PaginatedPromise<WhatsAppGroupJoinRequest> {
    return this.paginated<WhatsAppGroupJoinRequest>("GET", options, ({ signal, headers }, cursor) =>
      listWhatsAppGroupJoinRequests({ client: this.client, path: { group_id: groupId }, query: { ...query, starting_after: cursor ?? query?.starting_after, ending_before: cursor === undefined ? query?.ending_before : undefined }, headers, signal }));
  }

  /**
   * Approve up to 50 pending join requests in one call. WhatsApp decides each one on its own, so the response splits them into decided and failed; a failure on one leaves the rest applied.
   *
   * @example Approve a batch of join requests
   * const result = await bird.whatsapp.groups.joinRequests.approve(
   *   "wag_01krdgeqcxet5s7t44vh8rt9mg",
   *   { join_request_ids: ["wgj_01krdgeqcxet5s7t44vh8rt9mg"] },
   * );
   * console.log(result.decided.length, result.failed.length);
   */
  approve(groupId: string, params: WhatsappGroupsJoinRequestsApproveParams, options?: RequestOptions): APIPromise<WhatsAppGroupJoinRequestDecisionResult> {
    return this.call<WhatsAppGroupJoinRequestDecisionResult>("POST", options, ({ signal, headers }) =>
      approveWhatsAppGroupJoinRequests({ client: this.client, path: { group_id: groupId }, body: params, headers, signal }));
  }

  /**
   * Reject up to 50 pending join requests in one call. WhatsApp decides each one on its own, so the response splits them into decided and failed; a failure on one leaves the rest applied. A group that is not active refuses the whole call with a 409 WhatsAppGroupNotActive.
   *
   * @example Reject a batch, reading the refusals
   * const result = await bird.whatsapp.groups.joinRequests.reject(
   *   "wag_01krdgeqcxet5s7t44vh8rt9mg",
   *   { join_request_ids: ["wgj_01krdgeqcxet5s7t44vh8rt9mg"] },
   * );
   * for (const failure of result.failed) {
   *   console.log(failure.join_request_id, failure.error.description);
   * }
   */
  reject(groupId: string, params: WhatsappGroupsJoinRequestsRejectParams, options?: RequestOptions): APIPromise<WhatsAppGroupJoinRequestDecisionResult> {
    return this.call<WhatsAppGroupJoinRequestDecisionResult>("POST", options, ({ signal, headers }) =>
      rejectWhatsAppGroupJoinRequests({ client: this.client, path: { group_id: groupId }, body: params, headers, signal }));
  }
}
