// Code generated by surface-gen; DO NOT EDIT.
import { getWhatsAppTemplateVersion, listWhatsAppTemplateVersions } from "../generated/sdk.gen.js";
import type { GetWhatsAppTemplateVersionData, ListWhatsAppTemplateVersionsData, WhatsAppTemplateVersion, WhatsAppTemplateVersionSummary } from "../generated/types.gen.js";
import { Resource } from "./base.js";
import type { APIPromise, PaginatedPromise, RequestOptions } from "../core/result.js";

export type { WhatsAppTemplateVersionSummary };
export type { WhatsAppTemplateVersion };
export type WhatsappTemplatesVersionsListQuery = NonNullable<ListWhatsAppTemplateVersionsData["query"]>;

export class WhatsappTemplatesVersionsResourceBase extends Resource {
  /**
   * List a WhatsApp template's versions, newest first. Each version is one immutable submission; an open draft, if one exists, appears alongside them. Use this to find the version a send resolves to, or the draft still being edited.
   *
   * @example Walk a template's submissions
   * for await (const version of bird.whatsapp.templates.versions.list("bird_otp")) {
   *   console.log(version.id, version.version_number);
   * }
   */
  list(templateRef: string, query?: WhatsappTemplatesVersionsListQuery, options?: RequestOptions): PaginatedPromise<WhatsAppTemplateVersionSummary> {
    return this.paginated<WhatsAppTemplateVersionSummary>("GET", options, ({ signal, headers }, cursor) =>
      listWhatsAppTemplateVersions({ client: this.client, path: { template_ref: templateRef }, query: { ...query, starting_after: cursor ?? query?.starting_after }, headers, signal }));
  }

  /**
   * Get one version of a WhatsApp template: its submission state and the languages it carries. This is the level at which content exists.
   *
   * @example Read one version of a template
   * const version = await bird.whatsapp.templates.versions.get(
   *   "bird_otp",
   *   "wav_01ky4x8e4genzb7way45txfkm1",
   * );
   * console.log(version.id, Object.keys(version.languages));
   */
  get(templateRef: string, versionId: string, options?: RequestOptions): APIPromise<WhatsAppTemplateVersion> {
    return this.call<WhatsAppTemplateVersion>("GET", options, ({ signal, headers }) =>
      getWhatsAppTemplateVersion({ client: this.client, path: { template_ref: templateRef, version_id: versionId }, headers, signal }));
  }
}
