// Code generated by surface-gen; DO NOT EDIT.
import { createWhatsAppSuppression, deleteWhatsAppSuppression, getWhatsAppSuppression, listWhatsAppSuppressions } from "../generated/sdk.gen.js";
import type { CreateWhatsAppSuppressionData, DeleteWhatsAppSuppressionData, GetWhatsAppSuppressionData, ListWhatsAppSuppressionsData, WhatsAppSuppression } from "../generated/types.gen.js";
import { Resource } from "./base.js";
import type { APIPromise, PaginatedPromise, RequestOptions } from "../core/result.js";

export type { WhatsAppSuppression };
export type WhatsappSuppressionsListQuery = NonNullable<ListWhatsAppSuppressionsData["query"]>;
export type WhatsappSuppressionsAddParams = NonNullable<CreateWhatsAppSuppressionData["body"]>;

export class WhatsappSuppressionsResource extends Resource {
  /**
   * List the workspace's recorded WhatsApp suppression addresses as a cursor page.
   *
   * @example See who you will not message
   * // address is a prefix, so a partial value matches every address under it.
   * const suppressions = await bird.whatsapp.suppressions.list({ address: "+1555" });
   * for (const suppression of suppressions.data ?? []) {
   *   console.log(suppression.address, suppression.waba ?? "every account");
   * }
   */
  list(query?: WhatsappSuppressionsListQuery, options?: RequestOptions): PaginatedPromise<WhatsAppSuppression> {
    return this.paginated<WhatsAppSuppression>("GET", options, ({ signal, headers }, cursor) =>
      listWhatsAppSuppressions({ client: this.client, query: { ...query, starting_after: cursor ?? query?.starting_after, ending_before: cursor === undefined ? query?.ending_before : undefined }, headers, signal }));
  }

  /**
   * Read one WhatsApp suppression by ID, including one that has already ended. An ended record reports when it ended and what ended it. To find a suppression by address rather than by ID, use `whatsapp.suppressions.list` with its address filter.
   *
   * @example Read one suppression
   * // Resolves a record that has already ended, which the list leaves out.
   * const suppression = await bird.whatsapp.suppressions.get("was_01krdgeqcxet5s7t44vh8rt9mg");
   * console.log(suppression.reason, suppression.ended_at ?? "still in force");
   */
  get(suppressionId: string, options?: RequestOptions): APIPromise<WhatsAppSuppression> {
    return this.call<WhatsAppSuppression>("GET", options, ({ signal, headers }) =>
      getWhatsAppSuppression({ client: this.client, path: { suppression_id: suppressionId }, headers, signal }));
  }

  /**
   * Record a WhatsApp address on the workspace suppression list.
   *
   * @example Stop messaging an address
   * // Omit waba to block the address for the whole workspace, whichever account
   * // sends. With it, your other accounts keep reaching them, and the same
   * // address for two accounts is two records.
   * const suppression = await bird.whatsapp.suppressions.add({
   *   address: "+15550001234",
   *   waba: "102290129340398",
   * });
   * console.log(suppression.id, suppression.applies_to);
   */
  add(params: WhatsappSuppressionsAddParams, options?: RequestOptions): APIPromise<WhatsAppSuppression> {
    return this.call<WhatsAppSuppression>("POST", options, ({ signal, headers }) =>
      createWhatsAppSuppression({ client: this.client, body: params, headers, signal }));
  }

  /**
   * End one WhatsApp suppression by ID. The record is kept and stays readable. Only suppressions with reason `manual` can be ended; a recipient's own opt-out is refused.
   *
   * @example Message an address again
   * // Only a manual suppression can be ended; a recipient's own opt-out is
   * // theirs to reverse. The record is kept and still reads back by id.
   * await bird.whatsapp.suppressions.remove("was_01krdgeqcxet5s7t44vh8rt9mg");
   */
  remove(suppressionId: string, options?: RequestOptions): APIPromise<void> {
    return this.call<void>("DELETE", options, ({ signal, headers }) =>
      deleteWhatsAppSuppression({ client: this.client, path: { suppression_id: suppressionId }, headers, signal }));
  }
}
