// Code generated by surface-gen; DO NOT EDIT.
import { deleteWhatsAppGroupParticipant } from "../generated/sdk.gen.js";
import type { DeleteWhatsAppGroupParticipantData, WhatsAppGroup } from "../generated/types.gen.js";
import { Resource } from "./base.js";
import type { APIPromise, RequestOptions } from "../core/result.js";
import type { FetchOutcome } from "../core/http.js";

export type { WhatsAppGroup };

export class WhatsappGroupsParticipantsResource extends Resource {
  /**
   * Remove one person from a group, named by their business-scoped user ID or their phone number. IRREVERSIBLE: WhatsApp blocks a removed person from rejoining by invite link at all, and there is no add operation, so nothing puts them back in this group. Rotating the link does not lift it, and reaching that person again means a new group.
   *
   * @example Remove someone, permanently
   * const group = await bird.whatsapp.groups.participants.remove(
   *   "wag_01krdgeqcxet5s7t44vh8rt9mg",
   *   "BR.1566655121691972",
   * );
   * console.log(group.participants?.length);
   */
  remove(groupId: string, participantRef: string, options?: RequestOptions): APIPromise<WhatsAppGroup> {
    return this.call<WhatsAppGroup>("DELETE", options, ({ signal, headers }) =>
      deleteWhatsAppGroupParticipant({ client: this.client, path: { group_id: groupId, participant_ref: participantRef }, headers, signal }));
  }
}
