// Code generated by surface-gen; DO NOT EDIT.
import { getWhatsAppStatsByCountry, getWhatsAppStatsByErrorCode, getWhatsAppStatsByPhoneNumber, getWhatsAppStatsByTag, getWhatsAppStatsByTemplate, getWhatsAppStatsByTemplateCategory, getWhatsAppStatsDaily, getWhatsAppStatsHourly, getWhatsAppStatsSummary } from "../generated/sdk.gen.js";
import type { GetWhatsAppStatsByCountryData, GetWhatsAppStatsByErrorCodeData, GetWhatsAppStatsByPhoneNumberData, GetWhatsAppStatsByTagData, GetWhatsAppStatsByTemplateCategoryData, GetWhatsAppStatsByTemplateData, GetWhatsAppStatsDailyData, GetWhatsAppStatsHourlyData, GetWhatsAppStatsSummaryData, WhatsAppStatsByCountryResponse, WhatsAppStatsByErrorCodeResponse, WhatsAppStatsByPhoneNumberResponse, WhatsAppStatsByTagResponse, WhatsAppStatsByTemplateCategoryResponse, WhatsAppStatsByTemplateResponse, WhatsAppStatsResponse, WhatsAppStatsSummary } from "../generated/types.gen.js";
import { Resource } from "./base.js";
import type { APIPromise, RequestOptions } from "../core/result.js";

export type { WhatsAppStatsSummary };
export type { WhatsAppStatsResponse };
export type { WhatsAppStatsByErrorCodeResponse };
export type { WhatsAppStatsByTemplateResponse };
export type { WhatsAppStatsByTemplateCategoryResponse };
export type { WhatsAppStatsByTagResponse };
export type { WhatsAppStatsByPhoneNumberResponse };
export type { WhatsAppStatsByCountryResponse };
export type WhatsappStatsSummaryQuery = NonNullable<GetWhatsAppStatsSummaryData["query"]>;
export type WhatsappStatsDailyQuery = NonNullable<GetWhatsAppStatsDailyData["query"]>;
export type WhatsappStatsHourlyQuery = NonNullable<GetWhatsAppStatsHourlyData["query"]>;
export type WhatsappStatsByErrorCodeQuery = NonNullable<GetWhatsAppStatsByErrorCodeData["query"]>;
export type WhatsappStatsByTemplateQuery = NonNullable<GetWhatsAppStatsByTemplateData["query"]>;
export type WhatsappStatsByTemplateCategoryQuery = NonNullable<GetWhatsAppStatsByTemplateCategoryData["query"]>;
export type WhatsappStatsByTagQuery = NonNullable<GetWhatsAppStatsByTagData["query"]>;
export type WhatsappStatsByPhoneNumberQuery = NonNullable<GetWhatsAppStatsByPhoneNumberData["query"]>;
export type WhatsappStatsByCountryQuery = NonNullable<GetWhatsAppStatsByCountryData["query"]>;

export class WhatsappStatsResourceBase extends Resource {
  /**
   * Aggregate outbound WhatsApp counts for one window: accepted, sent, delivered, failed and rejected, with delivery and failure rates, read engagement, and processing and end-to-end latency percentiles. Restrict it to one dimension with `template`, `category`, `phone_number` or `tag`, one at a time, not combined. Set `compare` to `previous_period` for the deltas against the window immediately before. `from` and `to` are optional and default to the trailing 30 days. Counts are attributed to the time each message was accepted, so a delivery confirmed today counts against the day its message was accepted; `period.data_as_of` is the freshness boundary the rollups have reached.
   *
   * @example Aggregate KPIs for a window
   * const summary = await bird.whatsapp.stats.summary({
   *   from: "2026-08-01",
   *   to: "2026-08-31",
   *   timezone: "Europe/Amsterdam",
   * });
   * console.log(summary.delivery, summary.latency);
   */
  summary(query?: WhatsappStatsSummaryQuery, options?: RequestOptions): APIPromise<WhatsAppStatsSummary> {
    return this.call<WhatsAppStatsSummary>("GET", options, ({ signal, headers }) =>
      getWhatsAppStatsSummary({ client: this.client, query, headers, signal }));
  }

  /**
   * Outbound WhatsApp lifecycle counts, one row per calendar day of the window, gap-filled so a silent day is a zero row rather than a missing one. Every event a message produces counts against the day that message was accepted, so a row is a funnel over that day's sends and recent rows under-report while callbacks arrive. Each row carries its own latency percentiles, but delivery, failure and read rates are whole-window figures: read those from `whatsapp.stats.summary`. Accepts the same single-dimension restriction: `template`, `category`, `phone_number` or `tag`. Days are calendar days in `timezone`, or UTC when it is omitted. Max window 365 days; `from` and `to` default to the trailing 30 days.
   *
   * @example One row per calendar day
   * const stats = await bird.whatsapp.stats.daily({ from: "2026-08-01", to: "2026-08-31" });
   * for (const point of stats.data ?? []) {
   *   console.log(point.bucket, point.delivery);
   * }
   */
  daily(query?: WhatsappStatsDailyQuery, options?: RequestOptions): APIPromise<WhatsAppStatsResponse> {
    return this.call<WhatsAppStatsResponse>("GET", options, ({ signal, headers }) =>
      getWhatsAppStatsDaily({ client: this.client, query, headers, signal }));
  }

  /**
   * Outbound WhatsApp lifecycle counts, one row per hour, gap-filled. Every event a message produces counts against the hour that message was accepted, so a row is a funnel over that hour's sends and recent rows under-report while callbacks arrive. Each row carries its own latency percentiles, but delivery, failure and read rates are whole-window figures: read those from `whatsapp.stats.summary`. Use it where the daily grain hides the shape; a window spans at most 720 hours (30 days), and for anything longer use `whatsapp.stats.daily`. Accepts the same single-dimension restriction: `template`, `category`, `phone_number` or `tag`. `from` and `to` are optional RFC 3339 instants, defaulting to the trailing 168 hours.
   *
   * @example One row per hour, up to 30 days
   * const stats = await bird.whatsapp.stats.hourly({
   *   from: "2026-08-30T00:00:00Z",
   *   to: "2026-08-31T00:00:00Z",
   * });
   * for (const point of stats.data ?? []) {
   *   console.log(point.bucket, point.delivery);
   * }
   */
  hourly(query?: WhatsappStatsHourlyQuery, options?: RequestOptions): APIPromise<WhatsAppStatsResponse> {
    return this.call<WhatsAppStatsResponse>("GET", options, ({ signal, headers }) =>
      getWhatsAppStatsHourly({ client: this.client, query, headers, signal }));
  }

  /**
   * Failed outbound WhatsApp messages grouped by the normalized failure reason, the same value a failed message reports in `last_error.code`, ranked by volume. This is the read that answers "why are sends failing"; `whatsapp.stats.summary` gives the failure rate, this gives its composition. A send declined before handoff (insufficient balance, missing price, suppressed recipient) counts as rejected rather than failed and is absent here; read `delivery.rejected` on `whatsapp.stats.summary` for it. Rows are the whole workspace's: the breakdown takes no dimension filter. Cap the rows with `limit` (default 50, max 200).
   *
   * @example Which reasons drive failures
   * const stats = await bird.whatsapp.stats.byErrorCode({ from: "2026-08-01", to: "2026-08-31" });
   * for (const row of stats.data ?? []) {
   *   console.log(row.error_code, row.count);
   * }
   */
  byErrorCode(query?: WhatsappStatsByErrorCodeQuery, options?: RequestOptions): APIPromise<WhatsAppStatsByErrorCodeResponse> {
    return this.call<WhatsAppStatsByErrorCodeResponse>("GET", options, ({ signal, headers }) =>
      getWhatsAppStatsByErrorCode({ client: this.client, query, headers, signal }));
  }

  /**
   * Outbound WhatsApp counts grouped by template, keyed by `template_id`, ranked by accepted volume. Resolve the id through the WhatsApp template endpoints for a name. Rows sum to less than the period's accepted total: a free-form send resolves no template, and some volume cannot be attributed to one at all, so take the denominator from `whatsapp.stats.summary`. Rows are the whole workspace's: the breakdown takes no dimension filter; to see one template over time, filter `whatsapp.stats.daily` by `template` instead. Cap the rows with `limit` (default 50, max 200).
   *
   * @example Rank templates by accepted volume
   * const stats = await bird.whatsapp.stats.byTemplate({ from: "2026-08-01", to: "2026-08-31" });
   * for (const row of stats.data ?? []) {
   *   console.log(row.template_id, row.delivery);
   * }
   */
  byTemplate(query?: WhatsappStatsByTemplateQuery, options?: RequestOptions): APIPromise<WhatsAppStatsByTemplateResponse> {
    return this.call<WhatsAppStatsByTemplateResponse>("GET", options, ({ signal, headers }) =>
      getWhatsAppStatsByTemplate({ client: this.client, query, headers, signal }));
  }

  /**
   * Outbound WhatsApp counts grouped by Meta's template category (`authentication`, `utility` and `marketing` today, and the vocabulary is open), ranked by accepted volume. Category is what WhatsApp prices a message on, so this is the breakdown that explains a spend change. A free-form send carries no category, so rows sum to less than the period's accepted total; take the denominator from `whatsapp.stats.summary`. Rows are the whole workspace's: the breakdown takes no dimension filter. Cap the rows with `limit` (default 50, max 200).
   *
   * @example Group by Meta's template category
   * const stats = await bird.whatsapp.stats.byTemplateCategory({ from: "2026-08-01", to: "2026-08-31" });
   * for (const row of stats.data ?? []) {
   *   console.log(row.category, row.delivery);
   * }
   */
  byTemplateCategory(query?: WhatsappStatsByTemplateCategoryQuery, options?: RequestOptions): APIPromise<WhatsAppStatsByTemplateCategoryResponse> {
    return this.call<WhatsAppStatsByTemplateCategoryResponse>("GET", options, ({ signal, headers }) =>
      getWhatsAppStatsByTemplateCategory({ client: this.client, query, headers, signal }));
  }

  /**
   * Outbound WhatsApp counts grouped by the tags a send attached, ranked by accepted volume. A row's tag is `name:value`, so one tag name spreads over as many rows as it has values. Rows are the whole workspace's: the breakdown takes no dimension filter; to see one tag over time, filter `whatsapp.stats.daily` by `tag` instead. Cap the rows with `limit` (default 50, max 200).
   *
   * @example Compare campaigns and segments
   * const stats = await bird.whatsapp.stats.byTag({ from: "2026-08-01", to: "2026-08-31" });
   * for (const row of stats.data ?? []) {
   *   console.log(row.tag, row.delivery);
   * }
   */
  byTag(query?: WhatsappStatsByTagQuery, options?: RequestOptions): APIPromise<WhatsAppStatsByTagResponse> {
    return this.call<WhatsAppStatsByTagResponse>("GET", options, ({ signal, headers }) =>
      getWhatsAppStatsByTag({ client: this.client, query, headers, signal }));
  }

  /**
   * Outbound WhatsApp counts grouped by the business number that sent them, ranked by accepted volume, each row marked as a number your workspace connected or one Bird manages on your behalf. Use it to find the sender behind a delivery problem: a row identifies the number in E.164 form. Rows are the whole workspace's: the breakdown takes no dimension filter.
   *
   * @example Compare how each sender number performs
   * const stats = await bird.whatsapp.stats.byPhoneNumber({ from: "2026-08-01", to: "2026-08-31" });
   * for (const row of stats.data ?? []) {
   *   console.log(row.phone_number, row.delivery);
   * }
   */
  byPhoneNumber(query?: WhatsappStatsByPhoneNumberQuery, options?: RequestOptions): APIPromise<WhatsAppStatsByPhoneNumberResponse> {
    return this.call<WhatsAppStatsByPhoneNumberResponse>("GET", options, ({ signal, headers }) =>
      getWhatsAppStatsByPhoneNumber({ client: this.client, query, headers, signal }));
  }

  /**
   * Outbound WhatsApp delivery, read and latency stats grouped by the recipient's country, ranked by accepted volume. Use it to compare markets. A weak market cannot be narrowed further: no breakdown takes a country filter, so `whatsapp.stats.by_error_code` reports the workspace's failure reasons rather than the selected country's, and pairing the two is inference, not attribution. A recipient whose country cannot be resolved is counted under `ZZ`, so one-to-one sends always land somewhere. Group sends are the exception and are absent by design: one spans up to eight countries and has no single destination, so rows sum to `whatsapp.stats.summary` less that group volume. Do not report the difference as missing data. Rows are the whole workspace's: the breakdown takes no dimension filter.
   *
   * @example Compare destination markets
   * const stats = await bird.whatsapp.stats.byCountry({ from: "2026-08-01", to: "2026-08-31" });
   * for (const row of stats.data ?? []) {
   *   console.log(row.country, row.delivery);
   * }
   */
  byCountry(query?: WhatsappStatsByCountryQuery, options?: RequestOptions): APIPromise<WhatsAppStatsByCountryResponse> {
    return this.call<WhatsAppStatsByCountryResponse>("GET", options, ({ signal, headers }) =>
      getWhatsAppStatsByCountry({ client: this.client, query, headers, signal }));
  }
}
