// Code generated by surface-gen; DO NOT EDIT.
import { getWhatsAppMessage, listWhatsAppMessageEvents, listWhatsAppMessages } from "../generated/sdk.gen.js";
import type { GetWhatsAppMessageData, ListWhatsAppMessageEventsData, ListWhatsAppMessagesData, WhatsAppEventList, WhatsAppMessage } from "../generated/types.gen.js";
import { Resource } from "./base.js";
import type { APIPromise, PaginatedPromise, RequestOptions } from "../core/result.js";

export type { WhatsAppMessage };
export type { WhatsAppEventList };
export type WhatsappListQuery = NonNullable<ListWhatsAppMessagesData["query"]>;
export type WhatsappListEventsQuery = NonNullable<ListWhatsAppMessageEventsData["query"]>;

export class WhatsappResourceBase extends Resource {
  /**
   * Get one WhatsApp message by id: current delivery status, sent/delivered/read timestamps, the one content it was built from (a template, or free-form text, image, video, audio, sticker, document or location), and failure detail if it failed. For the per-event timeline use whatsapp_list_events.
   *
   * @example Read a message back
   * const msg = await bird.whatsapp.get("wa_abc123");
   * msg.status; // "accepted" | "delivered" | …
   */
  get(messageId: string, options?: RequestOptions): APIPromise<WhatsAppMessage> {
    return this.call<WhatsAppMessage>("GET", options, ({ signal, headers }) =>
      getWhatsAppMessage({ client: this.client, path: { message_id: messageId }, headers, signal }));
  }

  /**
   * List WhatsApp messages, newest first, as a cursor page ({data, next_cursor, …}). Each message carries the one content it was built from: a template, or free-form text, image, video, audio, sticker, document or location. Pass next_cursor back as starting_after to fetch the next page. Filter by direction, status, contact phone number, bsuid, template category, or tag. Use whatsapp_get for one message's current state.
   *
   * @example Iterate delivered messages
   * for await (const msg of bird.whatsapp.list({ status: ["delivered"] })) {
   *   console.log(msg.id, msg.status);
   * }
   */
  list(query?: WhatsappListQuery, options?: RequestOptions): PaginatedPromise<WhatsAppMessage> {
    return this.paginated<WhatsAppMessage>("GET", options, ({ signal, headers }, cursor) =>
      listWhatsAppMessages({ client: this.client, query: { ...query, starting_after: cursor ?? query?.starting_after }, headers, signal }));
  }

  /**
   * Get one WhatsApp message's delivery timeline, oldest first: whatsapp.accepted, whatsapp.sent, whatsapp.delivered, whatsapp.read, and whatsapp.failed events, with failure detail on failed events. Not paginated; an unknown message ID returns `404`. Use `whatsapp.get` for the condensed current status.
   *
   * @example Read one message's delivery timeline
   * const { data } = await bird.whatsapp.listEvents("wa_abc123");
   * for (const event of data) console.log(event.type, event.occurred_at);
   */
  listEvents(messageId: string, query?: WhatsappListEventsQuery, options?: RequestOptions): APIPromise<WhatsAppEventList> {
    return this.call<WhatsAppEventList>("GET", options, ({ signal, headers }) =>
      listWhatsAppMessageEvents({ client: this.client, path: { message_id: messageId }, query, headers, signal }));
  }
}
