// Code generated by surface-gen; DO NOT EDIT.
import { getWhatsAppTemplate, listWhatsAppTemplates } from "../generated/sdk.gen.js";
import type { GetWhatsAppTemplateData, ListWhatsAppTemplatesData, WhatsAppTemplate } from "../generated/types.gen.js";
import { Resource } from "./base.js";
import type { APIPromise, PaginatedPromise, RequestOptions } from "../core/result.js";

export type { WhatsAppTemplate };
export type WhatsappTemplatesListQuery = NonNullable<ListWhatsAppTemplatesData["query"]>;

export class WhatsappTemplatesResourceBase extends Resource {
  /**
   * List the workspace's WhatsApp templates: each template's handle, its lifecycle, and where each of its languages stands. Content is not included; use `whatsapp.templates.versions.get` for that.
   *
   * @example Find the templates a send can name
   * for await (const tpl of bird.whatsapp.templates.list()) {
   *   console.log(tpl.slug, tpl.status, tpl.available_languages);
   * }
   */
  list(query?: WhatsappTemplatesListQuery, options?: RequestOptions): PaginatedPromise<WhatsAppTemplate> {
    return this.paginated<WhatsAppTemplate>("GET", options, ({ signal, headers }, cursor) =>
      listWhatsAppTemplates({ client: this.client, query: { ...query, starting_after: cursor ?? query?.starting_after }, headers, signal }));
  }

  /**
   * Get one WhatsApp template by slug or ID: its handle, its lifecycle, and where each of its languages stands. Content is not included; use `whatsapp.templates.versions.get` for that.
   *
   * @example Read one template by slug
   * const tpl = await bird.whatsapp.templates.get("bird_otp");
   * console.log(tpl.default_language, tpl.live_version_id);
   */
  get(templateRef: string, options?: RequestOptions): APIPromise<WhatsAppTemplate> {
    return this.call<WhatsAppTemplate>("GET", options, ({ signal, headers }) =>
      getWhatsAppTemplate({ client: this.client, path: { template_ref: templateRef }, headers, signal }));
  }
}
