// Code generated by surface-gen; DO NOT EDIT.
import { createWhatsAppGroupPinnedMessage, deleteWhatsAppGroupPinnedMessage } from "../generated/sdk.gen.js";
import type { CreateWhatsAppGroupPinnedMessageData, DeleteWhatsAppGroupPinnedMessageData, WhatsAppGroup, WhatsAppGroupPinnedMessage } from "../generated/types.gen.js";
import { Resource } from "./base.js";
import type { APIPromise, RequestOptions } from "../core/result.js";
import type { FetchOutcome } from "../core/http.js";

export type { WhatsAppGroupPinnedMessage };
export type { WhatsAppGroup };
export type WhatsappGroupsPinsCreateParams = NonNullable<CreateWhatsAppGroupPinnedMessageData["body"]>;

export class WhatsappGroupsPinsResource extends Resource {
  /**
   * Pin one of the group's messages at the top of its chat for 1 to 30 days. A group holds 3 pinned messages; pinning a fourth unpins the oldest. The group's pinned_messages carries what is pinned.
   *
   * @example Pin a message to the top of the chat
   * const pin = await bird.whatsapp.groups.pins.create("wag_01krdgeqcxet5s7t44vh8rt9mg", {
   *   message_id: "wam_01kya19eknftrs2s6p82asmvnh",
   * });
   * console.log(pin.pinned_until);
   */
  create(groupId: string, params: WhatsappGroupsPinsCreateParams, options?: RequestOptions): APIPromise<WhatsAppGroupPinnedMessage> {
    return this.call<WhatsAppGroupPinnedMessage>("POST", options, ({ signal, headers }) =>
      createWhatsAppGroupPinnedMessage({ client: this.client, path: { group_id: groupId }, body: params, headers, signal }));
  }

  /**
   * Unpin one of the group's messages before its pin expires. Repeating the call is safe: a message this group carries that is not pinned changes nothing and still answers 200. A message from another group returns a 422 WhatsAppMessageNotInGroup.
   *
   * @example Unpin a message early
   * const group = await bird.whatsapp.groups.pins.delete(
   *   "wag_01krdgeqcxet5s7t44vh8rt9mg",
   *   "wam_01kya19eknftrs2s6p82asmvnh",
   * );
   * console.log(group.pinned_messages?.length);
   */
  delete(groupId: string, messageId: string, options?: RequestOptions): APIPromise<WhatsAppGroup> {
    return this.call<WhatsAppGroup>("DELETE", options, ({ signal, headers }) =>
      deleteWhatsAppGroupPinnedMessage({ client: this.client, path: { group_id: groupId, message_id: messageId }, headers, signal }));
  }
}
