// Code generated by surface-gen; DO NOT EDIT.
import { getWhatsAppTemplateVersionLanguage, listWhatsAppTemplateVersionLanguages } from "../generated/sdk.gen.js";
import type { GetWhatsAppTemplateVersionLanguageData, ListWhatsAppTemplateVersionLanguagesData, WhatsAppTemplateLanguage, WhatsAppTemplateLanguageList } from "../generated/types.gen.js";
import { Resource } from "./base.js";
import type { APIPromise, RequestOptions } from "../core/result.js";

export type { WhatsAppTemplateLanguageList };
export type { WhatsAppTemplateLanguage };

export class WhatsappTemplatesVersionsLanguagesResource extends Resource {
  /**
   * List the languages one WhatsApp template version carries, with each language's review outcome at Meta and a content hash to tell which ones actually differ before fetching any of them. Use `whatsapp.templates.versions.languages.get` for a single language's content blocks.
   *
   * @example See which languages a version holds
   * const { data } = await bird.whatsapp.templates.versions.languages.list(
   *   "bird_otp",
   *   "wav_01ky4x8e4genzb7way45txfkm1",
   * );
   * for (const language of data) console.log(language.language, language.status);
   */
  list(templateRef: string, versionId: string, options?: RequestOptions): APIPromise<WhatsAppTemplateLanguageList> {
    return this.call<WhatsAppTemplateLanguageList>("GET", options, ({ signal, headers }) =>
      listWhatsAppTemplateVersionLanguages({ client: this.client, path: { template_ref: templateRef, version_id: versionId }, headers, signal }));
  }

  /**
   * Get one language of one WhatsApp template version: its content blocks, what this version's submission did with it, and Meta's review outcome and category for it.
   *
   * @example Read one language's content
   * const language = await bird.whatsapp.templates.versions.languages.get(
   *   "bird_otp",
   *   "wav_01ky4x8e4genzb7way45txfkm1",
   *   "nl-BE",
   * );
   * for (const component of language.components) console.log(component.type);
   */
  get(templateRef: string, versionId: string, language: string, options?: RequestOptions): APIPromise<WhatsAppTemplateLanguage> {
    return this.call<WhatsAppTemplateLanguage>("GET", options, ({ signal, headers }) =>
      getWhatsAppTemplateVersionLanguage({ client: this.client, path: { template_ref: templateRef, version_id: versionId, language: language }, headers, signal }));
  }
}
