// Code generated by surface-gen; DO NOT EDIT.
import { createWhatsAppAgentNotification, getWhatsAppAgentNotification, listWhatsAppAgentNotifications } from "../generated/sdk.gen.js";
import type { CreateWhatsAppAgentNotificationData, GetWhatsAppAgentNotificationData, ListWhatsAppAgentNotificationsData, WhatsAppAgentNotification } from "../generated/types.gen.js";
import { Resource } from "./base.js";
import type { APIPromise, PaginatedPromise, RequestOptions } from "../core/result.js";

export type { WhatsAppAgentNotification };
export type WhatsappAgentsNotificationsListQuery = NonNullable<ListWhatsAppAgentNotificationsData["query"]>;
export type WhatsappAgentsNotificationsCreateParams = NonNullable<CreateWhatsAppAgentNotificationData["body"]>;

export class WhatsappAgentsNotificationsResource extends Resource {
  /**
   * List the notifications sent to the agents on your WhatsApp numbers, newest first, each with what came of it, as a cursor page. Filter by `from` for one number's agent.
   *
   * @example Find what an agent skipped
   * const notifications = await bird.whatsapp.agents.notifications.list({
   *   from: "+13124495648",
   *   status: "skipped",
   * });
   * for (const notification of notifications.data ?? []) {
   *   console.log(notification.name, notification.skipped_reason);
   * }
   */
  list(query?: WhatsappAgentsNotificationsListQuery, options?: RequestOptions): PaginatedPromise<WhatsAppAgentNotification> {
    return this.paginated<WhatsAppAgentNotification>("GET", options, ({ signal, headers }, cursor) =>
      listWhatsAppAgentNotifications({ client: this.client, query: { ...query, starting_after: cursor ?? query?.starting_after, ending_before: cursor === undefined ? query?.ending_before : undefined }, headers, signal }));
  }

  /**
   * Tell the agent on the `from` business number that something happened in your systems for one contact, such as a payment landing or an order shipping, so it can write to them about it. The notification is handed to WhatsApp in the background; read it back with `whatsapp.agents.notifications.get` to see whether the agent acted on it.
   *
   * @example Tell an agent something happened
   * // The agent decides whether and how to tell the contact. The answer reads
   * // accepted; read it back to see whether the agent acted on it.
   * const notification = await bird.whatsapp.agents.notifications.create({
   *   from: "+13124495648",
   *   to: "+14155551234",
   *   name: "order_shipped",
   *   description: "Order 88213 left the warehouse and arrives on Thursday.",
   *   payload: JSON.stringify({ order_id: "88213", carrier: "ACME Courier" }),
   * });
   * console.log(notification.id, notification.status);
   */
  create(params: WhatsappAgentsNotificationsCreateParams, options?: RequestOptions): APIPromise<WhatsAppAgentNotification> {
    return this.call<WhatsAppAgentNotification>("POST", options, ({ signal, headers }) =>
      createWhatsAppAgentNotification({ client: this.client, body: params, headers, signal }));
  }

  /**
   * Read one notification sent to one of your agents, with what came of it.
   *
   * @example Read what came of a notification
   * // A notification still on its way to WhatsApp is not readable yet, so a read
   * // straight after create can throw a not-found error.
   * const notification = await bird.whatsapp.agents.notifications.get("waan_01krdgeqcxet5s7t44vh8rt9m7");
   * console.log(notification.status, notification.skipped_reason ?? notification.error?.description);
   */
  get(notificationId: string, options?: RequestOptions): APIPromise<WhatsAppAgentNotification> {
    return this.call<WhatsAppAgentNotification>("GET", options, ({ signal, headers }) =>
      getWhatsAppAgentNotification({ client: this.client, path: { notification_id: notificationId }, headers, signal }));
  }
}
