// Code generated by surface-gen; DO NOT EDIT.
import { getWhatsAppBusinessAccount, listWhatsAppBusinessAccounts } from "../generated/sdk.gen.js";
import type { GetWhatsAppBusinessAccountData, ListWhatsAppBusinessAccountsData, WhatsAppBusinessAccount } from "../generated/types.gen.js";
import { Resource } from "./base.js";
import type { APIPromise, PaginatedPromise, RequestOptions } from "../core/result.js";

export type { WhatsAppBusinessAccount };
export type WhatsappBusinessAccountsListQuery = NonNullable<ListWhatsAppBusinessAccountsData["query"]>;

export class WhatsappBusinessAccountsResource extends Resource {
  /**
   * List the WhatsApp Business Accounts the workspace has connected, as a cursor page, with the state WhatsApp reports for each. The `waba` a returned account carries is the same value that ties a number to its account, and the one `whatsapp.numbers.list`'s `waba` filter takes.
   *
   * @example List the accounts behind your senders
   * for await (const account of bird.whatsapp.businessAccounts.list()) {
   *   console.log(account.id, account.name, account.status);
   * }
   */
  list(query?: WhatsappBusinessAccountsListQuery, options?: RequestOptions): PaginatedPromise<WhatsAppBusinessAccount> {
    return this.paginated<WhatsAppBusinessAccount>("GET", options, ({ signal, headers }, cursor) =>
      listWhatsAppBusinessAccounts({ client: this.client, query: { ...query, starting_after: cursor ?? query?.starting_after, ending_before: cursor === undefined ? query?.ending_before : undefined }, headers, signal }));
  }

  /**
   * Read one connected WhatsApp Business Account by its `id` (`waa_` prefix) or the ID WhatsApp reports in `waba`, with the state WhatsApp reports for the account.
   *
   * @example Read one account's review state
   * const account = await bird.whatsapp.businessAccounts.get("waa_01krdgeqcxet5s7t44vh8rt9mg");
   * console.log(account.account_review_status, account.business_verification_status);
   */
  get(businessAccountRef: string, options?: RequestOptions): APIPromise<WhatsAppBusinessAccount> {
    return this.call<WhatsAppBusinessAccount>("GET", options, ({ signal, headers }) =>
      getWhatsAppBusinessAccount({ client: this.client, path: { business_account_ref: businessAccountRef }, headers, signal }));
  }
}
