// Code generated by surface-gen; DO NOT EDIT.
import { getWhatsAppInboundStatsByPhoneNumber, getWhatsAppInboundStatsDaily, getWhatsAppInboundStatsHourly, getWhatsAppInboundStatsSummary } from "../generated/sdk.gen.js";
import type { GetWhatsAppInboundStatsByPhoneNumberData, GetWhatsAppInboundStatsDailyData, GetWhatsAppInboundStatsHourlyData, GetWhatsAppInboundStatsSummaryData, WhatsAppInboundStatsByPhoneNumberResponse, WhatsAppInboundStatsResponse, WhatsAppInboundStatsSummaryResponse } from "../generated/types.gen.js";
import { Resource } from "./base.js";
import type { APIPromise, RequestOptions } from "../core/result.js";

export type { WhatsAppInboundStatsSummaryResponse };
export type { WhatsAppInboundStatsResponse };
export type { WhatsAppInboundStatsByPhoneNumberResponse };
export type WhatsappStatsInboundSummaryQuery = NonNullable<GetWhatsAppInboundStatsSummaryData["query"]>;
export type WhatsappStatsInboundDailyQuery = NonNullable<GetWhatsAppInboundStatsDailyData["query"]>;
export type WhatsappStatsInboundHourlyQuery = NonNullable<GetWhatsAppInboundStatsHourlyData["query"]>;
export type WhatsappStatsInboundByPhoneNumberQuery = NonNullable<GetWhatsAppInboundStatsByPhoneNumberData["query"]>;

export class WhatsappStatsInboundResource extends Resource {
  /**
   * Aggregate count of the WhatsApp messages your workspace received in one window, with the delta against the window immediately before when `compare` is set to `previous_period`. Inbound is counted separately from outbound: this answers "how much are customers writing to us", where `whatsapp.stats.summary` answers "how much are we sending".
   *
   * @example Total messages received
   * const summary = await bird.whatsapp.stats.inbound.summary({ from: "2026-05-01", to: "2026-05-31" });
   * console.log(summary.received);
   */
  summary(query?: WhatsappStatsInboundSummaryQuery, options?: RequestOptions): APIPromise<WhatsAppInboundStatsSummaryResponse> {
    return this.call<WhatsAppInboundStatsSummaryResponse>("GET", options, ({ signal, headers }) =>
      getWhatsAppInboundStatsSummary({ client: this.client, query, headers, signal }));
  }

  /**
   * Received WhatsApp message counts, one row per calendar day of the window, gap-filled so a silent day is a zero row. Days are calendar days in `timezone`, or UTC when it is omitted. Max window 365 days; `from` and `to` default to the trailing 30 days.
   *
   * @example Received messages per day
   * const stats = await bird.whatsapp.stats.inbound.daily({ from: "2026-05-01", to: "2026-05-31" });
   * for (const point of stats.data ?? []) {
   *   console.log(point.bucket, point.received);
   * }
   */
  daily(query?: WhatsappStatsInboundDailyQuery, options?: RequestOptions): APIPromise<WhatsAppInboundStatsResponse> {
    return this.call<WhatsAppInboundStatsResponse>("GET", options, ({ signal, headers }) =>
      getWhatsAppInboundStatsDaily({ client: this.client, query, headers, signal }));
  }

  /**
   * Received WhatsApp message counts, one row per hour, gap-filled. A window spans at most 720 hours (30 days); for anything longer use `whatsapp.stats.inbound.daily`. `from` and `to` are optional RFC 3339 instants.
   *
   * @example Received messages per hour
   * const stats = await bird.whatsapp.stats.inbound.hourly({
   *   from: "2026-05-30T00:00:00Z",
   *   to: "2026-05-31T00:00:00Z",
   * });
   * for (const point of stats.data ?? []) {
   *   console.log(point.bucket, point.received);
   * }
   */
  hourly(query?: WhatsappStatsInboundHourlyQuery, options?: RequestOptions): APIPromise<WhatsAppInboundStatsResponse> {
    return this.call<WhatsAppInboundStatsResponse>("GET", options, ({ signal, headers }) =>
      getWhatsAppInboundStatsHourly({ client: this.client, query, headers, signal }));
  }

  /**
   * Received WhatsApp message counts grouped by the business number that received them, ranked by volume. Use it to see which of your numbers customers actually write to. Cap the rows with `limit` (default 50, max 200).
   *
   * @example Which number took the traffic
   * const stats = await bird.whatsapp.stats.inbound.byPhoneNumber({ from: "2026-05-01", to: "2026-05-31" });
   * for (const row of stats.data ?? []) {
   *   console.log(row.phone_number, row.received);
   * }
   */
  byPhoneNumber(query?: WhatsappStatsInboundByPhoneNumberQuery, options?: RequestOptions): APIPromise<WhatsAppInboundStatsByPhoneNumberResponse> {
    return this.call<WhatsAppInboundStatsByPhoneNumberResponse>("GET", options, ({ signal, headers }) =>
      getWhatsAppInboundStatsByPhoneNumber({ client: this.client, query, headers, signal }));
  }
}
