// Code generated by surface-gen; DO NOT EDIT.
import { getWhatsAppNumberProfile } from "../generated/sdk.gen.js";
import type { GetWhatsAppNumberProfileData, WhatsAppNumberProfile } from "../generated/types.gen.js";
import { Resource } from "./base.js";
import type { APIPromise, RequestOptions } from "../core/result.js";

export type { WhatsAppNumberProfile };

export class WhatsappNumbersProfileResource extends Resource {
  /**
   * Read the business profile WhatsApp shows to people a connected number messages.
   *
   * @example Read the profile people see in WhatsApp
   * const profile = await bird.whatsapp.numbers.profile.get("wan_01krdgeqcxet5s7t44vh8rt9mg");
   * console.log(profile.display_name, profile.description, profile.websites);
   */
  get(numberId: string, options?: RequestOptions): APIPromise<WhatsAppNumberProfile> {
    return this.call<WhatsAppNumberProfile>("GET", options, ({ signal, headers }) =>
      getWhatsAppNumberProfile({ client: this.client, path: { number_id: numberId }, headers, signal }));
  }
}
