// Code generated by surface-gen; DO NOT EDIT.
import { createWhatsAppGroup, deleteWhatsAppGroup, getWhatsAppGroup, listWhatsAppGroups, updateWhatsAppGroup } from "../generated/sdk.gen.js";
import type { CreateWhatsAppGroupData, DeleteWhatsAppGroupData, GetWhatsAppGroupData, ListWhatsAppGroupsData, UpdateWhatsAppGroupData, WhatsAppGroup } from "../generated/types.gen.js";
import { Resource } from "./base.js";
import type { APIPromise, PaginatedPromise, RequestOptions } from "../core/result.js";
import type { FetchOutcome } from "../core/http.js";

export type { WhatsAppGroup };
export type WhatsappGroupsCreateParams = NonNullable<CreateWhatsAppGroupData["body"]>;
export type WhatsappGroupsListQuery = NonNullable<ListWhatsAppGroupsData["query"]>;
export type WhatsappGroupsUpdateParams = NonNullable<UpdateWhatsAppGroupData["body"]>;

export class WhatsappGroupsResourceBase extends Resource {
  /**
   * Create a WhatsApp group administered by one of your business numbers. The number must hold Official Business Account status, which `whatsapp.numbers.list` reports as is_official_business_account. The response is the accepted group with status pending; WhatsApp confirms it moments later, which is when the group gains its invite link and becomes messageable. Re-read the group until its status is active.
   *
   * @example Create a group on a business number
   * const group = await bird.whatsapp.groups.create({
   *   whatsapp_number_id: "wan_01krdgeqcxet5s7t44vh8rt9mg",
   *   subject: "Norwood Fleet — Tuesday route",
   * });
   * console.log(group.id, group.status); // pending; read it back for the invite link
   */
  create(params: WhatsappGroupsCreateParams, options?: RequestOptions): APIPromise<WhatsAppGroup> {
    return this.call<WhatsAppGroup>("POST", options, ({ signal, headers }) =>
      createWhatsAppGroup({ client: this.client, body: params, headers, signal }));
  }

  /**
   * List the WhatsApp groups your workspace created, newest first, as a cursor page. Each carries its subject, status, invite link and participant count. Filter by the business number that administers the group (number), by the WhatsApp Business Account it sends under (waba), by status, or search subjects and descriptions with q. Each group includes its participants.
   *
   * @example Walk the workspace's groups
   * for await (const group of bird.whatsapp.groups.list()) {
   *   console.log(group.id, group.subject, group.participant_count);
   * }
   */
  list(query?: WhatsappGroupsListQuery, options?: RequestOptions): PaginatedPromise<WhatsAppGroup> {
    return this.paginated<WhatsAppGroup>("GET", options, ({ signal, headers }, cursor) =>
      listWhatsAppGroups({ client: this.client, query: { ...query, starting_after: cursor ?? query?.starting_after, ending_before: cursor === undefined ? query?.ending_before : undefined }, headers, signal }));
  }

  /**
   * Read one WhatsApp group: its subject, description, status, invite link, and who is in it. Poll it after creating a group to see status move from pending to active, which is when the invite link appears.
   *
   * @example Read a group back until it is active
   * const group = await bird.whatsapp.groups.get("wag_01krdgeqcxet5s7t44vh8rt9mg");
   * console.log(group.status, group.invite_link);
   */
  get(groupId: string, options?: RequestOptions): APIPromise<WhatsAppGroup> {
    return this.call<WhatsAppGroup>("GET", options, ({ signal, headers }) =>
      getWhatsAppGroup({ client: this.client, path: { group_id: groupId }, headers, signal }));
  }

  /**
   * Change a group's subject, description or picture. Fields you omit are left alone. WhatsApp applies each field separately, so one can be refused while the others take effect. Only an active group can be changed.
   *
   * @example Rename a group
   * const group = await bird.whatsapp.groups.update("wag_01krdgeqcxet5s7t44vh8rt9mg", {
   *   subject: "Norwood Fleet — Wednesday route",
   * });
   * console.log(group.last_operation?.status); // pending until WhatsApp reports back
   */
  update(groupId: string, params: WhatsappGroupsUpdateParams = {}, options?: RequestOptions): APIPromise<WhatsAppGroup> {
    return this.call<WhatsAppGroup>("PATCH", options, ({ signal, headers }) =>
      updateWhatsAppGroup({ client: this.client, path: { group_id: groupId }, body: params, headers, signal }));
  }

  /**
   * Delete a group. Every participant loses access, including your business, and the invite link stops working. Terminal and not reversible; the group stays readable with status deleted.
   *
   * @example Delete a group
   * const group = await bird.whatsapp.groups.delete("wag_01krdgeqcxet5s7t44vh8rt9mg");
   * console.log(group.last_operation?.status); // pending until WhatsApp confirms it
   */
  delete(groupId: string, options?: RequestOptions): APIPromise<WhatsAppGroup> {
    return this.call<WhatsAppGroup>("DELETE", options, ({ signal, headers }) =>
      deleteWhatsAppGroup({ client: this.client, path: { group_id: groupId }, headers, signal }));
  }
}
