// Code generated by surface-gen; DO NOT EDIT.
import { deleteWhatsAppMessageReaction, listWhatsAppMessageReactionEvents, upsertWhatsAppMessageReaction } from "../generated/sdk.gen.js";
import type { DeleteWhatsAppMessageReactionData, ListWhatsAppMessageReactionEventsData, UpsertWhatsAppMessageReactionData, WhatsAppReactionAccepted, WhatsAppReactionEvent } from "../generated/types.gen.js";
import { Resource } from "./base.js";
import type { APIPromise, PaginatedPromise, RequestOptions } from "../core/result.js";
import type { FetchOutcome } from "../core/http.js";

export type { WhatsAppReactionAccepted };
export type { WhatsAppReactionEvent };
export type WhatsappReactionSetParams = NonNullable<UpsertWhatsAppMessageReactionData["body"]>;
export type WhatsappReactionListEventsQuery = NonNullable<ListWhatsAppMessageReactionEventsData["query"]>;

export class WhatsappReactionResource extends Resource {
  /**
   * Place an emoji reaction on a WhatsApp message the workspace received. You hold at most one reaction per message, so calling this again replaces the emoji rather than adding a second one. The message must be one the contact sent and still resolvable: Bird keeps the id a reaction needs for 15 days, so an older message is a 404. The 202 is the reaction accepted, not delivered: use whatsapp_get and read the message's `reactions` to see what stands, or whatsapp_reaction_list_events for what WhatsApp made of it.
   *
   * @example React to a received message
   * const reaction = await bird.whatsapp.reaction.set("wam_01krdgeqcxet5s7t44vh8rt9mg", {
   *   emoji: "\u{1F44D}",
   * });
   * console.log(reaction.id, reaction.emoji);
   */
  set(messageId: string, params: WhatsappReactionSetParams, options?: RequestOptions): APIPromise<WhatsAppReactionAccepted> {
    return this.call<WhatsAppReactionAccepted>("PUT", options, ({ signal, headers }) =>
      upsertWhatsAppMessageReaction({ client: this.client, path: { message_id: messageId }, body: params, headers, signal }));
  }

  /**
   * Take back the reaction this workspace placed on a WhatsApp message. Removing a reaction from a message you have not reacted to changes nothing and still answers 202. A removal is refused on the same grounds as a placement: a message this workspace sent is a 422, and one Bird can no longer resolve is a 404, on the same 15-day retention. The 202 is the removal accepted, not applied: the reaction leaves the message's `reactions`, readable with whatsapp_get, once WhatsApp confirms it, and whatsapp_reaction_list_events records the removal either way.
   *
   * @example Take your reaction back
   * await bird.whatsapp.reaction.remove("wam_01krdgeqcxet5s7t44vh8rt9mg");
   */
  remove(messageId: string, options?: RequestOptions): APIPromise<void> {
    return this.call<void>("DELETE", options, ({ signal, headers }) =>
      deleteWhatsAppMessageReaction({ client: this.client, path: { message_id: messageId }, headers, signal }) as Promise<FetchOutcome<void>>);
  }

  /**
   * Get every change made to one WhatsApp message's reactions, newest first, as a cursor page ({data, next_cursor, …}): each emoji placed, each one replaced by another, and each one taken back, by the contact and by this workspace alike. Entries carry a status, so a reaction WhatsApp refused is visible here with its error. Use whatsapp_get and read the message's `reactions` instead for what currently stands.
   *
   * @example Follow what became of each reaction
   * for await (const event of bird.whatsapp.reaction.listEvents("wam_01krdgeqcxet5s7t44vh8rt9mg")) {
   *   console.log(event.id, event.emoji, event.status);
   * }
   */
  listEvents(messageId: string, query?: WhatsappReactionListEventsQuery, options?: RequestOptions): PaginatedPromise<WhatsAppReactionEvent> {
    return this.paginated<WhatsAppReactionEvent>("GET", options, ({ signal, headers }, cursor) =>
      listWhatsAppMessageReactionEvents({ client: this.client, path: { message_id: messageId }, query: { ...query, starting_after: cursor ?? query?.starting_after }, headers, signal }));
  }
}
