// Code generated by surface-gen; DO NOT EDIT.
import { getWhatsAppNumber, listWhatsAppNumberEvents, listWhatsAppNumbers } from "../generated/sdk.gen.js";
import type { GetWhatsAppNumberData, ListWhatsAppNumberEventsData, ListWhatsAppNumbersData, WhatsAppNumber, WhatsAppNumberEvent } from "../generated/types.gen.js";
import { Resource } from "./base.js";
import type { APIPromise, PaginatedPromise, RequestOptions } from "../core/result.js";

export type { WhatsAppNumber };
export type { WhatsAppNumberEvent };
export type WhatsappNumbersListQuery = NonNullable<ListWhatsAppNumbersData["query"]>;
export type WhatsappNumbersListEventsQuery = NonNullable<ListWhatsAppNumberEventsData["query"]>;

export class WhatsappNumbersResourceBase extends Resource {
  /**
   * List the WhatsApp numbers the workspace can send from as a cursor page, with each number's WhatsApp state, quality rating, messaging limit, throughput, and Official Business Account status.
   *
   * @example See the numbers a send can go out from
   * for await (const number of bird.whatsapp.numbers.list({ status: ["connected"] })) {
   *   console.log(number.id, number.phone_number, number.status);
   * }
   */
  list(query?: WhatsappNumbersListQuery, options?: RequestOptions): PaginatedPromise<WhatsAppNumber> {
    return this.paginated<WhatsAppNumber>("GET", options, ({ signal, headers }, cursor) =>
      listWhatsAppNumbers({ client: this.client, query: { ...query, starting_after: cursor ?? query?.starting_after }, headers, signal }));
  }

  /**
   * Read a WhatsApp number and the state WhatsApp reports for it. `next` says what to do about that state, including the browser step that finishes a connection while `status` is `awaiting_signup`.
   *
   * @example Read one number and what WhatsApp allows it
   * const number = await bird.whatsapp.numbers.get("wan_01krdgeqcxet5s7t44vh8rt9mg");
   * console.log(number.status, number.quality_rating, number.messaging_limit);
   */
  get(numberId: string, options?: RequestOptions): APIPromise<WhatsAppNumber> {
    return this.call<WhatsAppNumber>("GET", options, ({ signal, headers }) =>
      getWhatsAppNumber({ client: this.client, path: { number_id: numberId }, headers, signal }));
  }

  /**
   * The activity history of one WhatsApp number as a cursor page, newest first: when it was added, every change of its status, its messaging-limit and quality-rating changes, and each display-name review decision. This is the read that answers "why did this number's status, limit, or name change"; `whatsapp.numbers.get` gives only the current values. An unknown number ID returns `404`.
   *
   * @example Follow how a number reached its state
   * for await (const event of bird.whatsapp.numbers.listEvents(
   *   "wan_01krdgeqcxet5s7t44vh8rt9mg",
   * )) {
   *   console.log(event.created_at, event.type, event.summary);
   * }
   */
  listEvents(numberId: string, query?: WhatsappNumbersListEventsQuery, options?: RequestOptions): PaginatedPromise<WhatsAppNumberEvent> {
    return this.paginated<WhatsAppNumberEvent>("GET", options, ({ signal, headers }, cursor) =>
      listWhatsAppNumberEvents({ client: this.client, path: { number_id: numberId }, query: { ...query, starting_after: cursor ?? query?.starting_after }, headers, signal }));
  }
}
