// Code generated by surface-gen; DO NOT EDIT.
import { getCurrentWorkspace } from "../generated/sdk.gen.js";
import type { GetCurrentWorkspaceData, Workspace } from "../generated/types.gen.js";
import { Resource } from "./base.js";
import type { APIPromise, RequestOptions } from "../core/result.js";

export type { Workspace };

export class WorkspaceResource extends Resource {
  /**
   * Fetch the current workspace's ID, name, and the ID of the organization owning it. This is the workspace the current credentials are scoped to.
   *
   * @example Read the workspace this credential is scoped to
   * const workspace = await bird.workspace.get();
   * console.log(workspace.id, workspace.name); // "ws_…" "Production"
   */
  get(options?: RequestOptions): APIPromise<Workspace> {
    return this.call<Workspace>("GET", options, ({ signal, headers }) =>
      getCurrentWorkspace({ client: this.client, headers, signal }));
  }
}
