// Generated by beak gen:docs-snippets — do not edit. Type-checks every TS
// @example snippet so it cannot drift from the SDK's real types.
import { BirdClient } from "@messagebird/sdk";
import { BirdRateLimitError, BirdValidationError, BirdAPIError } from "@messagebird/sdk";

declare const bird: BirdClient;
declare const rawBody: string;
declare const headers: Record<string, string>;

export async function _ex_0() {
await bird.audiences.addContacts("adn_01krdgeqcxet5s7t44vh8rt9mg", {
  contact_ids: ["con_01krdgeqcxet5s7t44vh8rt9mg"],
});
}

export async function _ex_1() {
const audience = await bird.audiences.create({ name: "Newsletter subscribers" });
console.log(audience.id); // "adn_…"
}

export async function _ex_2() {
await bird.audiences.delete("adn_01krdgeqcxet5s7t44vh8rt9mg");
}

export async function _ex_3() {
const audience = await bird.audiences.get("adn_01krdgeqcxet5s7t44vh8rt9mg");
console.log(audience.name);
}

export async function _ex_4() {
for await (const audience of bird.audiences.list()) {
  console.log(audience.id, audience.name);
}
}

export async function _ex_5() {
for await (const member of bird.audiences.listContacts("adn_01krdgeqcxet5s7t44vh8rt9mg")) {
  console.log(member.contact.id, member.joined_at);
}
}

export async function _ex_6() {
await bird.audiences.removeContact(
  "adn_01krdgeqcxet5s7t44vh8rt9mg",
  "con_01krdgeqcxet5s7t44vh8rt9mg",
);
}

export async function _ex_7() {
await bird.audiences.removeContacts("adn_01krdgeqcxet5s7t44vh8rt9mg", {
  contact_ids: ["con_01krdgeqcxet5s7t44vh8rt9mg"],
});
}

export async function _ex_8() {
await bird.audiences.update("adn_01krdgeqcxet5s7t44vh8rt9mg", { name: "Renamed" });
}

export async function _ex_9() {
const bird = new BirdClient({
  apiKey: process.env.BIRD_API_KEY!,
  region: "eu1", // optional; overrides the region from the key prefix
  baseUrl: "http://localhost:8080", // optional; overrides region (local or self-hosted)
  timeout: 60_000, // per-attempt timeout in ms (default 60_000)
  maxRetries: 2, // retry budget for transient failures (default 2)
});
}

export async function _ex_10() {
const prop = await bird.contactProperties.archive("cp_01krdgeqcxet5s7t44vh8rt9mg");
console.log(prop.key, prop.archived);
}

export async function _ex_11() {
const prop = await bird.contactProperties.create({ key: "plan", type: "string" });
console.log(prop.id); // "cp_…"
}

export async function _ex_12() {
const prop = await bird.contactProperties.get("cp_01krdgeqcxet5s7t44vh8rt9mg");
console.log(prop.key, prop.type);
}

export async function _ex_13() {
for await (const prop of bird.contactProperties.list()) {
  console.log(prop.key, prop.type);
}
const page = await bird.contactProperties.list({ limit: 50 }); // page.data, page.next_cursor
}

export async function _ex_14() {
await bird.contactProperties.unarchive("cp_01krdgeqcxet5s7t44vh8rt9mg");
}

export async function _ex_15() {
await bird.contactProperties.update("cp_01krdgeqcxet5s7t44vh8rt9mg", { fallback_value: "free" });
}

export async function _ex_16() {
const result = await bird.contacts.batch({
  contacts: [{ email: "jane@acme.com", first_name: "Jane" }],
});
for (const item of result.data) {
  console.log(item.entry.email, item.status);
}
}

export async function _ex_17() {
const contact = await bird.contacts.create({
  email: "jane@acme.com",
  first_name: "Jane",
});
console.log(contact.id); // "con_…"
}

export async function _ex_18() {
await bird.contacts.delete("con_01krdgeqcxet5s7t44vh8rt9mg");
}

export async function _ex_19() {
const contact = await bird.contacts.get("con_01krdgeqcxet5s7t44vh8rt9mg");
console.log(contact.email, contact.first_name);
}

export async function _ex_20() {
for await (const contact of bird.contacts.list({ q: "acme.com" })) {
  console.log(contact.id, contact.email);
}
const page = await bird.contacts.list({ limit: 50 }); // page.data, page.next_cursor
}

export async function _ex_21() {
for await (const preference of bird.contacts.preferences.list(
  "con_01krdgeqcxet5s7t44vh8rt9mg",
)) {
  console.log(preference.channel, preference.status);
}
}

export async function _ex_22() {
const contact = await bird.contacts.update("con_01krdgeqcxet5s7t44vh8rt9mg", {
  first_name: "Jane",
});
console.log(contact.first_name);
}

export async function _ex_23() {
const domain = await bird.domains.create({ domain: "mail.acme.com" });
console.log(domain.id, domain.status); // "dom_…", "pending"
}

export async function _ex_24() {
await bird.domains.delete("dom_01krdgeqcxet5s7t44vh8rt9mg");
}

export async function _ex_25() {
const domain = await bird.domains.get("dom_01krdgeqcxet5s7t44vh8rt9mg");
console.log(domain.domain);
}

export async function _ex_26() {
for await (const domain of bird.domains.list()) {
  console.log(domain.id, domain.status);
}
}

export async function _ex_27() {
await bird.domains.update("dom_01krdgeqcxet5s7t44vh8rt9mg", {
  settings: { click_tracking: true, open_tracking: true },
  tracking: { name: "links" },
});
}

export async function _ex_28() {
const domain = await bird.domains.verify("dom_01krdgeqcxet5s7t44vh8rt9mg");
console.log(domain.status); // "verified" once DNS is in place
}

export async function _ex_29() {
await bird.email.cancel("em_abc123");
}

export async function _ex_30() {

try {
  await bird.email.send({
    from: { email: "onboarding@messagebird.dev", name: "Bird" },
    to: ["delivered@messagebird.dev"],
    subject: "Hello from Bird",
    html: "<p>My first Bird email.</p>",
  });
} catch (err) {
  if (err instanceof BirdRateLimitError) console.log(`rate limited; retry in ${err.retryAfter}s`);
  else if (err instanceof BirdValidationError) console.error(err.details);
  else if (err instanceof BirdAPIError) console.error(err.code, err.requestId);
  else throw err;
}
}

export async function _ex_31() {
const msg = await bird.email.get("em_abc123");
msg.status; // "accepted" | "processed" | "delivered" | "bounced" | …
msg.delivered_count;
msg.bounced_count;
}

export async function _ex_32() {
for await (const message of bird.email.list({ status: "bounced" })) {
  console.log(message.id);
}
}

export async function _ex_33() {
for await (const message of bird.email.list({ status: "bounced" })) {
  console.log(message.id);
}
const page = await bird.email.list({ limit: 50 }); // page.data, page.next_cursor
}

export async function _ex_34() {
const mailbox = await bird.email.mailboxes.create({ display_name: "Support" });
console.log(mailbox.address); // "abc123@inbox.ai"
}

export async function _ex_35() {
await bird.email.mailboxes.delete("mbx_01abc");
}

export async function _ex_36() {
const mailbox = await bird.email.mailboxes.get("mbx_01abc");
console.log(mailbox.state); // "active"
}

export async function _ex_37() {
const labels = await bird.email.mailboxes.labels("mbx_01abc");
console.log(labels.data.map((label) => label.name));
}

export async function _ex_38() {
for await (const mailbox of bird.email.mailboxes.list()) {
  console.log(mailbox.address);
}
}

export async function _ex_39() {
const msg = await bird.email.mailboxes.messages.create("mbx_01abc", {
  to: ["customer@example.com"],
  subject: "Hello",
  text: "Hi there!",
});
}

export async function _ex_40() {
const rule = await bird.email.mailboxes.receiveRules.create("mbx_01abc", {
  action: "block",
  entry: "spam.example.com",
});
console.log(rule.id);
}

export async function _ex_41() {
await bird.email.mailboxes.receiveRules.delete("mbx_01abc", "erl_01xyz");
}

export async function _ex_42() {
for await (const rule of bird.email.mailboxes.receiveRules.list("mbx_01abc")) {
  console.log(rule.action, rule.entry);
}
}

export async function _ex_43() {
const mailbox = await bird.email.mailboxes.restore("mbx_01abc");
console.log(mailbox.deleted_at); // null
}

export async function _ex_44() {
const mailbox = await bird.email.mailboxes.resume("mbx_01abc");
console.log(mailbox.state); // "active"
}

export async function _ex_45() {
const stats = await bird.email.mailboxes.stats("mbx_01abc");
console.log(stats.summary?.sends_accepted);
}

export async function _ex_46() {
const mailbox = await bird.email.mailboxes.update("mbx_01abc", {
  receive_policy: "open",
});
console.log(mailbox.id, mailbox.receive_policy);
}

export async function _ex_47() {
const { data, error } = await bird.email
  .send({
    from: { email: "onboarding@messagebird.dev", name: "Bird" },
    to: ["delivered@messagebird.dev"],
    subject: "Hello from Bird",
    html: "<p>My first Bird email.</p>",
  })
  .safe();
if (error) console.error(error.message);
else console.log(data.id);
}

export async function _ex_48() {
const msg = await bird.email.send({
  from: { email: "onboarding@messagebird.dev", name: "Bird" },
  to: ["delivered@messagebird.dev"],
  subject: "Hello from Bird",
  html: "<p>My first Bird email.</p>",
});
console.log(msg.id, msg.status); // "em_…", "accepted"
}

export async function _ex_49() {
const msg = await bird.email.send({
  from: { email: "onboarding@messagebird.dev", name: "Bird" },
  to: ["bounce+signup-flow@messagebird.dev"],
  subject: "Sandbox bounce test",
  html: "<p>This message will hard-bounce.</p>",
  tags: [{ name: "flow", value: "signup" }],
  metadata: { test_run: "docs-capture-1" },
});
console.log(msg.id, msg.status); // "em_…", "accepted"
}

export async function _ex_50() {
const batch = await bird.email.sendBatch([
  {
    from: { email: "onboarding@messagebird.dev", name: "Bird" },
    to: ["alice@example.com"],
    subject: "Your receipt",
    html: "<p>Thanks, Alice.</p>",
  },
  {
    from: { email: "onboarding@messagebird.dev", name: "Bird" },
    to: ["bob@example.com"],
    subject: "Your receipt",
    html: "<p>Thanks, Bob.</p>",
  },
]);
for (const item of batch.data) console.log(item.id, item.status);
}

export async function _ex_51() {
const msg = await bird.email.send({
  from: { email: "onboarding@messagebird.dev", name: "Bird" },
  to: ["delivered@messagebird.dev"],
  category: "transactional",
  template: {
    slug: "welcome-email",
    parameters: { first_name: "Jane" },
  },
});
console.log(msg.id, msg.status);
}

export async function _ex_52() {
const { data } = await bird.email.stats.byBounceCode({
  from: "2026-05-01",
  to: "2026-05-31",
  sort: "bounced",
  limit: 25,
});
for (const row of data) console.log(row.smtp_error_code, row.bounced);
}

export async function _ex_53() {
const { data } = await bird.email.stats.byBroadcast({
  from: "2026-05-01",
  to: "2026-05-31",
  sort: "click_rate",
  limit: 25,
});
for (const row of data) console.log(row.broadcast_id, row.engagement.click_rate);
}

export async function _ex_54() {
const { data } = await bird.email.stats.byCategory({ from: "2026-05-01", to: "2026-05-31" });
for (const row of data) console.log(row.category, row.delivery.delivered);
}

export async function _ex_55() {
const { data } = await bird.email.stats.byClient({
  from: "2026-05-01",
  to: "2026-05-31",
  limit: 25,
});
for (const row of data) console.log(row.email_client, row.engagement.unique_opens);
}

export async function _ex_56() {
const { data } = await bird.email.stats.byComplaintType({ from: "2026-05-01", to: "2026-05-31" });
for (const row of data) console.log(row.feedback_type, row.complained);
}

export async function _ex_57() {
const { data } = await bird.email.stats.byLocation({
  from: "2026-05-01",
  to: "2026-05-31",
  limit: 25,
});
for (const row of data) console.log(row.country, row.engagement.unique_opens);
}

export async function _ex_58() {
const { data } = await bird.email.stats.byMailboxProvider({
  from: "2026-05-01",
  to: "2026-05-31",
  limit: 25,
});
for (const row of data) console.log(row.mailbox_provider, row.delivery.delivered);
}

export async function _ex_59() {
const { data } = await bird.email.stats.byMailboxProviderRegion({
  from: "2026-05-01",
  to: "2026-05-31",
  limit: 25,
});
for (const row of data) console.log(row.mailbox_provider, row.mailbox_provider_region, row.delivery.delivered);
}

export async function _ex_60() {
const { data } = await bird.email.stats.byRecipientDomain({
  from: "2026-05-01",
  to: "2026-05-31",
  sort: "bounce_rate",
  limit: 25,
});
for (const row of data) console.log(row.recipient_domain, row.delivery.bounce_rate);
}

export async function _ex_61() {
const { data } = await bird.email.stats.bySendingDomain({
  from: "2026-05-01",
  to: "2026-05-31",
  sort: "delivery_rate",
  limit: 25,
});
for (const row of data) console.log(row.sending_domain, row.delivery.delivery_rate);
}

export async function _ex_62() {
const { data } = await bird.email.stats.bySendingIp({
  from: "2026-05-01",
  to: "2026-05-31",
  sort: "bounces.block",
  limit: 20,
});
for (const row of data) console.log(row.sending_ip, row.delivery.delivered);
}

export async function _ex_63() {
const { data } = await bird.email.stats.byTag({
  from: "2026-05-01",
  to: "2026-05-31",
  sort: "delivered",
  limit: 10,
});
for (const row of data) console.log(row.tag, row.delivery.delivered);
}

export async function _ex_64() {
const { data } = await bird.email.stats.byTemplate({
  from: "2026-05-01",
  to: "2026-05-31",
  sort: "open_rate",
  limit: 25,
});
for (const row of data) console.log(row.template_id, row.engagement.open_rate);
}

export async function _ex_65() {
const series = await bird.email.stats.daily({ from: "2026-05-01", to: "2026-05-31" });
for (const row of series.data) console.log(row.bucket, row.delivery.delivered);
}

export async function _ex_66() {
const series = await bird.email.stats.hourly({ from: "2026-05-01", to: "2026-05-02" });
for (const row of series.data) console.log(row.bucket, row.delivery.delivered);
}

export async function _ex_67() {
const s = await bird.email.stats.summary({ from: "2026-05-01", to: "2026-05-31" });
console.log(s.sends_accepted, s.delivery.delivered);
}

export async function _ex_68() {
await bird.email.threads.delete("thr_01abc", { permanent: true });
}

export async function _ex_69() {
const thread = await bird.email.threads.get("thr_01abc");
console.log(thread.subject);
}

export async function _ex_70() {
for await (const thread of bird.email.threads.list({ mailbox_id: "mbx_01abc" })) {
  console.log(thread.id, thread.subject);
}
}

export async function _ex_71() {
const atts = await bird.email.threads.messages.attachments("thr_01abc", "rem_01xyz");
console.log(atts.data.map((a) => a.filename));
}

export async function _ex_72() {
const body = await bird.email.threads.messages.body("thr_01abc", "rem_01xyz");
console.log(body.text);
}

export async function _ex_73() {
const msg = await bird.email.threads.messages.get("thr_01abc", "rem_01xyz");
console.log(msg.direction); // "inbound"
}

export async function _ex_74() {
for await (const msg of bird.email.threads.messages.list("thr_01abc")) {
  console.log(msg.id, msg.direction);
}
}

export async function _ex_75() {
const reply = await bird.email.threads.messages.reply("thr_01abc", "rem_01xyz", {
  text: "Thanks for reaching out!",
});
console.log(reply.id);
}

export async function _ex_76() {
const thread = await bird.email.threads.update("thr_01abc", {
  labels: { add: ["archive"] },
});
console.log(thread.id);
}

export async function _ex_77() {
const answer = await bird.lookup.email({ email: "aisha.khan@example.com" });
// result is an open vocabulary; delivery_confidence is always comparable.
console.log(answer.result, answer.delivery_confidence);
}

export async function _ex_78() {
const answer = await bird.lookup.phoneNumber({
  phone_number: "+31612345678",
  type: ["classification", "score"],
});
console.log(answer.country_code, answer.line_type);
// Only a block whose status is ok carries a value, and only that one is billed.
if (answer.score?.status === "ok") console.log(answer.score.value);
}

export async function _ex_79() {
// A number a carrier supplies is only on sale while the carrier still has it,
// so a 404 here means someone else took it.
const candidate = await bird.numbers.available.get("+447700900201");
console.log(candidate.country_code, candidate.capabilities);
}

export async function _ex_80() {
// The search is always country-scoped, so country_code is required.
const page = await bird.numbers.available.list({
  country_code: "GB",
  capabilities: ["sms", "voice"],
});
for (const candidate of page.data) {
  console.log(candidate.number, candidate.number_type);
}
}

export async function _ex_81() {
const allocated = await bird.numbers.get("nda_01krdgeqcxet5s7t44vh8rt9mg");
// A country that asks for ownership paperwork answers here; most answer null.
console.log(allocated.status, allocated.ownership ?? "no paperwork required");
}

export async function _ex_82() {
for await (const allocated of bird.numbers.list({ country_code: "GB" })) {
  // kind distinguishes a number you bought from one Bird manages.
  console.log(allocated.number, allocated.kind, allocated.status);
}
}

export async function _ex_83() {
const order = await bird.numbers.orders.create({ number: "+447700900201" });
// Most orders finish inside the request. One that has to wait on a carrier
// comes back without a number_id. Poll it until it is completed or failed.
if (order.status === "completed") {
  console.log("allocated as", order.number_id);
} else {
  console.log("still", order.status, "; poll", order.id);
}
}

export async function _ex_84() {
const order = await bird.numbers.orders.get("nor_01krdgeqcxet5s7t44vh8rt9mg");
// failure_reason says what went wrong, and only ever on a failed order.
console.log(order.status, order.failure_reason ?? "");
}

export async function _ex_85() {
const page = await bird.numbers.orders.list({ status: "failed" });
for (const order of page.data) {
  console.log(order.number, order.failure_reason ?? "");
}
}

export async function _ex_86() {
// Releasing stops the monthly charge and the number stops working for you.
// Only a dedicated number can be released; a shared one answers E14002.
await bird.numbers.release("nda_01krdgeqcxet5s7t44vh8rt9mg");
}

export async function _ex_87() {
const result = await bird.preferences.create({
  channel: "sms",
  handle: "+15550001234",
  status: "revoked",
});
console.log(result.applied, result.preference?.id);
}

export async function _ex_88() {
const result = await bird.preferences.delete("prf_01krdgeqcxet5s7t44vh8rt9mg");
if (!result.applied) {
  console.log("refused — a newer statement survived:", result.preference?.status);
}
}

export async function _ex_89() {
const preference = await bird.preferences.get(
  "prf_01krdgeqcxet5s7t44vh8rt9mg",
);
console.log(preference.status, preference.coverage);
}

export async function _ex_90() {
for await (const preference of bird.preferences.list({ channel: "sms" })) {
  console.log(preference.handle, preference.status);
}
}

export async function _ex_91() {
const channel = await bird.realtime.channels.get("rap_01krdgeqcxet5s7t44vh8rt9mg", "presence-lobby", {
  include: ["member_count"],
});
console.log(channel.occupied, channel.member_count);
}

export async function _ex_92() {
const { data } = await bird.realtime.channels.list("rap_01krdgeqcxet5s7t44vh8rt9mg", {
  prefix: "presence-",
  include: ["member_count"],
});
for (const channel of data) console.log(channel.name, channel.member_count);
}

export async function _ex_93() {
const { members } = await bird.realtime.channels.members("rap_01krdgeqcxet5s7t44vh8rt9mg", "presence-lobby");
for (const member of members) console.log(member.member_id);
}

export async function _ex_94() {
await bird.realtime.members.disconnect("rap_01krdgeqcxet5s7t44vh8rt9mg", "user_42");
}

export async function _ex_95() {
await bird.realtime.members.send("rap_01krdgeqcxet5s7t44vh8rt9mg", "user_42", {
  event: "order-shipped",
  data: { order_id: "ord_123" },
});
}

export async function _ex_96() {
const result = await bird.realtime.publish("rap_01krdgeqcxet5s7t44vh8rt9mg", {
  event: "order.updated",
  channels: ["orders", "presence-lobby"],
  data: { order_id: "ord_123", status: "shipped" },
});
console.log(result.data?.length); // one entry per channel
}

export async function _ex_97() {
await bird.realtime.publishBatch("rap_01krdgeqcxet5s7t44vh8rt9mg", {
  events: [
    { event: "order.created", channel: "orders", data: { id: 1 } },
    { event: "order.updated", channel: "orders", data: { id: 2 } },
  ],
});
}

export async function _ex_98() {
const msg = await bird.sms.get("sms_abc123");
msg.status; // "accepted" | "delivered" | …
}

export async function _ex_99() {
for await (const msg of bird.sms.list({ direction: "outbound" })) {
  console.log(msg.id, msg.status);
}
}

export async function _ex_100() {
const events = await bird.sms.listEvents("sms_abc123");
for (const event of events.data ?? []) {
  console.log(event.type, event.occurred_at);
}
}

export async function _ex_101() {
const msg = await bird.sms.send({
  from: "+15557654321",
  to: "+14155550100",
  text: "Your verification code is 123456.",
  category: "authentication",
});
console.log(msg.id, msg.status);
}

export async function _ex_102() {
const result = await bird.sms.sendBatch([
  {
    from: "+15557654321",
    to: "+15551111111",
    text: "Hi Alice!",
    category: "marketing",
  },
  {
    from: "+15557654321",
    to: "+15552222222",
    text: "Hi Bob!",
    category: "marketing",
  },
]);
}

export async function _ex_103() {
await bird.sms.send({
  to: "+14155550100",
  template: { slug: "bird_otp_verification", parameters: { code: "123456" } },
});
}

export async function _ex_104() {
const stats = await bird.sms.stats.byCarrier({ from: "2026-05-01", to: "2026-05-31" });
for (const row of stats.data ?? []) {
  console.log(row.carrier, row.delivery);
}
}

export async function _ex_105() {
const stats = await bird.sms.stats.byCategory({ from: "2026-05-01", to: "2026-05-31" });
for (const row of stats.data ?? []) {
  console.log(row.category, row.delivery);
}
}

export async function _ex_106() {
const stats = await bird.sms.stats.byCountry({
  from: "2026-05-01",
  to: "2026-05-31",
  sort: "delivery_rate",
});
for (const row of stats.data ?? []) {
  console.log(row.country, row.delivery);
}
}

export async function _ex_107() {
const stats = await bird.sms.stats.byErrorCode({ from: "2026-05-01", to: "2026-05-31" });
for (const row of stats.data ?? []) {
  // The same value as the error_code filter on bird.sms.list.
  console.log(row.error_code, row.delivery);
}
}

export async function _ex_108() {
const stats = await bird.sms.stats.byOriginator({ from: "2026-05-01", to: "2026-05-31" });
for (const row of stats.data ?? []) {
  console.log(row.originator, row.delivery);
}
}

export async function _ex_109() {
const stats = await bird.sms.stats.byStatus({ from: "2026-05-01", to: "2026-05-31" });
for (const row of stats.data ?? []) {
  console.log(row.status, row.count);
}
}

export async function _ex_110() {
const stats = await bird.sms.stats.byTag({ from: "2026-05-01", to: "2026-05-31" });
for (const row of stats.data ?? []) {
  // A message carrying several tags counts once under each, so rows do not sum
  // to the period total.
  console.log(row.tag, row.delivery);
}
}

export async function _ex_111() {
const stats = await bird.sms.stats.daily({ from: "2026-05-01", to: "2026-05-31" });
for (const point of stats.data ?? []) {
  console.log(point.bucket, point.delivery);
}
}

export async function _ex_112() {
const stats = await bird.sms.stats.hourly({
  from: "2026-05-30T00:00:00Z",
  to: "2026-05-31T00:00:00Z",
});
for (const point of stats.data ?? []) {
  console.log(point.bucket, point.delivery);
}
}

export async function _ex_113() {
const stats = await bird.sms.stats.inbound.byCountry({ from: "2026-05-01", to: "2026-05-31" });
for (const row of stats.data ?? []) {
  console.log(row.country, row.received);
}
}

export async function _ex_114() {
const stats = await bird.sms.stats.inbound.byNumber({ from: "2026-05-01", to: "2026-05-31" });
for (const row of stats.data ?? []) {
  console.log(row.number, row.received);
}
}

export async function _ex_115() {
const stats = await bird.sms.stats.inbound.byOperator({ from: "2026-05-01", to: "2026-05-31" });
for (const row of stats.data ?? []) {
  // Messages whose operator the carrier did not report are excluded, so these
  // rows can sum to less than the inbound summary for the same period.
  console.log(row.mcc_mnc, row.received);
}
}

export async function _ex_116() {
const stats = await bird.sms.stats.inbound.daily({ from: "2026-05-01", to: "2026-05-31" });
for (const point of stats.data ?? []) {
  console.log(point.bucket, point.received);
}
}

export async function _ex_117() {
const stats = await bird.sms.stats.inbound.hourly({
  from: "2026-05-30T00:00:00Z",
  to: "2026-05-31T00:00:00Z",
});
for (const point of stats.data ?? []) {
  console.log(point.bucket, point.received);
}
}

export async function _ex_118() {
const summary = await bird.sms.stats.inbound.summary({ from: "2026-05-01", to: "2026-05-31" });
console.log(summary.received);
}

export async function _ex_119() {
const summary = await bird.sms.stats.summary({
  from: "2026-05-01", // both calendar days for a day window, or
  to: "2026-05-31", //   both RFC 3339 instants for an hour window
});
console.log(summary.delivery, summary.latency);
}

export async function _ex_120() {
const tpl = await bird.smsTemplates.get("bird_otp_verification");
console.log(tpl.body, tpl.variables);
}

export async function _ex_121() {
const { data } = await bird.smsTemplates.list({ scope: "system" });
for (const tpl of data) console.log(tpl.id, tpl.slug);
}

export async function _ex_122() {
const rule = await bird.smsKeywordRules.create({
  operation: "stop",
  country: "NL",
  reply: "You are unsubscribed from MyBrand. Reply START to resume.",
});
// effective_keywords is Bird's set plus any of your own.
console.log(rule.id, rule.effective_keywords);
}

export async function _ex_123() {
await bird.smsKeywordRules.delete("skr_abc123");
}

export async function _ex_124() {
const rule = await bird.smsKeywordRules.get("skr_abc123");
console.log(rule.operation, rule.reply);
}

export async function _ex_125() {
const rules = await bird.smsKeywordRules.list({ country: "NL" });
for (const rule of rules.data) {
  console.log(rule.operation, rule.keywords);
}
}

export async function _ex_126() {
// Omitting keywords leaves the set alone; an empty array clears your additions
// back to Bird's.
const rule = await bird.smsKeywordRules.update("skr_abc123", {
  reply: "You are unsubscribed. Reply START to resume.",
});
console.log(rule.reply);
}

export async function _ex_127() {
// A suppression covers one sender and one subscriber, so stopping every sender
// means one call per sender.
const suppression = await bird.smsSuppressions.add({
  destination: "+15550001234",
  originator: "+15557654321",
});
console.log(suppression.id);
}

export async function _ex_128() {
const suppression = await bird.smsSuppressions.get("sup_abc123");
console.log(suppression.reason, suppression.blocking);
}

export async function _ex_129() {
for await (const suppression of bird.smsSuppressions.list()) {
  console.log(suppression.originator, suppression.destination, suppression.reason);
}
}

export async function _ex_130() {
// Only a `manual` suppression can be ended: a subscriber's own stop keyword and
// a carrier's opt-out are refused.
await bird.smsSuppressions.remove("sup_abc123");
}

export async function _ex_131() {
const result = await bird.verify.verifications.check({
  to: { phone_number: "+15551234567" },
  code: "123456",
});
console.log(result.success);
}

export async function _ex_132() {
const verification = await bird.verify.verifications.create({
  to: { phone_number: "+15551234567" },
});
console.log(verification.id, verification.status);
}

export async function _ex_133() {
const verification = await bird.verify.verifications.nextChannel({
  to: { phone_number: "+15551234567" },
});
console.log(verification.last_channel);
}

export async function _ex_134() {
const call = await bird.voice.get("vcl_01k0p3v9wera3v6q6xw3e9y2mh");
// A call still ringing or connected carries no economics yet.
call.status; // "answered" | "no_answer" | "ringing" | …
}

export async function _ex_135() {
for await (const call of bird.voice.list({ status: ["ringing", "in_progress"] })) {
  console.log(call.id, call.status);
}
}

export async function _ex_136() {
// Pass the RAW request body; set the secret via new BirdClient({ webhooks: { secret } }).
const event = bird.webhooks.unwrap(rawBody, headers);
console.log(event.type); // discriminated union: narrow on event.type
}

export async function _ex_137() {
const msg = await bird.whatsapp.get("wa_abc123");
msg.status; // "accepted" | "delivered" | …
}

export async function _ex_138() {
for await (const msg of bird.whatsapp.list({ status: ["delivered"] })) {
  console.log(msg.id, msg.status);
}
}

export async function _ex_139() {
const { data } = await bird.whatsapp.listEvents("wa_abc123");
for (const event of data) console.log(event.type, event.occurred_at);
}

export async function _ex_140() {
const msg = await bird.whatsapp.send({
  to: "+15551234567",
  template: {
    slug: "bird_otp",
    components: [{ type: "body", parameters: [{ type: "text", text: "123456" }] }],
  },
});
console.log(msg.id, msg.status);
}
